src/rebar3.erl, src/rebar_app_info.erl, src/rebar_prv_compile.erl, src/rebar_prv_install_deps.erl, src/rebar_state.erl
Not ready to merge, it doesn't work with a lock file. Opening for comment.
=> overrides working except for transitive dep inheritance with lock file

src/rebar_state.erl
pretty sure this was just a typo
=> change `rebar_app_into` to `rebar_app_info` in typespecs

src/rebar_prv_common_test.erl, src/rebar_prv_eunit.erl
=> change more instances of mistyped `erl_first_modules` to `erl_first_files`

rebar.config.sample
=> Add documentation for {ref, <sha>} syntax rebar.config.sample file

test/rebar_dialyzer_SUITE.erl
=> Add dialyzer tests

src/rebar_git_resource.erl
Fix for https://github.com/rebar/rebar3/issues/151
=> needs_update: on ref defined deps only have to match prefix if 7+ chars

src/rebar_app_discover.erl, src/rebar_prv_install_deps.erl, src/rebar_utils.erl, test/rebar_deps_SUITE.erl
Fix for https://github.com/rebar/rebar3/issues/146
=> use project sub-apps with deps in their rebar.config

src/rebar_otp_app.erl, src/rebar_plugins.erl, src/rebar_prv_compile.erl
Fix for https://github.com/rebar/rebar3/issues/149
=> update project app list with new appinfo records after build

src/rebar_prv_install_deps.erl
- Make functions shorter
- Unnest some functions
- Split up and give names to major conditional branches
It's a big piece to review and I made some arbitrary style
choices (regrouping some arguments on fewer lines) because I felt
it made things easier to read, but feel free to ask me to reverse these bits!
=> Refactor install deps

src/rebar3.erl, src/rebar_prv_release.erl, src/rebar_prv_tar.erl, test/rebar_release_SUITE.erl, test/rebar_test_utils.erl
I don't know why this blows up the way it does. Opening this PR so I can get some help.
=> release and tar tests

src/rebar_config.erl
=> don't attempt to merge locks when there are no dependencies

src/rebar_erlc_compiler.erl, test/rebar_compile_SUITE.erl
=> don't unescessarily recompile yrl/xrl files

src/rebar_digraph.erl, src/rebar_pkg_resource.erl, src/rebar_prv_install_deps.erl, src/rebar_prv_update.erl, test/mock_pkg_resource.erl, test/rebar_install_deps_SUITE.erl, test/rebar_test_utils.erl, test/rebar_upgrade_SUITE.erl
Adding test and support for package upgrades.
-- Mixed upgrades / dep sets are still kind of missing, and I think that src deps will take precedence over pkg deps by order of fetch
=> Upgrade pkg

src/rebar_utils.erl
See https://github.com/rebar/rebar/pull/458
=> Port env var expension fix from rebar2

src/rebar_state.erl, test/rebar_profiles_SUITE.erl
=> don't replace non-string list with empty list in profile merge

test/rebar_resource_SUITE.erl
The session was unfruitful, but I guess the tests were not necessarily
=> Some free tests from a debugging session

src/rebar.hrl, src/rebar3.erl, src/rebar_app_discover.erl, src/rebar_app_info.erl, src/rebar_app_utils.erl, src/rebar_dir.erl, src/rebar_erlc_compiler.erl, src/rebar_file_utils.erl, src/rebar_otp_app.erl, src/rebar_prv_clean.erl, src/rebar_prv_common_test.erl, src/rebar_prv_compile.erl, src/rebar_prv_eunit.erl, src/rebar_prv_install_deps.erl, src/rebar_prv_xref.erl, src/rebar_state.erl, test/rebar_compile_SUITE.erl, test/rebar_test_utils.erl, test/rebar_xref_SUITE.erl
This is more a work in progress because I'm not positive we want to go this way. But here is an implementation we can play with.
=> make base_dir for a run include the profiles in path, link to shared dep

src/rebar_prv_common_test.erl, src/rebar_prv_cover.erl, test/rebar_cover_SUITE.erl
=> move `_logs` and `_cover` to `_build` dir

src/rebar_dir.erl, test/rebar_as_SUITE.erl
=> shorter build dirs

src/rebar_prv_common_test.erl
Fixes #215.
Fixes #217.
When using the `suite` option there must only be one or no `dir` listed. Therefore don't include the test directories when there is a suite list. In order to name tests consistently assume the suites are a list of modules and find their full paths.
=> Don't include directories when testing subset of ct suites

src/rebar_prv_common_test.erl
* Return error on failed and/or auto skipped tests
* Print all results for repeated quiet tests
* Sum results of repeated tests
=> Fix handling of ct results

src/rebar3.erl, src/rebar_core.erl, src/rebar_prv_install_deps.erl
=> fix code path update for deps

src/rebar_prv_as.erl, test/rebar_as_SUITE.erl
=> parse `rebar3 as foo, bar task` correctly

README.md, src/rebar.app.src
Of course there are still bugs to fix, but we're likely good to go.
=> Bump to alpha

src/rebar_templater.erl
=> templater: return error, don't throw, if git or hg fail

rebar.config
=> Revert "disable smp in escript"

src/rebar_base_compiler.erl, src/rebar_prv_compile.erl
We should compile apps in parallel not erl files.
=> get rid of compile workers

src/rebar_api.erl, src/rebar_prv_app_discovery.erl, src/rebar_prv_common_test.erl, src/rebar_prv_dialyzer.erl, src/rebar_prv_eunit.erl, src/rebar_prv_update.erl, src/rebar_prv_upgrade.erl, src/rebar_prv_xref.erl
=> use PRV_ERROR for formattable errors

test/rebar_release_SUITE.erl, test/rebar_test_utils.erl
Add one test case to verify the dev_mode option for a release and
another to verify overriding the dev_mode option in a profile for a
release. Verification of proper dev_mode functioning is done in the
rebar_test_utils:check_results/2 function by checking if all the
directories in the release lib dir are symlinks or not and comparing
that result to the dev_mode expectation passed as input to
the check_results function.
=> Test cases to exercise the dev_mode release option

THANKS, src/rebar_base_compiler.erl, src/rebar_erlc_compiler.erl, test/rebar_compile_SUITE.erl
In an attempt to keep up with shared code between rebar3 and rebar2 I've merged in https://github.com/rebar/rebar/pull/467. 
@kejv would be great if you took a look in case I got anything wrong :)
=> merge rebar2's Refactor logic and optimizations in rebar_erlc_compiler:doterl_compile/4 #467

src/rebar_prv_common_test.erl
=> disallow suites in project root

src/rebar_erlc_compiler.erl
Now check if it is a proper `-include_lib` before trying to check if the file exists. Also check both the src dir and include dir of the app to see if the file exists. And output a nice warning to the user that their usage if wrong.
=> Warn on bad use of include_lib but try to find the header anyway

src/rebar_prv_common_test.erl
* Use throw..catch instead of error..catch to be explicit about what is caught and not to catch unexpected errors that can't be formatted.
* Handle `run_test/2` returning `{error, {failures_running_tests, _}}`.
* Run post hooks if no tests run to match eunit provider.
=> Improve error handling in ct provider

rebar.config, src/rebar_app_discover.erl, src/rebar_app_utils.erl, src/rebar_digraph.erl, src/rebar_prv_compile.erl
Fix for https://github.com/rebar/rebar3/issues/338
=> include applications list in compile sort

src/rebar_erlc_compiler.erl
Fix for https://github.com/rebar/rebar3/issues/355
=> fix erl_first_files to check entire path of file

src/rebar_prv_install_deps.erl, test/rebar_install_deps_SUITE.erl
=> Symlink existing default deps when in new profile

src/rebar_templater.erl
This is useful for if you use rebar as a lib or calling it from outside an escript.
=> support templates even when not run as escript

src/rebar_prv_install_deps.erl
They can be culled and reused in one sort pass.
=> Avoid topsorting deps twice

src/rebar_erlc_compiler.erl, test/mock_pkg_resource.erl, test/rebar_compile_SUITE.erl, test/rebar_test_utils.erl
Port of @kejv 's https://github.com/rebar/rebar/pull/477
=> enable parse transformations in rebar config

rebar.config
I don't exactly like this solution... but it works and fixes https://github.com/rebar/rebar3/issues/385
=> include relx templates in escript

src/rebar_dir.erl, src/rebar_state.erl, test/rebar_profiles_SUITE.erl
Same as #350 from @kovyl2404 but with an explicit test checking directory paths get properly merged too.
=> Kovyl2404 app discover profile duplication

src/rebar_prv_deps.erl
Whenever files were being locked *and* provided in rebar.config
duplicates could be printed. This is taken care of.
Also whenever atom packages were being used, they would cause the merge
step to fail. The new format does proper name-based deduplication of
resources, giving priority to locks to work.
Modification/needs-update support is still in.
This may also act as a fix for #341, if automation isn't required too
much.
Oh also the help is fixed for the provider.
=> Fix dupes in deps provider, support atom pkgs

src/rebar3.erl, src/rebar_otp_app.erl, src/rebar_prv_deps.erl, src/rebar_state.erl, src/rebar_utils.erl
To compile, this will need to properly inherit global config attributes.
@tsloughter it's what we discussed earlier today.
=> Use resource handlers to deal with deps/semver

src/rebar_prv_shell.erl
I want `rebar3 shell` to load my application configuration. I'm not sure if that makes sense, or if this is a reasonable way of going about it.
What do you think?
=> try to read sys.config when running `rebar shell`

src/rebar_packages.erl, src/rebar_prv_install_deps.erl
Fix for https://github.com/rebar/rebar3/issues/406
=> check registry for missing package that may exist for mix

src/rebar_prv_dialyzer.erl
The first commit is the first commit from #282. Unknowns are nolonger separated from other warnings. In 18.0 there will be a warning flag for unknown warnings `unknown` (and in 17.3+ there is an undocumented `no_unknown` flag).
The second commit resolves #376 by writing all warnings to a file. The output file is not configurable (yet) as configuration might be changing in #282 and I didn't want to introduce a new configuration only to change it. If there are warnings the output file name is printed for convenience.
=> Dialyzer output file

src/rebar_prv_common_test.erl
=> when compiling ct dirs base compiler input dir on project root rather than profile root

src/rebar_erlc_compiler.erl
to avoid repeated loading and unloading of modules
this was done once before in #222 which fixed a bunch of issues but i think it was reverted in #323 somehow
=> remove use of `code:load_abs/1` in favor of `beam_lib:chunks/2`

README.md
Related to https://github.com/rebar/rebar3/issues/416. It fails right now, but shows we care and are working on it :)
=> add Windows build badge

src/rebar_prv_tar.erl
=> reverse relx config so profile settings are used properly

src/rebar_prv_shell.erl
When swapping handlers, if a custom shell has been installed, it's
possible it'll take over the tty and other options. This may break
common operations that work on an otherwise regular shell, so we ignore
failures and let things work with the custom shell only.
=> Handle custom logger shell breakage

src/rebar_prv_dialyzer.erl
First step towards rebar2 compatibility.
* Only include direct dependencies + base plt
* Error on missing direct dependency
* Always use beams in ebin instead of reading .app file (copying rebar2)
* Remove fake unknown warnings (will clash with unknown warning in 18.0)
* Remove redundant search for .app file (code path includes deps)
=> Include same files in PLT as rebar2

src/rebar_hooks.erl
Allow hooks to know what is current build dir
=> Export env var REBAR_BUILD_DIR in hooks, as rebar_dir:base_dir/1

src/rebar_core.erl
Fix for https://github.com/rebar/rebar3/issues/514
I can't think of a way to give a more useful error message without a lot of "maybe"s in it...
=> print nice error message if do is undef for provider

src/rebar_prv_common_test.erl
when running `ct` tests
fixes #513
=> ensure all `src_dirs` and `extra_src_dirs` are handled properly

src/rebar.app.src, src/rebar3.erl, src/rebar_dir.erl, src/rebar_plugins.erl, src/rebar_prv_as.erl, src/rebar_prv_install_deps.erl, src/rebar_prv_plugins.erl, src/rebar_prv_plugins_upgrade.erl, src/rebar_state.erl, test/rebar_compile_SUITE.erl, test/rebar_plugins_SUITE.erl
Adds a provider for listing the current set of plugins for a project and for upgrading a plugin.
Important bug fix that I am not 100% about is https://github.com/rebar/rebar3/compare/rebar:master...tsloughter:plugins_provider?expand=1#diff-5bbc70cb457999c3dabeeac51e71f8a6R372
=> plugins provider

src/rebar_prv_packages.erl
Prints only Erlang (rebar or make as build tool) packages in sorted order.
=> print sorted list of packages

src/rebar_state.erl
Fixes https://github.com/rebar/rebar3/issues/539
=> error message for bad profile config, fixes #539

src/rebar_prv_plugins_upgrade.erl
Fixes https://github.com/rebar/rebar3/issues/542
=> error message when no plugin is passed to plugins upgrade and global upgrade

bootstrap, rebar.config, rebar.lock, src/rebar.app.src, src/rebar_prv_relup.erl, src/rebar_prv_tar.erl
=> Upgrade relx and add relup provider

src/rebar_prv_common_test.erl
to itself so a selective receive can be used to retrieve it
fixes #547
=> add an (almost) unique reference to message sent from the ct provider

src/rebar_prv_install_deps.erl
Fixes https://github.com/rebar/rebar3/issues/549
=> expand plugins for profile after applying profiles

src/rebar_agent.erl
The old run didn't necessarily apply all profiles well, and would only
reload modules in the app file. However, since adding extra_src_dirs,
modules can be compiled without ending up in the app file; this lets
the rebar3 shell agent handle that case.
Fixes https://github.com/rebar/rebar3/pull/570
=> Apply profiles properly & load all paths

src/rebar_utils.erl
See: https://github.com/rebar/rebar3/issues/589
=> always close port when done with it. fixes #589

src/rebar_erlc_compiler.erl, src/rebar_prv_compile.erl, test/rebar_compile_SUITE.erl
This came up as @Licenser was working on sniffle.
=> ensure necessary directories exist to compile mibs files

src/rebar_core.erl
The wide-cast catching of undef errors would make it so any provider
calling an undefined function would be reported as a missing 'do' for
the provider.
This patch inspects the stacktrace to know if `Provider:do/1` is indeed
the missing callback, and reports the rest properly.
=> Fix reporting of error:undef exceptions

.travis.yml
Should pass when travis adds support for 18.0
=> update travis to test on 18 and 17.5

src/rebar_digraph.erl
Fixes https://github.com/rebar/rebar3/issues/601
=> bug fix: was using outer LevelsAcc variable in inner foldl

.gitignore, pr2relnotes.py
pr2relnotes takes merged PRs from the git log and generates
formatted release notes including links to the PRs themselves
=> Add pr2relnotes tool to generate release notes

src/rebar_prv_install_deps.erl, test/rebar_compile_SUITE.erl, test/rebar_test_utils.erl
Fix for https://github.com/rebar/rebar3/issues/620
Only use `{deps, default}` of a dep.
=> do not install profile deps of deps

src/rebar3.erl
Fix for https://github.com/rebar/rebar3/issues/614
=> handle global config file that can't be read

src/rebar_prv_edoc.erl
Fix for https://github.com/rebar/rebar3/issues/629
=> run edoc provider in docs provider

src/rebar_utils.erl
Fixes https://github.com/rebar/rebar3/issues/631
=> support atom for branch names like rebar2

THANKS, src/rebar_app_discover.erl, src/rebar_prv_install_deps.erl, src/rebar_utils.erl, test/rebar_utils_SUITE.erl
Updated @derek121 branch and added him to the THANKS document.
=> Validate otp version

src/rebar_prv_plugins_upgrade.erl, src/rebar_prv_upgrade.erl, src/rebar_utils.erl
Fixes https://github.com/rebar/rebar3/issues/643
=> fix upgrade of newly added pkg dep from scm locked dep

priv/templates/plugin.template
Fix for https://github.com/rebar/rebar3/issues/657
=> fix plugin provider source name

src/rebar_app_discover.erl, src/rebar_app_info.erl, src/rebar_app_utils.erl, src/rebar_config.erl, src/rebar_otp_app.erl
Fix for https://github.com/rebar/rebar3/issues/653
=> include app.src.script in app discover

src/rebar_prv_clean.erl, test/rebar_compile_SUITE.erl
Fixes https://github.com/rebar/rebar3/issues/663
It broke when we merged https://github.com/rebar/rebar3/pull/619
=> fix find of deps for clean all

src/rebar_prv_packages.erl
Fixes https://github.com/rebar/rebar3/issues/648
=> sort versions of packages in `rebar3 pkgs` output

priv/shell-completion/fish/rebar3.fish
=> basic 🐟 completions

src/rebar_prv_upgrade.erl, src/rebar_state.erl
May be related to https://github.com/rebar/rebar3/issues/646
=> only use upgrade on default deps

src/rebar_prv_lock.erl, src/rebar_prv_upgrade.erl, src/rebar_utils.erl, test/rebar_upgrade_SUITE.erl
Fix for https://github.com/rebar/rebar3/issues/646
=> upgrade depends on the lock provider and lock prv sets state

src/rebar3.erl, src/rebar_agent.erl, src/rebar_api.erl, src/rebar_app_discover.erl, src/rebar_core.erl, src/rebar_prv_deps.erl, src/rebar_prv_install_deps.erl, src/rebar_prv_packages.erl, src/rebar_prv_shell.erl, src/rebar_prv_update.erl, src/rebar_prv_xref.erl, src/rebar_state.erl, src/rebar_utils.erl
I still need to figure out 6 'no local return' warnings. Then I'll be updating the specs in install_deps to be tighter.
=> fix dialyzer warnings, except 'no local return' warnings

rebar.lock, src/rebar_digraph.erl, src/rebar_prv_deps.erl, src/rebar_prv_install_deps.erl, src/rebar_prv_lock.erl, test/rebar_deps_SUITE.erl, test/rebar_install_deps_SUITE.erl
Not ready, I want to do some refactoring and more testing -- pretty sure some niceties were broken like with not printing out needless "skipping" messages. But should fix https://github.com/rebar/rebar3/issues/697 and some other stuff.
=> install package deps in same level/profile order as src deps

src/rebar_app_discover.erl, src/rebar_digraph.erl, src/rebar_prv_common_test.erl, src/rebar_prv_deps_tree.erl, src/rebar_prv_install_deps.erl, src/rebar_prv_upgrade.erl, test/mock_git_resource.erl, test/rebar_compile_SUITE.erl, test/rebar_deps_SUITE.erl, test/rebar_install_deps_SUITE.erl, test/rebar_plugins_SUITE.erl, test/rebar_profiles_SUITE.erl, test/rebar_test_utils.erl, test/rebar_upgrade_SUITE.erl
This includes @ferd 's tests from https://github.com/rebar/rebar3/pull/717 and fixes the issues related to them.
=> Ferd add mixed deps tests

src/rebar_git_resource.erl
Changes parse_git url function to use Using RFC3986 standard to validate
git uri instead of matching strings in function head. Also converts scp
style syntax to ssh uri for parsing. See:
https://git-scm.com/book/en/v1/Git-on-the-Server-The-Protocols
=> Modify parse_git_url to be more generic

src/rebar_erlc_compiler.erl
Some ets tables still leaking if compilation failed. This commit fix that problem. There is still leakage of `hex_registry` table.
=> fix leaking ets tables when compilation failed

src/rebar_digraph.erl, src/rebar_prv_install_deps.erl
Fixes https://github.com/rebar/rebar3/issues/698
=> properly update locks for deps and ignore skip messages for locks

src/rebar_packages.erl, src/rebar_prv_install_deps.erl, src/rebar_prv_packages.erl, src/rebar_state.erl, test/mock_pkg_resource.erl, test/rebar_pkg_SUITE.erl, test/rebar_test_utils.erl
=> fix leaking hex_registry table

src/rebar_relx.erl, test/rebar_release_SUITE.erl
Fix for https://github.com/rebar/rebar3/issues/709
=> do not override user cli supplied outputdir for relx

src/rebar_erlc_compiler.erl
This fixes an issue where while during the run the digraph would have an edge removed for a removed source file this update what not written to disk.
Fixes https://github.com/rebar/rebar3/issues/714
=> update erlcinfo on disk if source file removed

rebar.config, rebar.lock
The relx upgrade has a fix for https://github.com/rebar/rebar3/issues/750
=> upgrade relx and bbmustache

src/rebar_app_discover.erl, src/rebar_app_info.erl, src/rebar_app_utils.erl, src/rebar_config.erl, src/rebar_prv_install_deps.erl, src/rebar_prv_plugins_upgrade.erl, src/rebar_state.erl, test/rebar_pkg_alias_SUITE.erl, test/rebar_test_utils.erl
Fixes https://github.com/rebar/rebar3/issues/721 by supporting deps of the form:
```
{uuid, {pkg, uuid_erl}}  
{uuid, "1.5.0", {pkg, uuid_erl}}
```
=> support pkg attribute on dep to declare package name different from app name

src/rebar_file_utils.erl, src/rebar_prv_update.erl
Fix for https://github.com/rebar/rebar3/issues/754.
@ferd should get this merged in before the next beta is cut.
=> remove replacement of home dir with ~ in update output

src/rebar3.erl, src/rebar_packages.erl, src/rebar_prv_packages.erl, test/mock_pkg_resource.erl
Fixes https://github.com/rebar/rebar3/issues/763
=> only load packages when needed

src/rebar3.erl, src/rebar_packages.erl, src/rebar_prv_packages.erl, test/mock_pkg_resource.erl
Reverts rebar/rebar3#771
Somehow kept failing on R15Bxx. We can rebase/fix/resubmit I guess.
=> Revert "only load packages when needed"

src/rebar3.erl, src/rebar_packages.erl, src/rebar_prv_packages.erl, test/mock_pkg_resource.erl
Reverts rebar/rebar3#773
Visibly travis is to blame. Keep this thing merged.
=> Revert "Revert "only load packages when needed""

src/rebar_config.erl
Fixes compiling yaws, which has an .app.src.script file
=> Terms is already a list

.travis.yml
Updating per https://github.com/travis-ci/travis-ci/issues/4776#issuecomment-140432869 to see if it works.
=> update travis for s3

src/rebar_prv_dialyzer.erl
Fixed problem that fancy messages got written to disk not boring ones.
=> Write original messages not fancy ones to disk

src/rebar_config.erl
```erlang
%% file:consult/1 always returns the terms as a list, however file:script
%% can (and will) return any kind of term(), to make consult_and_eval
%% work the same way as eval we ensure that when no list is returned we
%% convert it in a list.
```
=> Fix consult_and_eval/2 to behave like consult

src/rebar_core.erl
Requested in https://github.com/rebar/rebar3/issues/803
=> add DEBUG statement of the command sequence that'll be run

src/rebar3.erl, src/rebar_app_info.erl, src/rebar_dialyzer_format.erl, src/rebar_prv_local_install.erl
Mostly just typespec updates for changes made in other PRs.
=> fix dialyzer warnings

src/rebar_git_resource.erl
It would already return 0.0.0 if it failed further through the git commands, now it will even on the first attempt to run git if it fails.
=> if not in a git repo but have 'git' as vsn, fallback to 0.0.0

src/rebar_relx.erl
=> Allow non-default checkouts dir for relx

src/rebar_prv_update.erl
Fix for https://github.com/rebar/rebar3/issues/876
=> return more useful error message (failed to download) when pkg http req fails

src/rebar_prv_dialyzer.erl, test/rebar_dialyzer_SUITE.erl
=> Rebuild PLT when beams no longer exist

rebar.config, rebar.lock
Fixes https://github.com/rebar/rebar3/issues/910
=> upgrade relx to 3.8.0, fixes bug in upgrade_install escript

src/rebar_prv_shell.erl
Application masters are booted at the root of apps, and take over the
group leader role to redirect IO. To cut the chain short and properly
have their role inherited, they are their own leader, and keep a
reference to the old leader in their internal state, which we cannot
change.
This is done so process ownership to a given application can be
established, and allows to properly clean up resources outside the
supervision tree when an app is shut down.
This patch goes around and finds all processes whose group leaders are
application masters older than the new `user` process booted by the
shell providers, and swaps them with that new `user`. This lets the
application masters survive, and fixes the blocking IO issue
(resolving issue #899)
This may mean an incomplete clean up is down on …
=> Fix IO locking up in shell apps

src/rebar_prv_update.erl
This patch makes it so the registry only has a package and list of its versions if it had the right build tool support by checking that one of the versions of the package was already added when buildtool was checked.
=> only add package list of versions to registry if it has the right build tool support

src/rebar_prv_new.erl, test/rebar_new_SUITE.erl
The checking of flags and the parsing of arguments is separated up.
Fixes #929
=> Handle force flags in leading position

src/rebar_prv_cover.erl
Will show/write to file total code coverage in the same manner rebar2 used to.
=> Add support for total code coverage

src/rebar_dir.erl, test/rebar_dir_SUITE.erl
Same as  #974 but with tests.
Tests fail without #974's patches, pass with it.
=> Fix wrong relative path resolution

rebar.config, rebar.lock
Tested locally to ensure app was launched in embedded mode for console.
=> Upgrade relx to v3.11.0

rebar.config, rebar.lock
This fixes a typo that could cause failure in some test runs.
=> Bump cth_readable to 1.1.1

src/rebar_relx.erl, test/rebar_release_SUITE.erl
Fix for https://github.com/rebar/rebar3/issues/954 
I decided this belonged in rebar3 and not relx, but we can still discuss that if someone thinks otherwise. Basically relx only supports a single entry for `overlay` so to support profiles that add to an overlay they must be merged together.
=> merge overlay entries into a single {overlay, list()} for relx

rebar.config, rebar.lock
This includes the upgrade to relx that replaces relx's sorting of apps with just systools sorting that keeps user defined order when it can.
=> upgrade bbmustache and relx

src/rebar_prv_eunit.erl
=> when using the `--file' argument to `eunit' paths were being converted

src/rebar_plugins.erl, test/rebar_plugins_SUITE.erl
Fix for https://github.com/rebar/rebar3/issues/1042
=> don't lose overrides in an app when installing plugins it uses

src/rebar_pkg_resource.erl, src/rebar_prv_update.erl, src/rebar_utils.erl
Fix for https://github.com/rebar/rebar3/issues/1038
=> add user-agent to http request headers

src/rebar_prv_shell.erl
=> Support --setcookie option

THANKS
=> Add me to THANKS for suffering through Tristan's code

src/rebar_packages.erl
Fixes https://github.com/rebar/rebar3/issues/1086
=> fix auto-registry update to work even when not a locked pkg-vsn

README.md, src/rebar.app.src, src/rebar3.erl, src/rebar_hooks.erl, src/rebar_prv_state.erl, src/rebar_state.erl
The provider is used for debugging to help displaying current rebar's state.
Usage:
```
rebar3 state
```
=> Add a state display provider

rebar.config, rebar.lock
=> bump certifi to 0.4.0

src/rebar3.erl, test/rebar_profiles_SUITE.erl
=> define the 'EUNIT' macro in the test profile

src/rebar_log.erl, src/rebar_relx.erl
Resolves https://github.com/rebar/rebar3/issues/1109
=> pass loglevel used in rebar3 to relx

src/rebar_prv_packages.erl
Unsure if this should be a final supported format or if we should
support other ways to match instead.
This is a demo to solve the issue hilighted in
https://github.com/erlang/rebar3/pull/1072
New output:
```
$ rebar3 pkgs recon
recon:
Versions: 2.2.0, 2.2.1
```
=> Allow 'rebar3 pkgs <app>' to return only that app

src/rebar_prv_shell.erl
The sys.config loading in the shell command did not implement recursion
and thus processed the file different from a `erl -config cfg/path`.
=> Recursively load configurations in shell

src/rebar_prv_edoc.erl
Allows `pre_hooks` and `post_hooks` to fire for the `edoc` provider.
I was looking for this so that I could run the normal edoc job, but overwrite the `doc/overview-summary.html` file with my own generated HTML.
=> Add a provider hook for edoc

src/rebar_prv_xref.erl
Re: Issue #572  
* Add support for xref_ignores in the rebar.config
Useful to ignore warnings in auto-generated module (e.g. yecc parser).
e.g.
```
{xref_ignores, [{swirl_ql_parser, return_error, 2}]}.
```
=> Add support for xref_ignores

src/rebar_git_resource.erl
fix issue #1185 git working directory issues due to command line options in Windows
=> #1185 fix windows git working directory

test/rebar_ct_SUITE.erl
don't bother checking the profile in the path to the data dir
=> adjust `data_dir_correct` test in ct suite

bootstrap
=> Expand os ENV proxy support to bootstrap script

src/rebar_erlc_compiler.erl, test/rebar_compile_SUITE.erl
partially addresses #1184 by ensuring files are always recompiled if they may be out of date
=> REBAR-1184 always recompile if `ERL_COMPILER_OPTIONS` env var is set

src/rebar_prv_dialyzer.erl
No longer do the work around introduced in #900 for fixed versions of dialyzer. This fix is for 18.3+ so won't be tested on CI at the moment. Could we add a newer version of OTP to travis? Perhaps 19.0?
On my local machine this change reduces the dialyzer test suite duration by 15% for new versions of dialyzer. For real world examples this will improve performance by a larger margin when a dep is removed or a dep update removes a module because the PLT won't be rebuilt from the base PLT, just a small change made to the PLT. However if the OTP release changes directory for the same full version of OTP (e.g. 19.0.1) it will be slower because all the OTP modules will be removed and then re-added.
=> Avoid PLT rebuild when files deleted on new dialyzer

.github/ISSUE_TEMPLATE.md
As proposed in https://github.com/erlang/rebar3/issues/1263
=> Add issue template to help people fill tickets

priv/templates/gitignore
This family of IDE with Erlang plugin is already quite popular.
=> Ignore IntelliJ IDEA files

rebar.config.sample, src/rebar_prv_cover.erl, test/rebar_cover_SUITE.erl
This is an expansion and replacement of https://github.com/erlang/rebar3/pull/1237 -- it adds a test and re-formats the code a bit to be more similar to the old one and avoid deep nesting.
=> Cover excl mods

rebar.config, rebar.lock
It will contain some new features and some bug fixes.
Please refer to [Release Notes](https://github.com/soranoba/bbmustache/releases)
And resolved the some issue !!
- https://github.com/erlang/rebar3/issues/1323
- https://github.com/erlang/rebar3/issues/1264
=> update bbmustache 1.3.0

src/rebar_erlc_compiler.erl, test/rebar_compile_SUITE.erl
there's no way to detect which files actually rely on a parse transform
passed to the compiler via the options (as opposed to `-compile(..)`
so if any parse transforms are in modules that need recompiling just
recompile the world
fixes #1328
=> recompile all files when a parse transform given as an opt needs updating

src/rebar_prv_eunit.erl, test/rebar_eunit_SUITE.erl
{`eunit_test_regex`, Regex}` will use the supplied `Regex` instead of
the default to locate tests in test dirs. note this matches only the
filename, not the path. the regex is applied to all test dirs, recursively
fixes #1331
=> allow using an alternate regex to locate test modules during eunit runs

src/rebar_file_utils.erl, src/rebar_prv_common_test.erl, src/rebar_prv_shell.erl, src/rebar_utils.erl
See #1289 for the description of the problem.
=> Fix sys.config's handling in common_test and otherwise.

src/rebar_app_info.erl, src/rebar_config.erl, src/rebar_erlc_compiler.erl, src/rebar_prv_common_test.erl, src/rebar_prv_cover.erl, src/rebar_prv_deps.erl, src/rebar_prv_eunit.erl, src/rebar_prv_shell.erl, src/rebar_prv_update.erl, src/rebar_prv_xref.erl, src/rebar_state.erl
Some tricky changes in there but should be okay overall. Gets rid of all the warnings.
=> Fix rebar3 dialyzer warnings

rebar.config, rebar.lock
relx ~> 3.22.0
erlware_commons ~> 0.22.0
cf ~> 0.2.2
=> Upgrade relx, erlware_commons and cf

src/rebar_prv_install_deps.erl
=> Replace unprocessed ~n linebreaks

bootstrap, src/rebar3.erl, src/rebar_pkg_resource.erl, src/rebar_utils.erl, test/rebar_utils_SUITE.erl
fix for issue 1394: https://github.com/erlang/rebar3/issues/1394
=> 1394: fixed handling of proxy username and password

src/rebar_base_compiler.erl, src/rebar_erlc_compiler.erl, src/rebar_prv_eunit.erl, src/rebar_templater.erl
This should solve the issue in https://github.com/erlang/rebar3/issues/1402
=> Restrict regexp to match on files starting with '._'

src/rebar_git_resource.erl
For environments with git versions less than 1.8.0 the option --single-branch does not exist to the git clone command. That renders rebar3 useless in those environments. The remedy is to fallback to simpler commands if an earlier git versions is detected. In this case the git resource options `tag` and `branch` are affected and will fallback to the command `git clone $URL $DIR -b $TagOrBranch` if version >= 1.8.0 is not satisfied.
I'm happy to rework this code and feedback is encouraged.
=> Select git clone command by git version

src/r3.erl, src/rebar3.erl, src/rebar_agent.erl, src/rebar_api.erl, src/rebar_app_discover.erl, src/rebar_app_info.erl, src/rebar_app_utils.erl, src/rebar_base_compiler.erl, src/rebar_config.erl, src/rebar_core.erl, src/rebar_digraph.erl, src/rebar_dir.erl, src/rebar_dist_utils.erl, src/rebar_file_utils.erl, src/rebar_pkg_resource.erl, src/rebar_prv_install_deps.erl, src/rebar_utils.erl
Includes improvments and function documentation for all modules (in
alphabetical order) up to rebar_core, and may have included more in
other modules as I saw fit to dig and understand more of the internals.
Decided to stop there for now to put a time bound on this and to
avoid to big of a changeset that could conflict with PRs and whatnot.
Part of some work for me to familiarize myself with more parts of the
internals and hopefully make user contribution easier in the future.
=> Type specifications and edocs improvements

CONTRIBUTING.md, THANKS
- "suffi", I assume that is supposed to be "suffix".
- Never heard of "fir" before, but unless we are talking about evergreen trees, I'm pretty sure that means "fire".
- Also added myself to *THANKS*, since I didn't do it last time.
Cheers!
=> Fixed typos and grammar errors for CONTRIBUTING.md.

README.md
=> The stable URL is for stable releases since 3.0.0

src/rebar_prv_update.erl
fixes https://github.com/erlang/rebar3/issues/1465
=> Fix printing path with unicode names in prv_update

src/rebar_templater.erl
Did not really know how to automate the testing for this, did it by
hand.
Should fix #1468
=> Add support for global plugin-defined templates

src/rebar3.erl, src/rebar_config.erl
=> REBAR_CONFIG impacts file project root only

src/rebar_prv_plugins.erl, test/rebar_test_utils.erl
Eventually I'll get windows to work
=> More fixes for bad calls to find_apps

manpages/rebar3.1
=> Revert "List 'lock' command in man page"

.travis.yml
this adds an osx build to the travis config. i also updated the 19.x and 18.x versions we test against to the most current available
=> update travis.yml to test on osx

src/rebar_dist_utils.erl
We do it by calling os:cmd on a named shell so that the automated daemon
rules work for rebar3 as well.
=> Try to start epmd when distribution fails

src/rebar_prv_common_test.erl, test/rebar_ct_SUITE.erl
=> add compile_only option to ct provider

appveyor.yml
16.x is not available on chocolatey or i would have added that too
=> appveyor configuration to build on 15.3.1, 17.5, 18.3 and 19.2

src/rebar_file_utils.erl
The code for symlink handling failed whenever a win32 platform with no
symlink capability would be detected. This patch is provided by
William H from the support ticket at
http://www.rebar3.org/v3/discuss/598225c90365bb00144bc07f, which
adds detection of failures in non-NTFS scenarios on Win32, and then
copies files instead of bailing out.
The end result should be appropriate support for such a platform.
=> Support Windows with non-NTFS filesystems

src/rebar_erlc_compiler.erl, test/rebar_compile_SUITE.erl
Fix when app-less include files are introduced by erl_opts.
=> Recompile when include files change in non-default directories

src/rebar_prv_compile.erl, test/rebar_compile_SUITE.erl
The compiling of OTP applications is done by first topographically
sorting them according to their dependencies, deps-first. This allows
all compilation to take place in order. In the current code, the same
logic extends to top-level applications in an umbrella project.
Unfortunately, there are cases where this is not going to be true: when
an application has extra_src_dirs entries (or additional directories or
files) to conditionally compile under some profiles, it may start
depending on another top-level application dedicated to that profile for
include files.
However, such an app will never make it to production and neither will
the compilation artifacts that create the dependency. Under that
scenario, current rebar3 is unusable.
This patch makes it so that the compilation provider …
=> Fix include paths in profile multiapp edge case

test/rebar_compile_SUITE.erl
=> Fix broken tests

src/rebar_git_resource.erl
=> [Closes #1675] Disable color in git log command

src/rebar_prv_cover.erl, test/rebar_cover_SUITE.erl
Adds an option (`-m`, `--min_coverage`, or `{cover_opts, [{min_coverage,X}]}`) to the 'cover' command, where the value is an integer between 0 and 100.
If the total coverage during the analysis is below the value expected, the command will fail with output like:
===> Requiring 64% coverage to pass. Only 62% obtained
If the rate is high enough, the command silently passes as it currently does.
This feature allows to enforce code coverage standards in a project ifdesired.
=> Support minimal coverage validation in tests

src/rebar_app_discover.erl
It makes things worse than if it weren't there.
Fixes issue #1726
=> Remove noisy debug message

src/rebar_prv_shell.erl
This patch makes it so that whenever the rebar3 shell has a new
configuration for an application that is already running and would be
restarted (without risking the stability of the node or functionality of
rebar_agent), we stop and restart the app.
=> Reload apps running in shell with new config

priv/templates/app.template, priv/templates/app_rebar.config
People are starting to expect these niceties! It's also easier to drop
the config when you know it's there than add it when you don't know it
exists.
=> Auto-boot main app in OTP app project templates

src/rebar_env.erl
=> Create ERLANG_LIB_*_erl_interface environment variables only if erl_interface exists

rebar.config, rebar.lock
Contains important bug fix https://github.com/soranoba/bbmustache/issues/17
=> upgrade bbmustache to 1.5.0

bootstrap, rebar.config, rebar.lock
=> Revert "upgrade certifi to 2.3.1"

src/rebar_prv_local_install.erl
=> otp21 eperm fix for local install/upgrade, no need to set uid/gid

src/rebar_erlc_compiler.erl
=> fixed typo erl_first_files

src/rebar_base_compiler.erl
Turns output like this:
===> Compiling apps/c/src/c.erl failed
apps/c/src/c.erl:3: can't find include lib "parse_trans/include/codegen.hrl"
Into:
===> Compiling apps/c/src/c.erl failed
apps/c/src/c.erl:3: can't find include lib "parse_trans/include/codegen.hrl"; Make sure parse_trans is in your app file's 'applications' list
Which is likely going to help newcomers encountering issues.
Fixes #1846
=> Friendlier output on include_lib errors

src/rebar_app_utils.erl
=> Fix package upgrade (issue #1945)

src/rebar_prv_new.erl
=> Add hint for `rebar3 new help` on `rebar3 help new`

src/rebar_compiler_erl.erl
Fix for https://github.com/erlang/rebar3/issues/1913
=> search subdirectories as well for imports/transforms/behaviours

src/rebar_compiler_mib.erl, test/rebar_compile_SUITE.erl
mostly copy/paste from rebar_compiler_erl
fix #1968
=> implement mib_first_files support in rebar_compiler_mib

systest/all_SUITE_data/resource_plugins/rebar.config
prevents some failures when running
=> Fixing systest to use up to date plugin

src/rebar_prv_packages.erl
- removed deprecated maintainers field from config template in
rebar_prv_packages
=> Remove deprecated hex field maintainers

src/rebar_hex_repos.erl, test/rebar_pkg_repos_SUITE.erl
=> add repo_name to repoconfig used with hex_core to be compatible

src/rebar_git_resource.erl
Closes #1944 
May need a regression test
=> Use single vs escaped double quotes

src/rebar_prv_shell.erl
Starting with OTP-21.2.3, some output appears to be sent to the shell
while we're taking down the TTY, which ends up stalling the whole log
flow for the default handler. I don't have proof but suspect this is due
to the system logging going directly from the ERTS runtime to the
logger, which may be trigger when we kill the TTY driver.
This patch makes it so whenever we detect that logger is active, we save
the default config, disable the default logger, and only then we can
kill the TTY driver. Once the driver is started and all the group
leaders have been rewritten, the default logger is re-added.
This all takes place _before_ the logger configuration is updated as
part of booting apps, and the change should be fully backwards
compatible.
Fixes #2007
=> Unhang logger when swapping the TTY in shell

src/rebar_prv_install_deps.erl, test/rebar_upgrade_SUITE.erl
We currently have a problem in the handling of locks in the `upgrade
<app>` command when a transitive dependency switches supervision trees.
If we start with:
A
/ \
B1  C
|
D
|
E
And upgrade to:
A
/ \
B2  C
|   |
E   D
by calling `rebar3 upgrade b`, we would expect the ugprade command to do
so directly. However we are currently left with the following lock file:
A
/ \
B2  C
|
D
|
E
This is _not_ critical since on the next run, the lock file is fixed
automatically through an install-deps sequence. However, this is a
jarring state in which to leave a project.
The reason is that we proceed the following way to handle an upgrade:
1. pick the name of the chosen app, and unlock it if it's at the level 0
2. grab a list of all its current children (and their own) and unlock
them
3. do the same …
=> Fix handling of transient locks during upgrade

src/rebar_file_utils.erl, src/rebar_prv_shell.erl, src/rebar_string.erl, src/rebar_templater.erl
I'm not sure the approach is too great, but it seems to work alright.
Like everything else shell-related it's a bit of a hack and real hard to test right
=> Attempt at support sys_config_src in shell

src/rebar_prv_eunit.erl
The `rebar3 eunit` command prints a profile of the slowest tests at the end of each test run. The profile output can cause failure output to scroll out of view (especially on a laptop screen). I rarely look at the profile output, but I always look at the failure output, and often have to scroll.
The plugin doesn't print the profile anymore. You can pass `-p` or `--profile` if you want to see it.
Before with a single test failure:
```
$ rebar3 eunit -p | wc -l
65
```
After with a single test failure:
```
$ rebar3 eunit | wc -l
42
```
Most importantly, test failures are the only thing in the output by default.
=> rebar3 eunit: Hide slowest tests profile output by default

src/rebar_git_resource.erl, src/rebar_resource_v2.erl, src/rebar_utils.erl
Adds support for `{git, short}`, `{git, long}` and `{file, File}` (relative to the app's directory) for configuring the version of an application.
=> add support for git ref and file content as app version

rebar.config, rebar.lock
relx changelog: https://github.com/erlware/relx/releases/tag/v3.32.0
=> upgrade relx to 3.32.0

src/rebar_templater.erl
This splits out the ability to print a message after a template has completed from the ct-suite PR I'd opened.
=> add support for usage message after template is done

src/rebar_agent.erl
rebar3's shell allows people to set applications as blacklisted to
prevent them from being reloaded because that can cause crashes.
However, as part of its normal operations, rebar_paths unloads all
modules that are currently not "owned" by at least one process,
considering them safe to do so.
These two behaviours, put together, lead to an odd thing where some
modules are suddenly unloaded and not in path, and that can be
confusing.
This calls for a unification of both features. We could decide to be
pushing the complexity of rebar3's shell into rebar_path so it knows of
blacklists, but this would be a bad idea because rebar_agent already
owns all the damn hack.
So instead this fix adds an optional call within rebar_agent's
blacklisted applications handling that calls …
=> Gracious loading of unloaded but blacklisted mods

src/rebar_packages.erl
Without this fix when there's an invalid checksum in rebar.lock client doesn't know that package can't be downloaded because of it. In the following examples rebar3 tries to download package from local Hex repository, then from official hex.pm.
Output before the change:
```
$ rebar3 get-deps
===> Failed to update package from repo hexpm
===> Package not found in any repo: amqp_tools 1.3.57
```
After the change:
```
$ ~/git/rebar3/_build/prod/bin/rebar3 get-deps
===> Checksum mismatch for package amqp_tools-1.3.57 from repo local
===> Failed to update package amqp_tools from repo hexpm
===> Package not found in any repo: amqp_tools 1.3.57
```
=> Warn when there's mismatch between rebar.lock & original package checksum

src/rebar_state.erl
=> Fix custom compiler mods typespecs, add edoc

src/rebar_prv_plugins_upgrade.erl
We might want to do this a little different and certainly need to add a test but I wanted to open this as it is all I have time to do at the moment and fixes the issue.
=> keep resources in new state used in plugins upgrade

src/rebar3.erl, test/rebar_dir_SUITE.erl
=> support REBAR_BASE_DIR for setting the base_dir

src/cth_retry.erl
See http://erlang.org/doc/man/ct_hooks.html#Module:on_tc_fail-4
=> Fix case clause which used wrong element order

src/rebar_utils.erl
To avoid a conflict the Kernel's default handler have to be disabled
before the new default handler is added
{kernel,
[{logger,
[{handler, default, undefined}
]}
]},
{my_app,
[{logger,
[{handler, default, my_handler, #{}}
]}
]}
To support this behavior in shell it's necessary to process the
handler-default-undefined tuple.
It's not clear what to do with the simple handler (logger_simple_h)
however.  It's added at the start and removed if a default handler was
added.  Should it be added in reread_logger_config/1 if there's no
default handler?
=> Disable the default logger handler in shell if required

src/rebar_prv_dialyzer.erl, test/rebar_dialyzer_SUITE.erl
In some cases it's nice to have dialyzer statistics out of box without
any additional steps.
=> Add `--statistics` option to dialyzer command

test/rebar_hooks_SUITE.erl
I had misread the code in issue #2200 -- the per-app hooks are still
run, just not the umbrella-level hooks.
=> bare compiler hooks do work and this shows it.

src/rebar_prv_path.erl
This reverts commit f0c8c202afd5b733b7fa11044d06d163e5a39485.
=> Revert "wip: rework rebar_prv_path to use app info"

src/rebar_plugins.erl, src/rebar_prv_shell.erl
=> shell: provide error message when applications list is bad

src/rebar3.erl, src/rebar_compiler.erl, test/rebar_compile_SUITE.erl
This patch contains two behaviour changes and reasserts other behaviours
that now line things up with user and documentation expectations:
1. The src directories remain recursive. We turned it on by accident at
some point in the past and now people rely on it, so we're stuck with
it. However a new test ensures that the feature can be turned off
on-demand as documented on the website.
2. The test directories are no longer recursive by default. The fix is
done by properly fixing how rebar3.erl does its feature injection by
mandating the default value there.
I'm somewhat nervous that this change could negatively impact some
users and older compiler module versions, but if users stick to the
rebar_dir interface, everything should keep working transparently.
3. The test directories' …
=> Fix directory recursion in compiler

src/rebar_app_utils.erl, src/rebar_fetch.erl, src/rebar_git_subdir_resource.erl, test/rebar_test_utils.erl
=> require the app name as the last part of git_subdir path

src/rebar_git_resource.erl
A more useful error message for #2343
=> git lock: abort if version is not equal to or greater than 1.8.5

src/rebar_config.erl, test/rebar_deps_SUITE.erl
=> Fix lock file not being generated when no deps are present in the config

src/rebar_dialyzer_format.erl
=> Fix `dialyzer` warning output for option `unknown`

rebar.config.sample
As mentioned in https://github.com/erlang/rebar3/issues/2359.
=> Add `alias` to example `rebar.config.sample`

src/rebar_prv_plugins_upgrade.erl
Didn't handle tuple-based dep definitions right
=> Fixup plugin upgrade autoupdate

README.md, priv/shell-completion/fish/rebar3.fish, priv/shell-completion/zsh/_rebar3
Still waiting on input from https://github.com/erlang/rebar3/issues/2397#issuecomment-708653420 and https://github.com/erlang/rebar3/issues/2397#issuecomment-708654579.
=> Update references to changed API elements

.github/workflows/main.yml, rebar.config
=> Make sure dialyzer static analysis is performed at least once, in CI

.github/workflows/nightly.yml, .github/workflows/publish.yml
This includes a trigger on pull requests just to test it.
=> try using docker container to publish to nightly

src/rebar_dialyzer_format.erl
Following up on https://github.com/erlang/rebar3/pull/2351, and since OTP 24 will most surely include https://github.com/erlang/otp/pull/3018, I'm pull requesting to adapt to a future `dialyzer` output-related change. I don't know how to properly proceed here, but I've seen you merge OTP 24 readiness elements in the past, so assume this is OK.
The present implementation hides the column element returned by `dialyzer:run`, but I can re-add it if you feel it necessary.
=> Adapt to upcoming OTP 24 `dialyzer` output

src/rebar_relx.erl
If the parameters --system_libs and --include-erts from rebar3 tar or
release are passed, then they need to take into account when loading
relx configuration file.
This commits checkes if the parameters are passed. If yes, they will be
used to override any system_libs and/or include_erts.
Fixes 2496
=> Do not discard parameters --system_libs and --include-erts

src/rebar_otp_app.erl
This is a partial revert of commit 80671df
In commit 80671df, the app vsn setting after compile was
removed because it was believed that app vsn is set during app
discovery stage and hence no need to set again after compile.
This leads to an issue for elixir dependencies (by rebar_mix plugin)
which do not have version info during discovery.
In this commit, the `vsn` and `original_vsn` were provided
when validating modules as before commit 80671df, but only if
the fields were not set before.
=> Ensure app vsn in app_info

src/rebar_prv_compile.erl
=> Fix Incorrect State variable used in rebar_prv_compile

priv/templates/Makefile
Reported in https://github.com/erlang/rebar3/issues/2553
=> Fix CLI arg order in makefile template

src/rebar_prv_local_install.erl, src/rebar_prv_local_upgrade.erl
=> local upgrade: extract vsn of rebar3 from appfile of downloaded escript

src/rebar_prv_xref.erl, src/rebar_relx.erl
Supercede #2611 but with passing tests via merge/rebase.
=> rebar3 release to honour the ignore-xref attribute

src/rebar_compiler_erl.erl
Even if a parse transform hasn't changed, its presence in a project triggers a full recompile.
=> Prevent a parse transform in a project triggering a full rebuild

.github/workflows/main.yml, .github/workflows/nightly.yml, .github/workflows/publish.yml, .github/workflows/shelltests.yml, CONTRIBUTING.md, rebar.config.sample, src/rebar_git_resource.erl, test/rebar_deps_SUITE.erl, test/rebar_test_utils.erl
I'll switch the github setting after this is merged to `main`.
=> switch to main as default branch

rebar.config.sample
A minimal fix in the rebar.config sample.
=> Fix missing dot

apps/rebar/src/rebar_prv_dialyzer.erl, rebar.config.sample
Companion pr on rebar3.org: https://github.com/tsloughter/rebar3.org/pull/124
=> Add missing doc. for `incremental` on Dialyzer analysis

apps/rebar/priv/templates/app_rebar.config, apps/rebar/priv/templates/escript_rebar.config, apps/rebar/priv/templates/otp_app.app.src, apps/rebar/priv/templates/otp_lib.app.src, apps/rebar/priv/templates/provider.erl, apps/rebar/priv/templates/relx_rebar.config, apps/rebar/priv/templates/sup.erl
This PR standardizes templates indentation.
=> Standardize templates indentation
