- src/rebar_erlc_compiler.erl
pretty sure this was a typo/mistake as `erl_first_modules` isn't referenced anywhere else
> point compiler to the right config value for which files need to be compiled first

- src/rebar.app.src
- src/rebar_prv_common_test.erl
- src/rebar_prv_eunit.erl
- test/rebar_eunit_SUITE.erl
- test/rebar_test_utils.erl
providers for `eunit` and `ct` test handlers, plus a basic test for the `eunit` handler. test for `ct` is omitted because apparently common test does not enjoy it when you try to run common test inside common test
fixes #62
there's still a few issues with these (some things are supported that should probably be deprecated like `{common_test/eunit}_first_files` and `{common_test/eunit}_compile_opts` and there's no support for `cover` yet) but they are in reasonable shape for further development and can probably be merged
> test providers

- src/rebar_prv_common_test.erl
- src/rebar_prv_eunit.erl
for better `common_test` reporting
`eunit` changed for consistency
> when compiling `common_test` or `eunit` use the same tmp dir

- src/rebar_prv_install_deps.erl
Removes the warning message when encountering a dependency that has been seen before if it was in the lock file. We assume that the lock file has all correct values and thus no reason to warn about a version being skipped due to being overridden by a high level definition.
> no skip warning for seen dep that has locked version

- src/rebar_prv_common_test.erl
- src/rebar_prv_eunit.erl
@evanmcc noticed an issue with the lager transform and common tests. Turned out the `erl_opts` were getting dropped when setting up the `src_dirs`. 
Note in eunit I removed the `| Srcs]` because `src_dirs` is retrieved with `append_values` when used to compile later anyway, so that is duplicating the dirs if we keep `Opts`.
> don't lose erl_opts when compiling for tests

- rebar.config
Discussing how slow rebar3 was for behelit_ on irc I ended up asking him to try these args and the time for a hot compile run went from 3-4 seconds to 0.6 seconds. So I think it is important to get in.
I also had him remove erlydtl from the escript. That takes the size of the escript form 1.2M to 750K. So we may want to consider moving to a simpler templating tool. But maybe not as big of a deal with these emu arg changes.
> add emulator args to escript for faster load time

- src/rebar_app_discover.erl
- src/rebar_hooks.erl
- src/rebar_otp_app.erl
- src/rebar_prv_compile.erl
- src/rebar_prv_install_deps.erl
With this PR we'll no longer crash if a dep has a list of options in it, like: `{merl, ".*", {git...}, [raw]}`, but we do just ignore it for now. `merl` builds fine without being raw as far as I can tell. But needed a fix to hooks so the path isn't wrong when running on a dep and did some cleanup on validation and error messages in `rebar_otp_app`.
> Clean up and backwards compatability

- rebar.config
`-mode minimal` breaks stuffs. 
If interested just do `rebar3 shell` and trying `httpc`.
I can't find documentation and what `minimal` actually does (or doesn't) do.
> no more mode minimal

- rebar.config
- src/rebar_app_discover.erl
- src/rebar_app_info.erl
- src/rebar_core.erl
- src/rebar_prv_erlydtl_compiler.erl
- src/rebar_state.erl
- test/rebar_hooks_SUITE.erl
- test/rebar_test_utils.erl
Example:
```
{provider_hooks, [{post, [{compile, {erlydtl, compile}}]}]}.
```
Looked at adding tests... Maybe I can just do something as simple as a `clean` as a post hook on `compile` and verify that the apps no longer show up as built.
> support for provider_hooks in config

- README.md
- THANKS
- src/rebar.app.src
- src/rebar_prv_xref.erl
- test/rebar_xref_SUITE.erl
* Add a provider for the xref tool for running cross reference
analysis on a project. Most of the code has been ported directly
from the rebar2 rebar_xref module with some modification and cleanup
to support testing.
* Port over the eunit test suite from rebar2, but convert it to
common_test. The testing is the same, but now the
erlang term output is examined to determine if the test run is successful
instead of scanning the console output for the expected strings.
> Add xref provider for cross reference analysis

- src/rebar_prv_xref.erl
Add xref support for multi-app projects. Instead of only adding the top-level ebin directory to the xref server use `rebar_state:project_apps/1` to enumerate the applications for the project and add the ebin directory for each one.
This corrects an issue with #127 that added xref support.
> Add xref support for multi-app projects

- src/rebar_fetch.erl
- test/mock_pkg_resource.erl
Fix a bug where packages are not added to the code path after installation. Dependent applications that build from source are not affected by this issue since the `build_apps` function in `rebar_prv_compiler` takes care of the code path changes for them. It is only the precompiled packages that suffer from this issue.
A good example of the problem is trying to use the `lager` package with an application with source files that requires the lager parse_transform. The build fails the first time with an error similar to this:
```
/home/kelly/repos/myproject/src/myapp_app.erl:none: undefined parse transform 'lager_transform'
Makefile:12: recipe for target 'compile' failed
make: *** [compile] Error 1
```
Subsequent build attempts are successful because the package is already installed, but the …
> Add packages to code path after installation

- src/rebar_app_utils.erl
I tried to use rebar3 on a repo with a rebar.config, but it wasn't OTP compliant (i.e. didn't have a .app or app.src file). Without the app file, I received an error. This pull request returns an error during app validation if the app file doesn't exist.
Error received without the fix below:
```
===> Uncaught error: {'EXIT',
{badarg,
[{erlang,length,[undefined],[]},
{lists,suffix,2,
[{file,"lists.erl"},{line,203}]},
{rebar_app_utils,consult_app_file,1,
[{file,"src/rebar_app_utils.erl"},{line,155}]},
{rebar_app_utils,load_app_file,2,
[{file,"src/rebar_app_utils.erl"},{line,134}]},
{rebar_otp_app,validate_app,2,
[{file,"src/rebar_otp_app.erl"},{line,85}]},
{rebar_prv_compile,build,2,
[{file,"src/rebar_prv_compile.erl"},
{line,88}]},
{rebar_prv_compile,'-build_apps/2-fun-0-',2, …
```
> Validate .app File Presence

- src/rebar_prv_dialyzer.erl
Currently `rebar3 dialyzer` is broken on OTP releases prior to (but not including) R16B02. See https://travis-ci.org/rebar/rebar3/jobs/49952886 for failing test cases.
erts.app was introduced in R16B02 (https://github.com/erlang/otp/commit/31b20cac498b98d40ed2bb15bb5259cb3c33a422) so read all beam files from the erts ebin directory if .app file does not exist.
> Fix dialyzer erts file lookup for releases prior to R16B02

- src/rebar_prv_dialyzer.erl
Addresses #102.
The implementation differs slightly from discussed https://github.com/rebar/rebar3/issues/102#issuecomment-70373199. If updating the PLT produces warnings the failure occurs after success typing analysis instead of before. The reasons for this is that a repeated run will not generate PLT warnings because the PLT is up to date and I felt this would cause confusion.
> Dialyzer fails if any warnings

- src/rebar_prv_do.erl
- src/rebar_utils.erl
- test/rebar_utils_SUITE.erl
this was for the `cover` meta command but the tests are useful even tho that approach is possibly not going to be used
> factor out task/args parsing from `do` for use in other meta commands

- src/rebar_prv_install_deps.erl
- src/rebar_prv_lock.erl
- src/rebar_prv_upgrade.erl
- src/rebar_state.erl
- test/mock_git_resource.erl
- test/rebar_deps_SUITE.erl
- test/rebar_test_utils.erl
- test/rebar_upgrade_SUITE.erl
I wanted to make this one visible while I work on it a bit, and open for comments.
Currently the mechanism I tried was to:
- Only allow to upgrade a top-level dependency. There's no reason (or good way) to properly upgrade a transitive dependency in a repeatable manner.
- Just fetch dependencies as if the dependencies were not locked (i.e. reuse the topological algorithm we use for deps)
- Do it via unlocking and re-running the installation of deps.
So the trick I tried for this one (and added a good bunch of tests for) was to unlock the top-level dep, and then all deps below it, then re-run the code. This works for trivial cases, but fails for more complex ones where the dependencies that change are several layers deep or in different subtrees.
I'll have to figure out a different …
> Upgrade procedure, from scratch (WIP)

- THANKS
- src/rebar_erlc_compiler.erl
Match erl_first_files properly against all files needing
compilation and make sure the order of erl_first_files as specified in
rebar.config is preserved (rebar/rebar#445)
> Fix #140 and preserve erl_first_files order

- src/rebar.app.src
- src/rebar3.erl
- src/rebar_prv_help.erl
- src/rebar_prv_wtf.erl
Tests missing.
Current output:
```
→ ./rebar3 wtf "do ct, eunit --someswitch"
Rebar3 wtf report
version 3.0.0
generated at 2015-02-12T18:05:50+00:00
=================
Please submit this along with your issue at https://github.com/rebar/rebar3/issues (and feel free to edit out private information, if any)
-----------------
Task: do
Entered as:
do ct, eunit --someswitch
-----------------
Operating System: x86_64-apple-darwin12.5.0
ERTS: Erlang/OTP 17 [erts-6.3] [source] [64-bit] [smp:4:4] [async-threads:0] [hipe] [kernel-poll:false]
Root Directory: /Users/ferd/.kerl/builds/17.4/release_17.4
Library directory: /Users/ferd/.kerl/builds/17.4/release_17.4/lib
-----------------
Loaded Applications:
[{inets,"INETS  CXC 138 49","5.10.4"},
{ssl,"Erlang/OTP SSL application","5.3.8"}, …
```
> Initial WTF provider implementation

- src/rebar_prv_dialyzer.erl
Dialyzer can return callgraph warnings (warnings where calls will always fails as the function is not exported from a module in the PLT) even when `{get_warnings, false}`. Fixes an issue discussed with @tsloughter on IRC.
I have sneaked in a typo fix in a second commit too ;).
> Fix {dialyzer_plt_warnings, false}

- src/rebar_prv_dialyzer.erl
Now that we fail on warnings it is not convenient for everyone to handle unmatched_returns and underspecs warnings. Extra default warnings are removed to match dialyzer's behaviour.
This will conflict with #152 but is simple to rectify.
> Dialyzer: Remove extra default warnings

- src/rebar_prv_deps.erl
- test/rebar_deps_SUITE.erl
- test/rebar_install_deps_SUITE.erl
Gives output such as:
```
$ rebar3 as test deps
ranch (locked package 1.0.0)
uuid (locked git source)
recon (locked git source)
peeranha (locked git source)
file_monitor (locked git source)
bootstrap (locked git source)
-- test --
meck* (git source)
```
And does handle fetched/non-fetched deps, locks, etc. Only package versions are displayed. Git sources are supported. Other sources are unknown and the whole `{Type, Ref}` tuple is returned.
The `*` asterisk denotes the app needs to be fetched or upgraded.
Only top-level deps are displayed.
> Initial `deps` command

- src/rebar_erlc_compiler.erl
- test/rebar_compile_SUITE.erl
the `needs_update` function in `rebar_erlc_compiler` only checks if the source (plus includes) has been updated since last compile but may also need recompiling if options passed to the compiler have changed
> check already compiled modules compile arguments against current compile arguments

- src/rebar_erlc_compiler.erl
the `needs_update/4` function loads old modules to check to see if they need to be recompiled. subsequently, the file is not reloaded even if it's recompiled. this means potential problems with tasks run after `compile`
> purge mods loaded during check to see if they need to be recompiled

- src/rebar_prv_common_test.erl
the process where ct is performed
> fix error where an exception in ct could hang rebar by monitoring

- src/rebar3.erl
- src/rebar_config.erl
- test/rebar_deps_SUITE.erl
Fix for https://github.com/rebar/rebar3/issues/150
Now `rebar3 compile` will discover newly added deps in `rebar.config`
> check for newly added deps in the config file that aren't level 0 in lock

- doc/templates.md
- src/rebar.hrl
- src/rebar3.erl
- src/rebar_dir.erl
- src/rebar_erlc_compiler.erl
- src/rebar_packages.erl
- src/rebar_prv_dialyzer.erl
- src/rebar_prv_update.erl
- src/rebar_templater.erl
- test/rebar_new_SUITE.erl
- test/rebar_upgrade_SUITE.erl
Moves the rebar3 config (including templates and plugins) to `~/.config/rebar3` and the package cache to `~/.cache/rebar3`
fixes #122
> follow xdg standard. fixes #122

- src/rebar_app_discover.erl
- src/rebar_app_info.erl
- src/rebar_app_utils.erl
- src/rebar_config.erl
- src/rebar_erlc_compiler.erl
- src/rebar_otp_app.erl
- src/rebar_prv_install_deps.erl
- src/rebar_utils.erl
Just some cleanup of duplicate code for app validation and checking if an app exists under a directory.
And removes some unnecessary "optimizations" from rebar2 like storing the app file in the State and storing the calculated version in some vsn cache in the state.
> consolidate app validation and exist checks

- src/rebar_hooks.erl
- src/rebar_utils.erl
Useful especially since we are using Makefiles from hooks for c_src and get no output on error without this change.
> output hook stdout and don't add extra newline

- src/rebar_prv_deps.erl
The 'element(1, ..)' guard would always fail and cause crashes.
> Fix crash on non-git source deps in deps provider

- src/rebar_prv_do.erl
so `rebar do foo, bar, baz` has the same outcome as `rebar3 foo && rebar3 bar && rebar3 baz`
fixes #191
> reset state between tasks run with `do`

- src/rebar_otp_app.erl
- src/rebar_prv_common_test.erl
- src/rebar_prv_eunit.erl
- src/rebar_state.erl
- test/rebar_profiles_SUITE.erl
changes in this pr:
* tests (src in `/test`) are now compiled to the appropriate app's `ebin` dir (but are filtered and excluded from being included in the app file)
* bare tests (those that don't belong to an application) are compiled to `_build/PROFILE/ebin`. i am not sure this is the best place for them and am open to suggestions for where they should be placed
* added `add_to_profile/3` function to `rebar_state` for modifying profiles from within rebar
* renamed the logdir for ct tests from `logs` to `_logs` to better match other meta directories (it could also be renamed `_ct` probably)
this pr supersedes #190 so it can now be closed if no one objects
> ct and eunit for builds

- src/rebar_prv_dialyzer.erl
Fixes #148.
This uses an undocumented option (`{check_plt, false}`) to avoid the bug in dialyzer.erl. The option is available since at least R13B03 and if it was documented we would want to use it regardless of the bug[1]. I will do a PR to OTP to document this option (it is documented on the command line interface) and fix the actual bug in dialyzer.erl too.
[1] We check the plt explicitly with `{analysis_type, check_plt}` and currently triple check the PLT. Adding this option is a significant speed boost, especially on small applications with many dependencies.
> Do not automatically check plt

- src/rebar_prv_eunit.erl
this fixes an issue similar to #211 but is still currently broken due to #212. i think it should still be merged however to aid in fixing #212
> preserve state when compiling directories with a `rebar.config`

- src/rebar_prv_dialyzer.erl
This is an attempt to make the provider less of a black box, so that dependency issues (i.e. not listing a dependency in applications) and the actual dialyzer commands can be seen using `DEBUG=1`.
> Add debug statements to dialyzer provider

- src/rebar_erlc_compiler.erl
- src/rebar_otp_app.erl
- test/rebar_compile_SUITE.erl
- test/rebar_eunit_SUITE.erl
fixes #216 and #220
i have a test case for this, but see #224
> switch from loading modules to read compile info to using `beam_lib`

- src/rebar_prv_dialyzer.erl
* Moves the PLT from `./_build/` to `./_build/profile/` to respect profiles.
* Uses rebar_utils:opt_release() to name PLT files
* Use shorter name for default PLT
The current PLT name format `.rebar3.otp-{OTP_RELEASE}.plt` was chosen when project PLTs were placed in `./` (before `./_build`, `~/.config/.rebar3/` and profiles). Given that moving the project PLT to the profile directory will cause projects to rebuild their PLT's I thought it a convenience to change to a minimal naming scheme at the same moment.
> Change PLT name and directory

- src/rebar_core.erl
- test/rebar_namespace_SUITE.erl
This adds some more convolution to command parsing, unfortunately, but
makes some cases clearer (`rebar3 as as as as` is no longer valid). It
unfortunately disallows using $REBAR_PROFILE along with `as` in a rebar
command.
Still need to rework $REBAR_PROFILE to work in there or something
> Fix namespace regressions

- src/rebar_erlc_compiler.erl
- src/rebar_prv_common_test.erl
- src/rebar_prv_compile.erl
- src/rebar_prv_eunit.erl
- test/rebar_compile_SUITE.erl
this gets correct compile paths included in module info which is relevant to some tools
> compile source from the symlinked directories under `_build`

- rebar.config
Slight speed up and I can't think of a use for smp in rebar3 at this time.
> disable smp in escript

- src/rebar_templater.erl
error before:
===> Uncaught error: {'EXIT',
{badarg,
[{io,format,
[<0.23.0>,
"\e[0;36m===> Skipping template ~p, due to presence of a custom template at ~s~n~n\e[0m",
["/home/mariano/.config/rebar3/templates/fn_app/fn_app.template"]],
[]},
{rebar_templater,prioritize_templates,2,
[{file,"src/rebar_templater.erl"},{line,330}]},
{rebar_templater,find_templates,1,
[{file,"src/rebar_templater.erl"},{line,274}]},
{rebar_templater,new,4,
[{file,"src/rebar_templater.erl"},{line,47}]},
{rebar_prv_new,do,1,
[{file,"src/rebar_prv_new.erl"},{line,44}]},
{rebar_core,do,2,
[{file,"src/rebar_core.erl"},{line,129}]},
{rebar3,main,1,
[{file,"src/rebar3.erl"},{line,46}]},
{escript,run,2,
[{file,"escript.erl"},{line,752}]}]}}
> fix debug format to avoid crash with custom template

- src/rebar_prv_dialyzer.erl
This will cause a complete base plt rebuild in new projects. Rebuilding can be skipped by manually copying any PLTs. Better now than later.
/cc @asabil
> Store base PLT in ~/.cache/rebar3/

- src/rebar3.erl
- src/rebar_core.erl
- src/rebar_prv_as.erl
Breaking up initial call to parse from the ones deep inside the provider
parsing to do smarter namespace detection, added 'as' the ability to
look into these also, and cleaned up the code a whole lot that would
depend on implicit assumptions.
A side-effect is that 'do' is now valid for all namespaces, although it
can be overriden.
> Fix #267, refactor as/do/namespace interactions

- src/rebar_app_discover.erl
- src/rebar_prv_install_deps.erl
- test/rebar_install_deps_SUITE.erl
- test/rebar_test_utils.erl
The deps are sorted and merged, but the merge function merges lists, not
elements. This yields deps that are duplicated and ran for multiple
times.
We first add proper sorts so the keymerge is guaranteed to be fine, and
then do a dedup run to get rid of duplicates if they happen to be.
This would yield warnings when none should happen, and would break
conflict errors because all runs would automatically fail on the first dep.
The option {deps_error_on_conflict, true} will make it so conflicts in
deps being fetched interrupts the operation rather than just display a
warning.
Defaults to `false'.
> Dep conflict as error

- src/rebar_prv_install_deps.erl
The list of deps returned from `update_src_deps` and `update_pkg_deps` is used to set the code path for building project apps. This change ensures all package deps apps are included in that list so the code path is updated properly.
> include all pkg deps in list of deps returned from update

- src/rebar_prv_release.erl
- src/rebar_state.erl
- test/rebar_profiles_SUITE.erl
- test/rebar_release_SUITE.erl
- test/rebar_test_utils.erl
Fixing #287, includes #289 tests from @kellymclaughlin 
This works by:
1. Implementing a stable umerge function that considers keys as comparing equal if they're values and tuples, but preserves the current duplication semantics (we also make sure that the 'newer' profile always takes precedence)
2. Reversing the list of argument passed on to relx so that it always uses them in the priority *we* judge important (I guess relx uses a fold of sort to turn their config in a dictionary, so by reversing the list we get the right dictionary)
This appears to fix the bug without need for additional special-casing of arguments.
> Fancy profile merge fun

- src/rebar.hrl
- src/rebar_app_info.erl
- src/rebar_dir.erl
- src/rebar_prv_install_deps.erl
- src/rebar_prv_lock.erl
- src/rebar_utils.erl
- test/mock_git_resource.erl
- test/mock_pkg_resource.erl
- test/rebar_compile_SUITE.erl
- test/rebar_test_utils.erl
Don't treat an app found in `_checkouts` like a project app but instead as a dep that is always "invalid" so that any changes are compiled each run.
> treat _checkouts as deps that are always compiled

- test/rebar_eunit_SUITE.erl
I came across an issue using the `test` profile to run the `eunit` command. This PR provides a failing test case for the issue. 
The `{d, 'TEST'}` tuple is duplicated in the final merged version of the `erl_opts` so an error is thrown. The problem seems to be that the profiles are applied twice when using `as`. Once by `rebar_prv_as` and then again when `rebar_core:process_command/2` is called from `rebar_prv_do` when the tasks are being processed. 
I tested adding a third parameter to `rebar_core:process_command` to indicate if profiles should be applied or not and then disabled profile application from `process_command` call in `rebar_prv_do`. That resolves the duplicate define issue, but probably not the right answer when the `do` command is in use. Maybe `rebar_prv_as` needs its own …
> Add test case to exercise the eunit provider using the test profile

- src/rebar_state.erl
- test/rebar_eunit_SUITE.erl
Much clearer semantics now. All lists are treated as proplists, meaning
we want to:
1) allow duplicates (providers have to avoid them if they must)
2) preserve order of elements that compare equal (`a == {a, val}`)
through a stable sort (so if `{a, b}` comes before `a`, we keep
`{a, b}` first in the list
3) In two lists of attributes requiring a merge, we always give the
'new' profile a priority to override the default one.
See #294
> Fix property merging

- src/rebar_prv_eunit.erl
- test/rebar_eunit_SUITE.erl
- test/rebar_profiles_SUITE.erl
- test/rebar_test_utils.erl
here's a refactoring of the eunit provider to allow for `--app` and `--suite` options to run only a subset of tests. there's also a vastly expanded test suite
> eunit refactor and test suite

- src/rebar_prv_new.erl
- Allow 'rebar3 help' to work and have it point to 'rebar3 help
<template>'
- show a 'template not found' message when a template is indeed not
found rather than crashing.
> Polish rough edges of 'new' provider

- src/rebar_prv_cover.erl
- test/rebar_cover_SUITE.erl
this pr moves the generated cover data to `_build/$PROFILE/cover` and runs the `cover` task under the `test` profile (like the `eunit` and `ct` tasks) so users can discriminate between different profiles coverage data
it also attempts to add paths to modules contained in the cover data so line by line coverage can be generated for them
> cover enhancements

- src/rebar_prv_common_test.erl
- src/rebar_prv_cover.erl
- src/rebar_prv_shell.erl
- test/rebar_ct_SUITE.erl
modify `ct` provider to copy selected directories and compile them alongside their source (ie, if `some_tests` is a directory that contains test suites beams resulting from compiling them will be
placed in `some_tests` in the appropriate `_build` directory)
also an actual test suite that tests some relevant things
and logs are now put in `_build/PROFILE/logs` by default
drawbacks to this provider:
test specifications aren't really supported. short of parsing them ourselves and deconstructing all their paths there's no way to get them to work well with the approach this provider takes (copy any test directories into `_build` then work as closely as possible to `ct_run` from there). instead, this provider just punts and doesn't copy or compile any directories leaving it up to the test …
> modify `ct` provider to copy selected directories and compile them

- rebar.config
- src/rebar_prv_as.erl
- src/rebar_prv_clean.erl
- src/rebar_prv_common_test.erl
- src/rebar_prv_compile.erl
- src/rebar_prv_cover.erl
- src/rebar_prv_do.erl
- src/rebar_prv_edoc.erl
- src/rebar_prv_erlydtl_compiler.erl
- src/rebar_prv_eunit.erl
- src/rebar_prv_help.erl
- src/rebar_prv_release.erl
- src/rebar_prv_tar.erl
- src/rebar_prv_update.erl
- src/rebar_prv_version.erl
- `rebar3 help erlydtl compile` would not resolve, now it does and prints `Usage: rebar3 erlydtl compile`
- `rebar3 help compile` would display `Usage: rebar compile`, now displays `Usage: rebar3 compile`
- Made sure all providers have a `desc` property so there is something to show for in help.
- Fixes #314
> Fix ns help

- src/rebar3.erl
- src/rebar_plugins.erl
Removes installing of global plugins as a special case.
Additionally removes the duplication of attempts to install/load deps plugins if the dep is already installed.
> Remove global plugins

- src/rebar_dir.erl
- src/rebar_erlc_compiler.erl
- src/rebar_prv_eunit.erl
- test/rebar_compile_SUITE.erl
This patch moves the erlc digraph found in `erlcinfo` to be per application instead of for the entire project. This allows to check if a file that was compiled before no longer exists and we can delete the corresponding beam file that was created from the now gone file.
> rm old beams, make erlcinfo graph per app isntad of global to project

- src/rebar.hrl
- src/rebar_app_discover.erl
- src/rebar_config.erl
- src/rebar_digraph.erl
- src/rebar_packages.erl
- src/rebar_prv_install_deps.erl
- src/rebar_prv_packages.erl
- src/rebar_prv_update.erl
- src/rebar_state.erl
- src/rebar_utils.erl
- test/mock_pkg_resource.erl
- test/rebar_compile_SUITE.erl
Fixes support for a single atom as a dep, like `{deps, [cowboy]}.`
Additionally simplifies the job of `rebar3 pkgs` and fixes an issue with not knowing package deps didn't need to be recompiled by using the `AppInfo` created when doing `rebar_app_discover:find/2` instead of the new one created by install deps to be filled in -- however we override the `state` for `AppInfo` with the one newly created since that one has the overrides applied for this run.
> support single atoms for pkg deps, fetch highest version available

- src/rebar_erlc_compiler.erl
- src/rebar_prv_common_test.erl
- src/rebar_prv_compile.erl
- src/rebar_prv_erlydtl_compiler.erl
- src/rebar_prv_escriptize.erl
- src/rebar_prv_report.erl
Main change: Instead of the common test provider having compile use the copied to test directory under `_build/test/lib` it now copies everything as before but the compile function is told to compile from the original test dir to the outdir under `_build/test/lib`.
This is important so that the "find erl files" part of the compiler doesn't find erl files that were added to data dirs during former runs.
> Mainly CT changes

- src/rebar_dir.erl
- src/rebar_prv_install_deps.erl
- src/rebar_prv_lock.erl
- test/rebar_install_deps_SUITE.erl
When fetching dependencies for the first time using a profile (`rebar3
as prod release` or `rebar3 ct`), the dependencies get fetched into the
non-default profile. This has two consequences:
- the files get re-downloaded on follow-up runs
- the lock file includes incomplete or too many deps in its list
This patch forces dependencies in the default profile to be stored in
_build/default/lib even when running under other profiles, then symlinks
them to the correct one.
This makes it so common dependencies in 'default' be downloaded there
and avoids re-downloading them. Should also fix the lock issues.
Should address https://github.com/rebar/rebar3/issues/307 and https://github.com/rebar/rebar3/issues/339
> Default deps always to the default profile

- src/rebar_prv_install_deps.erl
Fix for https://github.com/rebar/rebar3/issues/271
This way the erlydtl needed by rebar3/relx will be used when relx is building the release's scripts.
> add to end of code path not the beginning in handle_deps

- src/rebar_prv_update.erl
We should just ignore optional dependencies  on hex packages until we add real support for them.
> ignore optional deps for now

- src/rebar_app_discover.erl
- src/rebar_dir.erl
- src/rebar_prv_compile.erl
This patch keeps the top level config's hooks from being also considered a top level app's hooks. 
Before this fix a project like `relx` would end up running the `erlydtl` post compile hook twice. THis is done since we need to support the "project level" hooks so that a rebar.config can specify hooks even in a release project layout -- as in they aren't tied to a specific application that is being built.
> don't duplicate hooks for top level app

- src/rebar_app_discover.erl
- src/rebar_base_compiler.erl
- src/rebar_dir.erl
- src/rebar_prv_compile.erl
- src/rebar_prv_erlydtl_compiler.erl
- src/rebar_prv_escriptize.erl
Seeing the app that is about to be compiled as the project app before running compile hooks allows for simpler configs and providers that work the same at the top level and when part of dependencies.
Specifically I discovered this issue when using rebar3 to build rebar3 and erlydtl provider hook failing to work on relx.
> set the dep as the project app before running hooks

- src/rebar3.erl
- src/rebar_api.erl
- src/rebar_erlc_compiler.erl
- src/rebar_otp_app.erl
- src/rebar_prv_common_test.erl
- src/rebar_prv_compile.erl
- src/rebar_prv_cover.erl
- src/rebar_prv_dialyzer.erl
- src/rebar_prv_eunit.erl
- src/rebar_prv_install_deps.erl
- src/rebar_prv_shell.erl
- src/rebar_prv_xref.erl
- src/rebar_state.erl
- src/rebar_utils.erl
- test/rebar_compile_SUITE.erl
- test/rebar_profiles_SUITE.erl
- test/rebar_test_utils.erl
- test/rebar_xref_SUITE.erl
Not ready for merging but opening so discussion can go here. One particular part I'm wondering about is wanting to not have the deps of plugins in the path unless a plugin's provider is run, may be a pain to implement, but may be worth it as well.
And to take that to an even bigger extreme, we could only include deps of any provider in the path when that provider is run. Meaning only erlydtl and relx would not be in the path until their providers `do` functions are to be called. That may be overdoing it though.
> Track code path

- rebar.config
`rebar3 new help` currently doesn't find any templates
This fixes regression introduced in: https://github.com/rebar/rebar3/commit/3a63bec39fde05dcddf3f693dd780879662b599c#diff-31d7a50c99c265ca2793c20961b60979L4
> fix template listing (re-add escript_incl_extra)

- src/rebar_erlc_compiler.erl
Since an include_lib could be surrounded by a macro and not actually used we shouldn't have this warning, it could be wrong and confusing.
> remove warning if header not found, could be in a macro

- src/rebar_app_info.erl
- src/rebar_prv_install_deps.erl
This patch updates the `app_info` record for a dep after it is fetched so attributes like `applications` which is used for compilation order is accurate.  Fixes https://github.com/rebar/rebar3/issues/370
> read in application details into app_info after fetch

- src/rebar_app_discover.erl
- src/rebar_prv_app_discovery.erl
- Solve "Uncaught error" failure in case of syntax error in app.src file.
- Print helpful information on the location of the syntax error.
This was the output in case of an incorrect app.src file:
```
DEBUG=1 rebar3 compile
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace
===> Uncaught error: {'EXIT',
{function_clause,
[{rebar_app_info,app_file_src,
[error,
"/home/umberto/gitlab/emmebm/src/emmebm.app.src"],
[{file,
"/home/travis/build/rebar/rebar3/_build/default/lib/rebar/src/rebar_app_info.erl"},
{line,140}]},
{rebar_app_discover,find_app,2,
[{file,
"/home/travis/build/rebar/rebar3/_build/default/lib/rebar/src/rebar_app_discover.erl"},
{line,162}]},
{rebar_utils,filtermap,2,
[{file,
"/home/travis/build/rebar/rebar3/_build/default/lib/rebar/src/rebar_utils.erl"}, …
```
> Manage syntax error in app.src files.

- src/rebar_prv_common_test.erl
- test/rebar_ct_SUITE.erl
> delete all symlinks when copying from project files to `_build` tree to prevent any data from being overwritten

- priv/templates/app.template
- priv/templates/cmake.template
- priv/templates/escript.template
- priv/templates/lib.template
- priv/templates/plugin.template
Some templates like OTP apps are usable within releases, so the text
does remain a bit vague, but hopefully less than before.
> Make standalone vs complete project template clear

- src/rebar_prv_edoc.erl
```erlang
%% rebar.config
{edoc_opts, [
{doclet, edown_doclet}
]}.
{deps, [
{edown, ".*", {git, "git://github.com/uwiger/edown.git", {branch, "master"}}}
]}.
```
This becomes available.
> be able to use the specified edoclet in deps

- rebar.config.sample
- src/rebar_erlc_compiler.erl
- src/rebar_otp_app.erl
- src/rebar_prv_compile.erl
- src/rebar_prv_eunit.erl
- test/rebar_extra_src_dirs_SUITE.erl
like `src_dirs`, `extra_src_dirs` are directories to be copied to
the `_build` dir and compiled. unlike `src_dirs` they are not added
to the .app specification
> generalize the "test" special dir into an {extra_src_dirs, [...]} option

- priv/templates/gitignore
By default rebar3's new projects include a gitignore file. This file doesn't ignore _build but this is a directory one would probably not want to check in.
> Ignore the build directory

- src/rebar3.erl
- src/rebar_dir.erl
- src/rebar_plugins.erl
- src/rebar_prv_common_test.erl
- src/rebar_prv_install_deps.erl
- src/rebar_state.erl
- test/rebar_compile_SUITE.erl
- test/rebar_test_utils.erl
There is probably work to be done to ensure code paths are what we want for plugin use, but this at least installs them.
> install plugins from the global config to ~/.cache/plugins

- .gitignore
- src/rebar_prv_common_test.erl
- src/rebar_prv_eunit.erl
- src/rebar_utils.erl
I'm not 100% on this because it doesn't repurge after the initial purge. Unsure if that is necessary. Will work on adding that tomorrow, opening for feedback and suggestions.
> purge loaded code when it conflicts with project apps in tests

- README.md
Because Erlang Solutions now defaults to a download that includes third party libraries I think we should recommend installing from source using kerl or erln8 instead.
> update readme building instructions to prefer source

- src/rebar_dir.erl
- src/rebar_erlc_compiler.erl
- src/rebar_otp_app.erl
- src/rebar_prv_compile.erl
- test/rebar_dir_SUITE.erl
note that now ALL `src_dirs` across included profiles are
compiled. previously only the last included profile's `src_dirs`
were used
fixes #448
> methods for retrieving `src_dirs` and `extra_src_dirs`

- src/rebar_state.erl
Say, I have following project (just for example).
```
vkovalev@dijkstra:/tmp/bar$ tree
.
├── apps
│   └── bar
│       └── src
│           └── bar.app.src
├── rebar.config
└── rebar.lock
vkovalev@dijkstra:/tmp/bar$ cat rebar.config 
{erl_opts, [debug_info]}.
{deps, [
{jiffy, {git, "https://github.com/davisp/jiffy", {branch, "master"}}}
]}.
{overrides, [
{override, jiffy, [
{provider_hooks, [
{pre, [{compile, {default, clean}}]}
]}
]}
]}.
```
`rebar3 compile` fails when trying to execute `clean` hook on any dependency. Badmatch shoots [there](https://github.com/rebar/rebar3/blob/master/src/rebar_prv_clean.erl#L81), because `command_parsed_args` field in `rebar_state` [initialized with default value `[]`](https://github.com/rebar/rebar3/blob/master/src/rebar_state.erl#L54), which, I believe, …
> Properly initialize command parsed args in rebar state

- src/rebar_prv_common_test.erl
- src/rebar_prv_compile.erl
- src/rebar_prv_eunit.erl
adding it results in ct test suites being compiled before they're
properly copied so changes made to suites between runs are not
reflected if a run fails before test dirs are copied
> don't add `{extra_src_dirs, ["test"]}` to `test` profile

- src/rebar_app_discover.erl
- src/rebar_prv_compile.erl
- test/rebar_hooks_SUITE.erl
I have litle single-application project which have to run heavy long running hooks.
```
[vkovalev@t30nix foobar]$ tree
.
|-- rebar.config
`-- src
|-- foobar.app.src
`-- foobar.erl
1 directory, 3 files
[vkovalev@t30nix foobar]$ cat rebar.config 
{pre_hooks, [
{compile, "echo 'Hello there.'"}
]}.
{post_hooks, [
{compile, "echo 'BOO!'"}
]}.
```
Now `rebar3 compile` produces next output:
```
[vkovalev@t30nix foobar]$ rebar3 compile
Hello there.
Hello there.
===> Compiling foobar
BOO!
BOO!
```
Well, this is because hooks first is ran [here] (https://github.com/rebar/rebar3/blob/master/src/rebar_prv_compile.erl#L50) as project-level hooks. Then the same hooks is ran on 'application-level' [there] (https://github.com/rebar/rebar3/blob/master/src/rebar_prv_compile.er …
> Run hooks for single application only once.

- src/rebar_state.erl
- test/rebar_hooks_SUITE.erl
All circumstances as in #455. But for now let specify hook by its *short name*. Without specifying namespace.
```
{overrides, [
{override, jiffy, [
{provider_hooks, [
{pre, [{compile, clean}]}
]}
]}
]}.
```
Now it fails without saying something specific. Actually, symptoms appears [here](https://github.com/rebar/rebar3/blob/master/src/rebar_core.erl#L118). `providers:get_provider/3` returns `not_found` (or something, could not recall certainly), because namespace in *dependency state* is undefined. I think, rebar should copy namespace from its *root* state. Am I right?
> Properly setup namespace for dependency provider hooks

- src/rebar_prv_clean.erl
Same that had to be done for the compile provider. Clearly we need to abstract this. I'll work on that when I have time tomorrow. But this fixes https://github.com/rebar/rebar3/issues/459
> only run clean hooks once

- src/rebar3.erl
In #467  rebar acted quite unfairy promising to show stacktrace if DEBUG=1 will be set. However, it didn't show one. Commit fixes this inconveniencs.
> Show stacktrace to errors caught in rebar3 module.

- src/rebar_app_discover.erl
- test/rebar_disable_app_SUITE.erl
Allow for selectively enable/disable apps at build time.
@ferd the main interest is when an app has a lot of dependancies (C ports...) and moving it to a separate project would make the project too complex to maintain.
> Add excluded_apps rebar.config keyword

- src/rebar_prv_upgrade.erl
- test/mock_pkg_resource.erl
- test/rebar_upgrade_SUITE.erl
they would always be left unfound otherwise.
Fixes #480
> Fix upgrade of atom-only packages

- src/r3.erl
- src/rebar_agent.erl
- src/rebar_prv_do.erl
- src/rebar_prv_shell.erl
- moved path addition, config loading and app boot to before the shell
is available
- apps successfully booting are in an INFO message, failed to boot into
an ERROR message
- A warning is printed when apps are booted informing to please use
releases for actual deployment, and is omitted otherwise.
- Some minor refactorings otherwise.
I still want to figure out a good auto-included rebar3 binding for compiling and module loading within rebar3 shell itself.
> improve the rebar3 shell

- src/rebar_prv_shell.erl
When setting up a shell some time elapses between listing the pids and setting
the group_leader. If the process exited during that time then
erlang:group_leader/2 will crash with badarg.
> Fix badarg exception when setting group_leader for a dead pid

- rebar.config
- rebar.lock
- src/rebar_prv_app_discovery.erl
- src/rebar_prv_as.erl
- src/rebar_prv_clean.erl
- src/rebar_prv_common_test.erl
- src/rebar_prv_compile.erl
- src/rebar_prv_cover.erl
- src/rebar_prv_deps.erl
- src/rebar_prv_dialyzer.erl
- src/rebar_prv_do.erl
- src/rebar_prv_edoc.erl
- src/rebar_prv_escriptize.erl
- src/rebar_prv_eunit.erl
- src/rebar_prv_help.erl
- src/rebar_prv_install_deps.erl
- src/rebar_prv_lock.erl
- src/rebar_prv_new.erl
- src/rebar_prv_packages.erl
- src/rebar_prv_release.erl
- src/rebar_prv_report.erl
- src/rebar_prv_shell.erl
- src/rebar_prv_tar.erl
- src/rebar_prv_unlock.erl
- src/rebar_prv_update.erl
- src/rebar_prv_upgrade.erl
- src/rebar_prv_version.erl
- src/rebar_prv_xref.erl
- Crashes in providers lib when no providers in a namespace are bare
- Making sure bareness matches semantics; i.e. a bare provider is
visible, a non-bare provider is hidden.
Fixes https://github.com/rebar/rebar3/issues/484 -- Depends on https://github.com/tsloughter/providers/pull/8 after which I can amend this PR.
> fix bareness issues

- src/rebar_prv_compile.erl
- src/rebar_prv_escriptize.erl
I don't really like it. I feel we are getting more and more one off "save this state here" spots that may bite us later. We may want to look at splitting state into 2 types, 1 that is the constant changing state we are currently storing in `app_info` as well and another that is higher project stuff like `all_deps`.
This change is necessary so a dep that builds itself into an escript is still able to.
> keep all_deps list in state created for building deps

- src/rebar_prv_release.erl
- src/rebar_prv_tar.erl
Useful for running plugins like cuttlefish that need to run after release creation.
> run pre and post hooks for release and tar providers

- src/rebar3.erl
- src/rebar_plugins.erl
This is useful for plugins that themselves or dependencies that use provider hooks. Since a builtin provider will never rely on a plugin it is smart to set those up first so they are available for plugins when they compile.
> set default providers before installing plugins

- rebar.config
- src/rebar_prv_escriptize.erl
Automatically include the main application in the escript and fix error message if it can't find what is the main application.
Also improves the `rebar.config` for `rebar3` by removing the unneeded escriptize options.
> improve escriptize provider

- src/rebar_app_discover.erl
- src/rebar_app_info.erl
- src/rebar_prv_compile.erl
- src/rebar_prv_install_deps.erl
- src/rebar_state.erl
- test/rebar_hooks_SUITE.erl
This commit adds the config option:
```erlang
{artifacts, [filename()]}.
```
A dep is not considered "valid" (built) until all artifacts exist, in addition to the checks already done to make sure `.app`'s list of modules matches the available beam files for the app. So if an artifact does not exist it will run the compile provider and its hooks for that dep.
The filename is relative to the `base_dir`. So for example to verify `eleveldb` has successfully run the post hook port compiler you'd add:
```erlang
{artifacts, ["lib/eleveldb/priv/eleveldb.so"]}
```
Or for `cuttlefish`'s `escriptize` post hook:
```erlang
{artifacts, ["bin/cuttlefish"]}.
```
> add config option artifacts

- src/rebar_prv_dialyzer.erl
- test/rebar_dialyzer_SUITE.erl
* All configuration is moved to `{dialyzer, PropList}`
* `dialyzer_warnings` renamed `warnings`
* `dialyzer_plt_warnings` renamed `get_warnings`
* `dialyzer_plt_apps` renamed `plt_extra_apps`
* `dialyzer_plt_dir` renamed `plt_location`
* `{plt_location, local}` uses profile base directory
* `dialyzer_plt` removed
* `dialyzer_plt_prefix` sets prefix of PLT name (default "rebar3")
* `dialyzer_base_plt_apps` renamed `base_plt_apps`
* `dialyzer_base_plt_dir` renamed `base_plt_location`
* `{base_plt_location, global}` uses rebar3's global cache directory
* `dialyzer_base_plt` removed
* `base_plt_prefix` sets prefix of PLT name (default  "rebar3")
PLT files are always named `<prefix>_<otp_version>_plt` to match rebar.
`plt_prefix` and `base_plt_prefix` are not available in rebar, where the …
> Use the same dialyzer rebar.config options as rebar 

- src/rebar_prv_shell.erl
Whenever the old shell got killed and an app got loaded prior, the whole
thing would silently drop output as the old 'user' process was replaced
while application master processes would keep the old one's pid in
their internal state.
To work around this limitation, make sure the apps are booted only after
the shell is replaced so that only the new `user` pid is used.
> OTP apps show proper output

- src/rebar3.erl
- src/rebar_config.erl
- src/rebar_otp_app.erl
- src/rebar_state.erl
- test/rebar_deps_SUITE.erl
- test/rebar_test_utils.erl
If a list that can't be parsed into a dict is used in the config file right now it throws a worthless error message.
Ultimately we should probably do a top level check to try to help even more with what is wrong, but not sure how we want to do that yet.
I guess we'll have to write our own initial check when reading in the file that checks each top level tuple to see if it is a key-value pair and nothing else?
> catch error if config can't be parsed into dict to print error message

- src/rebar_prv_do.erl
- src/rebar_prv_help.erl
Add ssupport for printing help of all a namespaces' tasks
```
λ rebar3 pc      
pc <task>:
clean          clean the results of port compilation
compile        perform port compilation
```
And:
```
λ rebar3 help pc      
pc <task>:
clean          clean the results of port compilation
compile        perform port compilation
```
> print help for namespaces

- src/rebar_hooks.erl
- src/rebar_plugins.erl
Adds a useful debug message that is usually an error message but since we skip plugins if they don't build it is useful to print it out in debug in case it is being called from a plugin build.
Also fixes plugins relying on plugins to build by appending a plugins providers (plugins installed for the plugin in this case) in the providers passed to the compile provider.
> Plugins for plugins

- src/rebar_hooks.erl
- src/rebar_plugins.erl
This change ensures the State created in `install_deps` for the app is used when building the app if it is a plugin.
> fix for overrides in plugins, simpler plugin state handling

- THANKS
plugins that are only in the selected profiles have to be installed as well:
for `rebar.config`
```
{plugins, [{foo, {git, ...}}]}.
{profiles, [{p1,{plugins,[{bar, {git, ...}}]}}]}.
```
running `rebar3 as p1 bar` will not work without this.
> install_plugins in rebar_prv_as:do

- test/rebar_compile_SUITE.erl
- test/rebar_install_deps_SUITE.erl
- test/rebar_test_utils.erl
- tests locks by piggyback-riding the install deps suite, and makes sure to
test that non-default profiles don't get locked
- tests erl_first_files by using a parse transform that stamps modules with an
attribute as it runs them. It then compiles everything, loads the
module, and makes sure the stamps respect the defined order.
> More tests

- src/rebar_agent.erl
- src/rebar_dir.erl
- src/rebar_file_utils.erl
- src/rebar_git_resource.erl
- src/rebar_prv_common_test.erl
- src/rebar_prv_dialyzer.erl
- src/rebar_utils.erl
- test/rebar_compile_SUITE.erl
- test/rebar_hooks_SUITE.erl
- test/rebar_test_utils.erl
- test/rebar_utils_SUITE.erl
1. First issue I've encountered when using rebar3 on windows was something like #395. Just try to run `rebar3 ct` in rebar's own project directory. Command will truncate all files in `test` dir and fail. Issue is in how `rebar_prv_common_test` dealing with symlinks.
2. Fix issue with dependencies downloading and long file names.
3. Fix dialyzer provider.
4. Fix issue with duplicating common test runs for single-project application.
5. Fix funky issue with `rebar_ct_SUITE:multi_app_default_dir/1` caused by seeding random generator with os:timestamp().
[![Windows build status](https://ci.appveyor.com/api/projects/status/twlj92ewp0l5sr85/branch/windows-ct-fix?svg=true)](https://ci.appveyor.com/project/kovyl2404/rebar3)
> Make test on windows green.

- rebar.config
This reverts commit 40ee6d95e103f29c89c8a17c300c30448061c287.
You can't ctrl-c out of a running rebar3 command with this disabled, that isn't acceptable :(
> Revert "disable ctrl-c interrupt in shell for escript"

- src/rebar_app_discover.erl
This change allows yaws, which has .app.src and .app.src.script files, to be built with rebar3
> Read and process .app.src.script if present

- priv/templates/plugin.erl
- priv/templates/plugin.template
- priv/templates/provider.erl
I think this makes it less confusing to start from a plugin template and implement a plugin with multiple providers.
> update plugin template to separate plugin init and providers

- rebar.config.sample
- src/rebar_prv_cover.erl
- test/rebar_cover_SUITE.erl
`{cover_print_enabled, true}` dropped in favour of `{ct_opts, [verbose]}`
`{cover_data_dir, "..."}` dropped for now. can be replaced with something in `ct_opts` if anyone complains it was dropped
addresses #576
> remove `cover_print_enabled` and `cover_data_dir` config options and replace with `cover_opts`

- src/rebar_plugins.erl
- src/rebar_prv_install_deps.erl
- src/rebar_prv_plugins_upgrade.erl
- test/rebar_install_deps_SUITE.erl
- test/rebar_test_utils.erl
To fix issue with conflicting deps between profiles with differing levels and versions this patch changes from installing all deps for a profile to installing a level at a time. For example: `rebar3 as nondef compile` will install level 0 of `nondef` profile, hold on to level 1 deps for `nondef` in a list, install level 0 of `default` profile, store its level 1 deps, and so on until there are no more `{profile, deps}` tuples in the list.
> wip: deps install refactor

- src/rebar_agent.erl
- src/rebar_prv_shell.erl
This tries to reduce memory usage when running `rebar3 shell` by running
the agent in the current process (and avoiding to copy state
cross-boundaries), and using frequent hibernation after each run to
force a full GC and compaction of the current process.
> Run agent as current process & hibernate

- src/rebar_file_utils.erl
Changed so that we don't use variables that are declared inside a case outside that case.
> Changed cases on robocopy so it uses variables in a better way

- THANKS
- bootstrap
- src/rebar3.erl
- src/rebar_pkg_resource.erl
- src/rebar_prv_update.erl
- src/rebar_utils.erl
- test/rebar_deps_SUITE.erl
Add proxy support to bootstrap and rebar3.
Either bootstrap and rebar3 now uses environment variables http_proxy and https_proxy to fetch dependency packages and hex plugins.
Enhancement #561.
> Add proxy support to bootstrap and rebar3. Enhancement #561.

- src/rebar_prv_install_deps.erl
- test/rebar_test_utils.erl
- test/rebar_upgrade_SUITE.erl
I'm not 100% on this fix, but all tests pass :) and worked locally on sniffle. My guess is the different way of handling "seen" deps before we moved to the new way of handling the install process was because we didn't go level by level and now that we do we can treat it mostly the same even when it is an upgrade.
> pass failing upgrade case where levels are increased

- bootstrap
- src/rebar_state.erl
Fixes https://github.com/rebar/rebar3/issues/608
Plugins installing plugins got wonky because of profile application changing the global profile to default/global.
Also threw in a fix for if a previous bootstrap goes bad and writes an empty lock file because you screw something up so it doesn't find deps (I did).
> Global plugin bug

- src/rebar_prv_compile.erl
- src/rebar_prv_eunit.erl
i'm reasonably certain that this is safe to revert (fixing #568 and #575) as it was a fix for an issue with common_test loading the wrong tests that i think was actually caused by the regression in #440 or made irrelevant by #474 
i can't reproduce the common_test problem either way
> Revert "don't add `{extra_src_dirs, ["test"]}` to `test` profile"

- src/rebar_prv_compile.erl
Need to ensure all plugins are in the code path after a compile provider run. Before this fix depending on when a plugin provider was added and if there were hooks declared (hooks also remove paths after running) would cause providers that run post compile to become undefined.
> keep plugins in path after compile provider run

- src/rebar_file_utils.erl
- src/rebar_git_resource.erl
- src/rebar_hg_resource.erl
- src/rebar_utils.erl
Basic escaping is done only. Fancy hex sequences are not covered, but
this should otherwise take care of the most common issues.
Fixes #497
> Escape paths and args in shell commands

- src/rebar_file_utils.erl
- src/rebar_prv_install_deps.erl
See #634 
Linking message will only be printed the first time the link or copy
actually happens.
Note:
rebar_file_utils:symlink_or_copy will now return 'exists'
instead of ok, if it did nothing because the link exists.
Nothing was checking the return value yet, so seemed reasonable.
> Tidy up "Linking.." messages during compile

- src/rebar_prv_plugins_upgrade.erl
```
λ cat ~/.config/rebar3/rebar.config
{plugins, [rebar3_hex]}.
```
```
λ grep plugins rebar.config
{plugins, [rebar3_live]}.
```
```
λ env DEBUG=1 rebar3 plugins upgrade rebar3_hex
===> Load global config file /Users/mao/.config/rebar3/rebar.config
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace
===> Uncaught error: function_clause
===> Stack trace to the error location: [{rebar_prv_plugins_upgrade,
find,
[rebar3_hex,[rebar3_live]],
[{file,
"/Volumes/Private/src/rebar3/_build/default/lib/rebar/src/rebar_prv_plugins_upgrade.erl"},
{line,90}]},
{rebar_prv_plugins_upgrade,
'-find_plugin/3-fun-0-',3,
[{file,
"/Volumes/Private/src/rebar3/_build/default/lib/rebar/src/rebar_prv_plugins_upgrade.erl"},
{line,82}]},
{ec_lists,search,2,
[{file, …
```
> Fix plugin upgrade when plugin mentioned only by its name

- src/rebar_digraph.erl
- src/rebar_prv_install_deps.erl
This is a fix for https://github.com/rebar/rebar3/issues/674
The issue was that all the "collected" package deps, whether from parsing `rebar.config` at the top level or parsing the `rebar.config` of a git dep would end up being considered at level 0. This patch stores the actual Level with the package deps so the lock file is correct.
> keep correct Level for pkg deps of scm deps

- src/rebar_prv_new.erl
`template` is not a kv-style argument, but a plain argument. If you give `template=app` on the command line, you get "template not found."
> Fix description in "rebar3 new"

- src/rebar_app_discover.erl
- src/rebar_config.erl
- src/rebar_digraph.erl
- src/rebar_prv_deps.erl
- src/rebar_prv_install_deps.erl
- src/rebar_utils.erl
If a digraph is passed to `cull_deps` it keeps track of the solution which can be printed out with `rebar3 deps -t`.
Additionally, to make this possible without duplicates, there are some fixes for unneeded duplicates in deps list that gets passed around, which caused no issues for install because it had a proper order but wasted resources and caused issues with `deps -t`.
> add tree option to deps command that prints pkg deps tree

- src/rebar_prv_shell.erl
Addresses https://github.com/rebar/rebar3/issues/688
Displays: `===> Erlang Distribution failed, falling back to nonode@nohost. Verify that EPMD is running and try again` in red (as ERROR)
> Detect missing EPMD, error, fallback and advise.

- README.md
- priv/shell-completion/bash/rebar3
- priv/shell-completion/fish/rebar3.fish
- priv/shell-completion/zsh/_rebar3
- src/rebar.app.src
- src/rebar_app_info.erl
- src/rebar_digraph.erl
- src/rebar_prv_deps.erl
- src/rebar_prv_deps_tree.erl
- src/rebar_prv_install_deps.erl
This requires https://github.com/rebar/rebar3/pull/706 be merged first.
The change for this PR is the addition of the `tree` provider. I split it out from `deps` because it depends on the dependencies getting installed and and `deps` does not. So the `-t` option is removed from `deps`.
Example output on the project `project-fifo/howl`:
```
|- clique-0.0.0+build.140.ref8067df5 (git repo)
|- cowboy-1.0.1 (git repo)
|  |- cowlib-1.0.0 (git repo)
|  |- ranch-1.0.0 (git repo)
|- cuttlefish-0.0.0+build.479.reff5f6fdc (git repo)
|  |- getopt-0.4.3 (git repo)
|  |- neotoma-0.0.0+build.125.ref760928e (git repo)
|- edown-0.2.4+build.98.refb7c8eb0 (git repo)
|- eper-0.87.0 (git repo)
|- fifo_spec-0.1.17 (git repo)
|  |- fifo_dt-0.1.48 (git repo)
|  |  |- riak_dt-0.0.0+build.307.reff7981d4 (git repo) …
```
> Tree provider

- src/rebar_digraph.erl
- src/rebar_erlc_compiler.erl
- src/rebar_prv_update.erl
After starting `rebar3 shell` there is a lots of `ets` tables that belongs to some digraphs. 
```
45086           hex_registry      set   4323   243631   rebar_agent
98335           vertices          set   3495   58249    rebar_agent
102432          edges             set   368    11684    rebar_agent
106529          neighbours        bag   738    16482    rebar_agent
110626          hex_registry      set   4323   243631   rebar_agent
114723          vertices          set   4      346      rebar_agent
118820          edges             set   5      393      rebar_agent
122917          neighbours        bag   12     472      rebar_agent
135208          vertices          set   16     468      rebar_agent
139305          edges             set   36     931      rebar_agent
143402 …
```
> fix leaking ets tables caused by digraphs

- test/mock_git_resource.erl
- test/rebar_compile_SUITE.erl
- test/rebar_deps_SUITE.erl
- test/rebar_install_deps_SUITE.erl
- test/rebar_plugins_SUITE.erl
- test/rebar_profiles_SUITE.erl
- test/rebar_test_utils.erl
- test/rebar_upgrade_SUITE.erl
Requires a rework of other test suites using the same dep-handling
mechanism.
Will be useful to find issues with mixed dependencies.
Currently:
- missing warnings when a pkg dep is skipped because of a source dep
- if a pkg dep and a src dep of the same name are used at the top-level, we apparently keep them in an order that disregards "source always wins". May not be a bug?
- overriden source dep onto a package is silently ignored rather than erroring out.
> [WIP] Add tests for mixed deps installs

- src/rebar.hrl
- src/rebar3.erl
- src/rebar_app_discover.erl
- src/rebar_app_info.erl
- src/rebar_app_utils.erl
- src/rebar_digraph.erl
- src/rebar_packages.erl
- src/rebar_plugins.erl
- src/rebar_prv_install_deps.erl
- src/rebar_prv_packages.erl
- src/rebar_prv_update.erl
- src/rebar_prv_upgrade.erl
- src/rebar_state.erl
- test/mock_pkg_resource.erl
- test/rebar_deps_SUITE.erl
- test/rebar_install_deps_SUITE.erl
- test/rebar_pkg_SUITE.erl
Instead fetching and resolving src deps (which could depend on pkg deps)
and then pkg deps this patch combines the two into a single set of
iterations by level. The only difference between src and pkg deps in this
new install_deps is how their deps list is found -- from the config or
lock file for src deps and from the neighbors of the vertex for pkg.
Fixes https://github.com/rebar/rebar3/issues/699
> this patch treats pkg and src deps as equals, so level decides winner

- src/rebar_file_utils.erl
- src/rebar_packages.erl
- src/rebar_pkg_resource.erl
- src/rebar_prv_update.erl
- test/rebar_pkg_SUITE.erl
Basically changes the `rebar3 update` output to:
```
λ rebar3 update
===> Updating package registry...
===> Writing registry to ~/.cache/rebar3/hex/default/registry
===> Generating package index...
===> Writing index to ~/.cache/rebar3/hex/default/packages.idx
```
I prefer this use of `default` instead of the long directory name when it is going to be the majority of the cases.
> use 'default' for default hex repo path in cache and include in info messages

- src/rebar_app_discover.erl
- src/rebar_state.erl
The issue was that deps were being set in the state before dedup, which meant the non-locked dep was in the list before the locked entry. Now we replace the deps entry with the updated value.
Fixes https://github.com/rebar/rebar3/issues/725
> don't store deps list with duplicate in state

- src/rebar_state.erl
- test/rebar_compile_SUITE.erl
Fixes https://github.com/rebar/rebar3/issues/704 and https://github.com/rebar/rebar3/issues/719
> override 'deps' now automatically overrides '{deps,default}'

- src/rebar_prv_install_deps.erl
Adds an error message for cases like that in https://github.com/rebar/rebar3/issues/743
> add error message for dependency that doesn't contain single app dir

- src/rebar_prv_upgrade.erl
Adds a useful warning and no longer errors out when the user removes a top level dep and then runs `upgrade`. Fix for https://github.com/rebar/rebar3/issues/729
> don't error on upgrade if user removes top level dep

- src/rebar_prv_packages.erl
- test/rebar_pkg_SUITE.erl
Fixes https://github.com/rebar/rebar3/issues/749 and adds a test to just verify that `rebar3 pkgs` doesn't crash.
> fix pkgs provider output for new package index format

- src/rebar_prv_eunit.erl
- test/rebar_eunit_SUITE.erl
equivalent to 'eunit:test([{file, "file_one"}, {file, "file_two"}, ...])'
> add support for `rebar3 eunit --file=...'

- src/rebar_prv_common_test.erl
fixes issue with persistent compilation errors for files in `./test`
> symlink ct test dirs rather than copy

- src/rebar_file_utils.erl
This patch forces write_file_if_contents_differ/2 to use raw bytes as
when writing files. This fixes an issue where UTF-8 characters are
processed and written back as ISO-8859-1 into the file, which makes it
impossible to use UTF-8 characters in .app.src files.
Supercedes https://github.com/rebar/rebar3/pull/618
> Use raw bytestream when writing files

- src/rebar_app_utils.erl
Fixes https://github.com/rebar/rebar3/issues/758
Before it was only properly setting the Parent when a dep had to be fetched.
> set parent on already fetched apps so tree works

- src/rebar_prv_deps_tree.erl
I added the reset to latin1 and changed the format sequence to `~ts` which works for me, just `~s` doesn't work for me.
> use ~ts for unicode output and reset encoding to latin1

- src/rebar_pkg_resource.erl
This makes it obvious where packages are cached and when the cache is
being reused.
Messages are of the form:
```
===> Fetching recon ({pkg,<<"recon">>,<<"2.2.0">>})
===> Downloaded package, caching at $HOME/.cache/rebar3/hex/default/packages/recon-2.2.0.tar
```
and
```
===> Fetching recon ({pkg,<<"recon">>,<<"2.2.0">>})
===> Version cached at $HOME/.cache/rebar3/hex/default/packages/recon-2.2.0.tar is up
to date, reusing it
```
> Displays package caching actions

- src/rebar_app_discover.erl
- src/rebar_app_info.erl
- src/rebar_app_utils.erl
- src/rebar_base_compiler.erl
- src/rebar_dir.erl
- src/rebar_erlc_compiler.erl
- src/rebar_hooks.erl
- src/rebar_opts.erl
- src/rebar_otp_app.erl
- src/rebar_plugins.erl
- src/rebar_prv_clean.erl
- src/rebar_prv_common_test.erl
- src/rebar_prv_compile.erl
- src/rebar_prv_install_deps.erl
- src/rebar_prv_plugins_upgrade.erl
- src/rebar_state.erl
- src/rebar_utils.erl
- test/rebar_dir_SUITE.erl
- test/rebar_profiles_SUITE.erl
- test/rebar_src_dirs_SUITE.erl
This is an initial look at breaking out the parts of `rebar_state` that aren't global to within `rebar_app_info` (like individual app's erl_opts, overrides, etc).
I'm not sure yet what I'll do with `providers` and code paths since they may need to be per app (like a plugin).
> move state into app_info

- src/rebar_app_utils.erl
Fix for #744 but won't make sense until after https://github.com/rebar/rebar3/pull/760 is merged because it builds on it.
> Fix #744: Allow _checkouts dep to override pkg dep not in registry

- src/rebar_utils.erl
Related to #770 
Using `replace_path` and I see the code path has properly replaced `erlware_commons` within the code path with the correct local copy that we are attempting to run the tests of.
```
Path ["/home/tristan/Devel/erlware_commons/_build/test/lib/proper/ebin",
"/home/tristan/.cache/rebar3/plugins/rebar3_run/ebin",
"/home/tristan/.cache/rebar3/plugins/rebar3_hex/ebin",
"/home/tristan/.cache/rebar3/plugins/jsx/ebin",
"/home/tristan/Devel/erlware_commons/../rebar3/rebar3/ssl_verify_hostname/ebin",
"/home/tristan/Devel/erlware_commons/../rebar3/rebar3/relx/ebin",
"/home/tristan/Devel/erlware_commons/../rebar3/rebar3/rebar/ebin",
"/home/tristan/Devel/erlware_commons/../rebar3/rebar3/providers/ebin",
"/home/tristan/Devel/erlware_commons/../rebar3/rebar3/getopt/ebin", …
```
> delete and prepend code path instead of replacing, fixes #770

- src/rebar_prv_common_test.erl
[There is](http://www.erlang.org/doc/man/ct.html#run_test-1) only `cover` option but [rebar_prv_common_test.erl]( https://github.com/rebar/rebar3/blob/master/src/rebar_prv_common_test.erl#L464) uses `cover_spec`
> Fix cover_spec options for ct

- src/rebar_app_discover.erl
- src/rebar_app_info.erl
- src/rebar_dir.erl
- src/rebar_hooks.erl
- src/rebar_packages.erl
- src/rebar_prv_install_deps.erl
- src/rebar_templater.erl
- test/rebar_hooks_SUITE.erl
All hooks will be run as part of the `app_info` set of hooks, in `compile` for example: https://github.com/rebar/rebar3/blob/master/src/rebar_prv_compile.erl#L87 and artifacts will be found relative to an app's output directory, except in the case of being defined in the rebar.config at the top level of an umbrella project. In that case artifacts will be resolved from `profile_dir` (eg `_build/default/`) and hooks will be run from the top level before any part of a provider is run, like https://github.com/rebar/rebar3/blob/master/src/rebar_prv_compile.erl#L49
Additionally 3 variable can be used in the artifacts string: `base_dir`, `profile_dir` or `out_dir` -- `out_dir` is the default path to start finding artifacts but I figured it would be nice to let it be explicit as well, example: …
> hooks/artifacts are always run/resolved from an app unless at top of umbrella

- src/rebar_hooks.erl
- src/rebar_prv_clean.erl
- src/rebar_prv_compile.erl
- src/rebar_prv_plugins.erl
- test/rebar_plugins_SUITE.erl
This patch allows for a hook to update the opts of an appinfo record, hopefully being enough for what @Licenser wants in https://github.com/rebar/rebar3/issues/670
An example would be a provider that you define in `provider_hooks` to run before `compile` which adds to `erl_opts`:
```
do(State) ->
AppInfo = rebar_state:current_app(State),
ErlOpts = rebar_app_info:get(AppInfo, erl_opts, []),
AppInfo1 = rebar_app_info:set(AppInfo, erl_opts, [{d, 'SOME_DEFINE'} | ErlOpts]),
{ok, rebar_state:current_app(State, AppInfo1)}.
```
> support updating of per app info by hooks

- README.md
- priv/shell-completion/bash/rebar3
- priv/shell-completion/fish/rebar3.fish
- priv/shell-completion/zsh/_rebar3
- src/rebar.app.src
- src/rebar_prv_path.erl
prints requested paths to stdout based on current profile
usage:
```bash
$ echo `rebar3 path`
/Users/talentdeficit/dev/erlang/rebar/_build/default/lib/ssl_verify_hostname/ebin /Users/talentdeficit/dev/erlang/rebar/_build/default/lib/relx/ebin /Users/talentdeficit/dev/erlang/rebar/_build/default/lib/providers/ebin /Users/talentdeficit/dev/erlang/rebar/_build/default/lib/getopt/ebin /Users/talentdeficit/dev/erlang/rebar/_build/default/lib/erlware_commons/ebin /Users/talentdeficit/dev/erlang/rebar/_build/default/lib/bbmustache/ebin /Users/talentdeficit/dev/erlang/rebar/_build/default/lib/rebar/ebin
$ echo `rebar3 path --base`
/Users/talentdeficit/dev/erlang/rebar3/_build/default
$ echo `rebar3 path --app=rebar,providers --ebin --seperator=","` …
```
> `rebar3 path' provider

- README.md
- priv/shell-completion/bash/rebar3
- priv/shell-completion/fish/rebar3.fish
- priv/shell-completion/zsh/_rebar3
- src/rebar.app.src
- src/rebar3.erl
- src/rebar_pkg_resource.erl
- src/rebar_prv_local_install.erl
- src/rebar_prv_local_upgrade.erl
This is a proposal for making it easy for a user to use rebar3 without the escript. Not relying on the escript allows for a faster start time and fully functioning shell.
To use:
```
$ ./bootstrap
$ ./rebar3 local install
$ export PATH=$PATH:~/.cache/rebar3/bin/rebar3
$ rebar3 <task>
```
> add 'local install' and 'local upgrade'

- .travis.yml
- rebar.config
Fix for https://github.com/rebar/rebar3/issues/794
But we can no longer build the escript for uploading to s3 with R15B03 because of a bug in filelib.
> use full path of apps for priv files included in escript

- src/rebar_prv_local_install.erl
Fixes use of providers like `rebar3 hex` which reads user input.
> replace noinput with noshell so providers that ask for input work

- rebar.config.sample
- src/rebar.hrl
- src/rebar_prv_dialyzer.erl
- test/rebar_dialyzer_SUITE.erl
- test/rebar_localfs_resource.erl
According to https://github.com/rebar/rebar3/issues/778, I tried to add `plt_include_all_deps` dialyzer option.
```erlang
%% in rebar.config
{dialyzer, [
{plt_include_all_deps, true}
]}.
```
If the value is `true`, dialyzer will include not only the first level dependencies but also all nested dependent applications in the PLT file.
> Add plt_include_all_deps dialyzer option

- src/rebar_pkg_resource.erl
Version #'s with patch info like "1.1.1-x" would cause an error. Now
tokenize the version string with "." AND "-".
Some versions of OTP return an unexpected version #:
```
8> application:get_key(ssl, vsn).
{ok,"6.0.1-basho1"}
```
This was causing a bootstrap error:
```
./bootstrap
===> Updating package registry...
===> Writing registry to /home/jbalint/.cache/rebar3/hex/default/registry
===> Generating package index...
===> Writing index to /home/jbalint/.cache/rebar3/hex/default/packages.idx
===> Fetching bbmustache ({pkg,<<"bbmustache">>,<<"1.0.4">>})
escript: exception error: no match of right hand side value
{error,
{rebar_fetch,
{fetch_fail,{pkg,<<"bbmustache">>,<<"1.0.4">>}}}}
```
> Fix parsing of version #'s of dependencies

- src/rebar_git_resource.erl
Fixing two bugs in semantic versions with git and hopefully improved it.
I noticed the issue(s) while working with rebar3 on a project that uses jiffy. jiffy relies on semantic versioning, and tags various versions, but does not include a 'v' prefix in the tag. As such, rebar3 was unable to detect the version. This was the first bug. This is fixed by making the v prefix optional.
The second bug was more subtle and has no readily available example (though one is easy to prepare). Specifically, suppose you had checked out an older tag of a repository that used semantic versioning: when compiling the .app file, the regex used would find the *latest* tag, not the current tag, and use that for the version. This is the second bug. This is fixed by looking for the "HEAD" string in the git log …
> Improved git versioning

- src/rebar.app.src
- src/rebar_prv_bare_compile.erl
- src/rebar_prv_compile.erl
- src/rebar_prv_escriptize.erl
- src/rebar_prv_local_install.erl
For https://github.com/rebar/rebar3/issues/671
Example:
```
rebar3 bare compile
```
Note you'll need to set `ERL_LIBS` for any dependencies needing for compilation and plugins still go to `_build/default/plugins`.
> add 'bare compile' provider, for starters for use by mix

- src/rebar_git_resource.erl
Reverts rebar/rebar3#811
Discovered there was an issue with the second part of the change, where it checks for `HEAD` in the regex. This breaks former usage and seems to cause a non-semver compliant version to be created.
> Revert "Improved git versioning"

- rebar.config
- rebar.lock
- src/rebar_utils.erl
Includes changes related to the `v` prefix in versions being optional now.
> Update erlware commons and relx

- src/rebar_app_discover.erl
- src/rebar_app_info.erl
- src/rebar_otp_app.erl
If an app is upgraded and no longer has a `.app.src` file (but it did before) the app record still contained a path for that file that no longer exists as though it was still expected to use it. The fix here sets `app_src` to undefined if it isn't there when the new version is unpacked and inspected so that later rebar3 doesn't attempt to read it in expecting it to be there.
> handle case that upgraded app no longer has .app.src file

- src/rebar_prv_install_deps.erl
Just makes the `Upgrading ...` output the same as `Fetching ...`.
> include source the app is being ugpraded to, like with fetching, in info

- src/rebar_git_resource.erl
Fixed the broken of two reverted patches such that it only returns the latest tag and no additional abbreviation, thus leaving the abbreviation to rebar.
> Git versioning 2

- src/rebar_config.erl
- test/rebar_deps_SUITE.erl
Stupidly wasn't parsing an empty lock like a normal lock file. Getting rid of that special case in `rebar_config` makes sure newly added deps are treated the same whether the lock is empty or contains locks -- but exists. Also adds a test for that case, we were already testing the case that the lock had contents and a new dep was added to rebar.config.
> handle newly added deps to config even when lock is empty

- src/rebar_dir.erl
- src/rebar_file_utils.erl
- test/rebar_dir_SUITE.erl
- test/rebar_file_utils_SUITE.erl
useful in more contexts than just rebar_prv_common_test and this allows tests
they're currently duplicated in rebar_prv_common_test but will be removed in a separate pr once (if) this one is accepted
> extract `retarget_path/2', `relative_path/2' and `reduce_path/1' and add tests

- test/rebar_ct_SUITE.erl
this test almost certainly only fails under very limited circumstances
limiting it's utility. it is known to fail with some versions of rebar3
when this test is run via `rebar3 ct --cover`
> test for ensuring `data_dir` is set correctly in ct configs

- src/rebar_erlc_compiler.erl
- test/rebar_compile_SUITE.erl
`rebar_erlc_compiler` has a faculty to compile arbitrary files but it's not exposed. it'd be useful for `ct`, `eunit` and possibly other providers to expose this
> add an export to allow specifing arbitrary extra erl files to be compiled

- src/rebar3.erl
The current code could not cope with missing dependencies, as they would
prevent the rebar3 app from loading or properly building its config,
which prevented the log state from being carried along with default
values. This in turn would turn in an escript-level error that
obfuscated the true source of failure.
This patch bypasses the whole state setup and logging macros and logs an
error message manually when a dependency such as crypto or SSL is
missing from the Erlang install.
Fixes https://github.com/rebar/rebar3/issues/836
> Properly warn on missing rebar3 deps

- src/rebar_prv_shell.erl
The list of applications in the relx config section could contain
tuples. The tuple will either contain a version constraint for the app,
the start type of the app or both.
This fix silently expands `{shell_apps, [Apps]}` to support the same
format.
fixes #764
> Shell handles all possible relx app formats

- src/rebar_prv_upgrade.erl
- test/rebar_upgrade_SUITE.erl
This commit replaces the method of upgrading by unlocking all transitive
deps by one that utilizes the parent element of each app to only
unlock transitive deps of children of the top level deps being upgraded.
Additionally the run function of upgrade_SUITE is modified to only create
the mock updates before the upgrade provider is run, instead of before
any provider is run, which would cause improper behavior in install_deps.
> only upgrade children and transitive children of dep being upgraded

- priv/templates/vm.args
Better default. More likely that the long name doesn't work for someone than the short name.
> make short name the default in vmargs

- src/rebar_pkg_resource.erl
Uses global rebar config to see if user wishes to disable ssl verfication.
If {ssl_verify, false} is present certificates will not be verified.
> Add support for disabling ssl verification for hex

- rebar.config
- rebar.lock
- src/rebar_dialyzer_format.erl
- src/rebar_prv_dialyzer.erl
Some more improvements on output, it's now easier to spot the file / line number the warning is in those are coded cyan. Also warnings are grouped by file now and the filename is only printed once. 
This combination allows for a more concise output while staying nicely readable.
> Group dialyzer warnings by file and concentrate output

- src/rebar_hooks.erl
This is necessary for some rebar2 repos to build because they have script hooks that utilize these env variables.
Fix for https://github.com/rebar/rebar3/issues/855
> add ERLANG_ARCH and ERLANG_TARGET to os env for hooks

- src/rebar_erlc_compiler.erl
- test/rebar_compile_SUITE.erl
This passes the directory to the option to ensure it works with more
than configs at the root of the project.
This should fix https://github.com/rebar/rebar3/issues/861
> Support proper paths in non-erl first files

- src/rebar_prv_deps_tree.erl
Fix for issue #859 - unicode rendering of deps tree based on PR #865
modified PR #865 to the /utf8 flag indicates this is supposed to be a UTF8 string.
> Fix for issue #859 - unicode rendering of deps tree based on PR #865

- rebar.config
- rebar.lock
cf 0.1.3 fixes the issue mentioned in #879 and marks all xterm* terminals as colour capable.
> Bump cf for fixing #879

- rebar.config
- src/rebar_erlc_compiler.erl
- src/rebar_prv_clean.erl
- src/rebar_prv_common_test.erl
- src/rebar_prv_compile.erl
- src/rebar_prv_cover.erl
- src/rebar_prv_eunit.erl
- src/rebar_utils.erl
- test/rebar_compile_SUITE.erl
- test/rebar_cover_SUITE.erl
- test/rebar_ct_SUITE.erl
- test/rebar_eunit_SUITE.erl
- test/rebar_file_utils_SUITE.erl
- test/rebar_src_dirs_SUITE.erl
- test/rebar_test_utils.erl
changes:
* `extra_src_dirs` are copied from the project to `_build` either relative to the app they are relative to in the project or relative to `_build/profile/extras`. they're compiled in place. copied instead of symlinked so profiles can't leak into one another (and also to keep beams out of the project directories) and compiled in place because `ct` can't handle them being in `ebin`. `rebar_file_utils` calls out to shell to copy files but this loses metadata so anything in an extra dir is going to be recompiled every single time compile is invoked but there's a metadata preserving copy in ec_file that could be used instead. that can be a separate change though
* any directory in `_build` that is used as a compiler output target is added to the code_path/all_deps. i believe this is …
> compiler refactor/eunit & ct fixes

- src/rebar_dir.erl
- test/rebar_dir_SUITE.erl
- test/rebar_src_dirs_SUITE.erl
deduplicating `src_dirs` on read removes the need to do it at call site repeatedly or do an upsert style add to `src_dirs`
> dedup `src_dirs` and `extra_src_dirs` on read

- src/rebar_utils.erl
prevents code reloading by temporary marking of rebar3's ebin dir
as sticky during code refresh
> prevent rebar3 from reloading it's own path and terminating itself

- src/rebar_prv_common_test.erl
- src/rebar_prv_eunit.erl
- src/rebar_utils.erl
at the cost of some SASL warnings this prevents rebar3 from terminating
processes when reloading their code before running tests
> add an option to soft purge rather than purge old code

- src/rebar_prv_common_test.erl
- test/rebar_ct_SUITE.erl
possible fix for #892
the inability to run ct within ct makes this difficult to test properly and when i have more time i'm going to experiment with some better method of testing, but this works for the test repo provided in #892 and seems to work on some projects i have that use ct
> calculate coverage info as late as possible in ct provider execution

- src/rebar_opts.erl
Fix for https://github.com/rebar/rebar3/issues/897
> do not sort mib_first_files during merge_opts, order must be kept

- rebar.config
- rebar.lock
- src/rebar.app.src
- src/rebar_prv_common_test.erl
This uses cth_readable to:
- silence error_logger output to the shell unless a test fails
- silence ct:pal output to the shell unless a test fails
I have currently not baked in any way to disable this behaviour, but I
figured if it is required, there is time to do it before the final
3.0.0 release.
> Prettify all of common test output.

- src/rebar_prv_shell.erl
Runs a user-specified escript to initialize a system before starting the project Apps and the interactive shell. This allows for development-only frameworks and scaffolding to start before brining up the system for interactive use.
> rebar3 shell improvements (escript, rebar.config shell defaults)

- rebar.config
- rebar.lock
- src/rebar.app.src
- src/rebar_prv_eunit.erl
Pinging @seancribbs in case he has any warnings about making this a default.
It can be turned off by either the user already having a `report` key in their eunit opts or setting `eunit_formatters` to `false` in `eunit_opts`.
> include Sean Cribbs eunit formatter by default

- src/rebar_erlc_compiler.erl
In some cases (nested includes?) paths end up in such a way that joining
them breaks up and hard-crashes rebar3. This patch specifically handles
this scenario to fix things by avoiding passing empty lists to
filename:join.
fixes #914.
I'm not sure how exactly to reproduce for tests. I showed it is fixed it by using https://github.com/rabbitmq/rabbitmq-erlang-client : 
```
→ rebar3 compile
===> Compiling amqp_client
===> Compiling /home/ferd/code/experiment/rabbitmq-erlang-client/_build/default/lib/amqp_client/src/amqp_gen_consumer.erl failed
/home/ferd/code/experiment/rabbitmq-erlang-client/_build/default/lib/amqp_client/include/amqp_client.hrl:20: can't find include lib "rabbit_common/include/rabbit.hrl" …
```
> Fix error reports on missing include paths

- src/rebar_prv_common_test.erl
- src/rebar_prv_eunit.erl
- test/rebar_ct_SUITE.erl
- test/rebar_eunit_SUITE.erl
when `ct_opts`, `eunit_tests`, `eunit_first_files`, `ct_first_files`, `erl_first_files`,
`eunit_compile_opts`, `ct_compile_opts` and `erl_opts` have values that are single non-list
terms warn and try wrapping them in a list when processing them in the `eunit` and `ct`
providers
before:
```
$ DEBUG=1 rebar3 ct
===> error: function_clause [{lists,sort,
[#Fun<rebar_utils.1.98462181>,export_all],
[{file,"lists.erl"},{line,963}]},
{rebar_utils,tup_umerge,2,
[{file,
"/home/travis/build/rebar/rebar3/_build/default/lib/rebar/src/rebar_utils.erl"},
{line,281}]},
{dict,update_bkt,4,
[{file,"dict.erl"},{line,319}]},
{dict,update_bkt,4,
[{file,"dict.erl"},{line,321}]},
{dict,on_bucket,3,
[{file,"dict.erl"},{line,409}]},
{dict,update,4,
[{file,"dict.erl"},{line,314}]},
{dict,fold_bucket,3, …
```
> warn on incorrectly specified test options in `rebar.config`

- bootstrap
- rebar.config
- rebar.lock
- src/rebar.app.src
- src/rebar_state.erl
Fix for https://github.com/rebar/rebar3/issues/933
> don't add a provider if the same namespace and name already exists

- src/rebar_opts.erl
- src/rebar_relx.erl
Relx config need new values at the end of the list and
profile additions prepended. So now in apply_profile in
the case it is a relx config we prepend the config list.
This does, however, mean that a profile release can not
'extend' a release defined in the default profile since
the one being extended would have its definition after
the profile release and thus relx would not be able to
use its values for extending.
Fixes https://github.com/rebar/rebar3/issues/936
> special handling of relx configs in profiles

- src/rebar_packages.erl
- test/rebar_pkg_SUITE.erl
Fix for https://github.com/rebar/rebar3/issues/939 and https://github.com/rebar/rebar3/issues/793
> auto-update the registry if a pkg isn't found, fail if it still isn't found

- src/rebar_prv_eunit.erl
Fixes my last changes so it properly recognizes: `{eunit_opts, [{eunit_formatters, false}]}.` for turning off the special eunit formatters.
> fetch eunit_formatters config not from the command args but from the config

- src/rebar_prv_eunit.erl
The previous default meant that verbose output would not be emitted, thanks to the custom formatter which doesn't seem to interact well with `verbose`.
I'm opening this now because I wanted to quickly fix this behavior, but I'm open to suggestions on how to improve the tests for this.
> Default to no eunit formatter if verbose specified

- src/rebar_erlc_compiler.erl
- test/rebar_compile_SUITE.erl
When compiling a dependency with a MIB file the generated hrl file is left in the root project directory in a file called "include". This has the perverse effect of messing up the search path for include files causing any dependencies with files in their "include" directory to fail to build after that.
> Fix a small bug in the MIB compiler when building dependencies

- src/rebar_utils.erl
- test/rebar_utils_SUITE.erl
- Add test cases for tuple deduplication
- proper segregation of comparison between tuple terms and non-tuple
terms. Guards weren't specific enough and that meant the wrong clauses
of guards would be triggered
- proper deduplication of entries in the list. An additional N passes
are required (we co-opt the reverse step to be more efficient) because
while the original lists:umerge easily removes dupes, this is
requiring more logic here since `[a,{a,b},{a,b,c},a,{a,b,c}]` is a
possible interleaving and we'd want `[a,{a,b},{a,b,c}]` -- comparison
of direct neighbours isn't enough, and we must keep the same sort
stability otherwise.
should fix and replace https://github.com/rebar/rebar3/pull/960
> Tup merge tests

- src/rebar_erlc_compiler.erl
- test/rebar_compile_SUITE.erl
this restores compatibility with rebar2 and erlang.mk
the fix is somewhat of a hackjob but without refactoring rebar_base_compiler pretty substantially there's no good way to pass the mib compiler the extra information it needs
> symlink mib hrl output in apps `include' directories

- src/rebar_app_utils.erl
- test/rebar_pkg_SUITE.erl
This patch makes the dependency handler treat a fuzzy match like `~> 1.0.0` in the same way it handles a package with no version given (pick the highest) and when a package from hex contains the fuzzy match. Nothing else changes, simply what version is picked to be in the lock file is given more flexibility. This will also allow us to fully support hex publishing in `rebar3_hex`.
> convert ~> versions to highest matching

- src/rebar_prv_common_test.erl
- src/rebar_prv_compile.erl
- test/rebar_ct_SUITE.erl
previously rebar3 dropped suites declared at the root of the project (via
`--suite=whatever_SUITE' probably) and warned. this was because the compiler
would recursively copy and compile everything in the directory indicated by
the test suite. this changes the copy mechanism to only copy erl source files
and directories that end with `_SUITE_data' into the `extras' dir in `_build'
> allow ct suites to be specified at root of project (or root of app)

- bootstrap
This allows rebar to pick up existing assets, if present:
- hex registry from .cache/rebar3/hex/default/registry
- built deps from _build/default/lib/*
@tsloughter, does this approach look good?
Rationale: this allows to build rebar3 in a build system, which requires it to be hermetic. This is the case for Debian (they are working on making their builds reproducible) and for Nix. I am working on Nix packaging for Erlang using rebar3 and hex.pm here:
https://github.com/NixOS/nixpkgs/pull/11651
Currently I have to apply the following patch to make it hermetic:
https://github.com/gleber/nixpkgs/blob/add-erlang-modules/pkgs/development/tools/build-managers/rebar3/hermetic-bootstrap.patch
And in the build rules I am manually providing plugins to build process: …
> Allow bootstrap to pick up existing Hex cache and deps

- priv/templates/otp_app.app.src
- priv/templates/otp_lib.app.src
hex.pm is now using maintainers instead of contributors in metadata.
Templates should be updated to reflect it.
> contributors -> maintaiers in template app data

- src/rebar_prv_compile.erl
if these directories actually exist they'll be added to the path ahead
of the release/standard distribution directories and they'll break eunit
and/or ct execution
> warn if the directories `eunit' or `ct' show up in `src_dirs'

- src/rebar_file_utils.erl
- test/rebar_eunit_SUITE.erl
- test/rebar_file_utils_SUITE.erl
This should fix #849.
Changes how robocopy does recursive directory copies, and normalizes some directory handling.
> Fix windows stuff

- src/rebar_app_utils.erl
- src/rebar_prv_install_deps.erl
- test/rebar_compile_SUITE.erl
Fix for https://github.com/rebar/rebar3/issues/998
When implementing this I discovered we actually were applying profiles to dependencies! This removes that mistake and only applies the `prod` profile to dependencies.
The reason we didn't notice is this only happened in `handle_dep` which would not be called for a dep when say `rebar3 eunit` is run because the dep was already fetched to `default`, so the `test` profile wouldn't be wrongly applied to it, it would only happen for test deps, which is still wrong and now won't happen.
> only apply default and prod profile to dependencies

- src/rebar3.erl
- src/rebar_plugins.erl
- src/rebar_prv_app_discovery.erl
- test/rebar_plugins_SUITE.erl
Fix for https://github.com/rebar/rebar3/issues/947
We were trying to install project app plugins before we discovered them. I changed that to just a top level config plugins install and moved the project app plugin install to after they are discovered.
> install project app plugins after discovering them not before

- rebar.config
- rebar.lock
cth_readable 1.2.0 uses cf 0.2.1 to output colors, which makes it
support dumb terminals without issue.
> Updates cth_readable so it supports dumb terminals

- src/rebar_prv_shell.erl
- src/rebar_user.erl
This is quite the hack.
This requires to detect the current shell running; if it's the new
shell, business as usual.
However, if it's the old shell, we have to find a way to take over it
and drive IO. This requires a few steps because:
- the old shell does not let you be supervised intelligently (it uses
supervisor_bridge, so killing the child is not a supported operation
from the supervisor)
- the old shell ignores all trappable exit signals except those coming
from the Port in charge of stdio ({fd, 0, 1})
- the old shell shuts down on all exit signals from the stdio Port
except for badsig, and replicates the shutdown reason otherwise
- An escript does not tolerate the `user` process dying (old shell) for
any non-normal reason without also taking the whole escript down
- Booting in an …
> Support old-style shell for rebar3 shell

- src/rebar_prv_eunit.erl
`beam_lib:chunks(..)` needs a path to object code which, frustratingly,
`code:which/1` won't return for cover compiled modules. instead just
assume that if `code:which/1` doesn't return `non_existing` a module
is something we can run tests on
fixes #1014
> change detection of valid modules for `eunit`

- rebar.config
- src/rebar_utils.erl
this is slower than the compile time check but i guess packaging rebars with
repos is still a thing and i think only the `eunit` and `ct` providers call it
anyways
fixes #1004
> check at runtime instead of compile time for `file:list_dir_all/1`

- src/rebar_prv_shell.erl
If a bad configuration file is submitted to rebar3 shell, display the
following error:
===> The configuration file submitted could not be read and will be
ignored.
And keep going otherwise rather than silently failing.
While crash-fast is usually a good mechanism, the shell so far is very
tolerant of failures from apps to boot and whatnot, so this feels
appropriate.
Fixes #1019
> Display error message when bad config is loaded

- CONTRIBUTING.md
- README.md
- The README is better targetted to newcomers and explains the basics of
the project: what it is, why use it, how to get started, where to find
more information. It looks less like a reference and more like a brief
overview of rebar3.
- Whatever looks like a list or reference manual material is expected to
be moved to the website
- Be clearer about the rebar3 project structure in CONTRIBUTING.md;
explain how to write tests, how to structure code, and so on.
- Added contributing section on bug reports, feature requests, etc.
Fixes #1020
> Rework README and CONTRIBUTING documents

- README.md
- src/rebar_prv_local_install.erl
- src/rebar_prv_local_upgrade.erl
This PR moves `unstable install` and `unstable upgrade` to the `local` namespace and adds an optional env var `REBAR3_ERL_ARGS` to allow setting custom VM args when running `rebar3`.
> local install and local upgrade

- src/rebar_prv_eunit.erl
- test/rebar_eunit_SUITE.erl
this ONLY attempts to deduplicate test sets that are generated by
rebar in the absence of any user specified tests
this closes #937
> deduplicate default test set generated by `rebar3 eunit`

- src/rebar_prv_clean.erl
- test/rebar_as_SUITE.erl
Note that this isn't about being easier to use or less typing than using `as` it is simply about discoverability.
Closes https://github.com/rebar/rebar3/issues/972
> add profile option to clean task

- src/rebar_erlc_compiler.erl
- test/rebar_compile_SUITE.erl
Several projects use an include path relative
to the project's root.
file:compile will look in three places for the include
files:
The current working directory
The directory where the module is being compiled
The directories given by the include option
> Add module directory to include path

- src/rebar_prv_common_test.erl
- test/rebar_ct_SUITE.erl
this ensures the project apps are compiled to `lib/` instead of `extras/`
> don't strip the project apps when running `ct` with just a root suite specified

- src/rebar3.erl
Fix for https://github.com/rebar/rebar3/issues/871
> check top level config for minimum or blacklisted  otps at start

- test/rebar_release_SUITE.erl
- test/rebar_test_utils.erl
This is a test case for validation against #1036, so it's failing right now.
It also exposes erlware/relx#335, to reproduce it run the test then enter the directory where the test fixtures were generated to and generate the release again, if run multiple times it will fail with the 
```
badmatch,{error,enoent}},
[{rlx_prv_assembler,rewrite_app_file,2,
```
error every other time.
This is relx erroring out because it's trying to rewrite OTP's kernel .app file which is not present, it seems to be copied in one run and deleted in the next, this accounts for it failing every other time
Makes use of several var types: integers,
strings, binaries, binary strings and tuples.
> Add test case for relx overlay vars

- src/rebar_prv_compile.erl
erlc_compile, for before/after compiling .erls to .beams, but before .app.src to .app
After discussing #1044 some on IRC with @tsloughter and @talentdeficit, we concluded something in this form would be viable.
My understanding is that it was originally intended for providers to have only two hooks: pre and post. However, the ability to define arbitrary hook points allows for greater flexibility with respect to scoping out the responsibilities of a given provider. We arguably shouldn't need to separate two closely related operations into different modules just so we can put hooks in between them.
The more I think about this, though, the less certain I am that there is an "optimal" solution. It feels dirty to be adding a "provider hook" for something that's not really a provider. Maybe …
> Add secondary hook for rebar_prv_compile

- rebar.config
- rebar.lock
Includes changes to relx to support cuttlefish. Mainly that you can now set `sys_config` and `vm_args` to `false` to tell relx not to create defaults. 
Also a bug fix when building a tarball with no `sys.config` or `vm.args`.
> upgrade relx to 3.17.0

- src/rebar_prv_install_deps.erl
- src/rebar_prv_upgrade.erl
Without this change there was sort of confusing output any time you ran `upgrade` because it had the same entry point as the provider:
```
...
```
> break up do/1 function in install_deps to make upgrade less confusing

- src/rebar_app_info.erl
- src/rebar_config.erl
- src/rebar_prv_lock.erl
- src/rebar_prv_unlock.erl
- src/rebar_state.erl
- test/rebar_lock_SUITE.erl
Changes to how hex or packages may work in the future will necessarily
bring changes to the format of lock files.
This commit adds an optional framing for future lock files of the form:
{Version, LockList}.
<Whatever consultable attributes>
This format is supported such as the LockList is the current lockfile
contents, and will never have more information than it currently does.
Attributes can be whatever and are currently undefined.
Rebar copies will be able to:
- Keep using the core locklist (which avoids breaking the last year or
so of community libraries using rebar3)
- Warn when it runs an outdated copy in comparison to the lock file
- Automatically rewrite lock files in the format it supports
- Augment or parse files in a version-specific manner.
This changes the usage interface …
> Make lock files future-proof

- src/rebar3.erl
- src/rebar_plugins.erl
- src/rebar_state.erl
This change allows top level plugins to take the names of default providers. For example, the cuttlefish plugin, which requires control over the release building, will be `{default, release}` and `{default, tar}` in order to make this possible.
> give top level plugin providers precedence over default providers

- src/rebar3.erl
- src/rebar_plugins.erl
- src/rebar_state.erl
- test/mock_git_resource.erl
- test/rebar_plugins_SUITE.erl
- test/rebar_test_utils.erl
Providers weren't initialized deps of plugins like cuttlefish would fail to build since there was no `escriptize` provider at the time of build.
> add project_providers after initing default providers but allow overrides

- src/rebar_packages.erl
- src/rebar_prv_update.erl
- test/rebar_deps_SUITE.erl
- test/rebar_pkg_SUITE.erl
Add: `==`, `>=`, `>`, `<` and `<=`
> Hex improvements

- rebar.config
- rebar.lock
The new version fixes parse transforms over OTP incompatibility that
would crash entire compile runs before.
Fixes https://github.com/rebar/rebar3/issues/1063
> Bump cth_readable

- src/rebar_hooks.erl
- src/rebar_prv_common_test.erl
- src/rebar_prv_eunit.erl
- src/rebar_relx.erl
- test/rebar_hooks_SUITE.erl
Fixes https://github.com/rebar/rebar3/issues/1089
Issue is that some providers, like `compile` and `clean`, distinguish between top level hooks and per-app hooks. in order to keep them from running twice we remove the hooks from the top level State if it is a single top level app in the project (the hook stays with the app). But in the case of `eunit` and `ct` and `relx` these per-app hooks are not run. To fix this I have it now run all hooks for those providers. I think that is the proper fix but open to alternatives.
> Run all hooks

- src/rebar_prv_common_test.erl
- test/rebar_ct_SUITE.erl
The idea is that given we accept arbitrary config items for CT, we
should similarly be able to pass unsupported options and keep things
running.
However for unsupported options, a warning is very useful to have.
CC @talentdeficit
> Take CT options errors and turn them to warnings

- src/rebar3.erl
- src/rebar_prv_common_test.erl
- src/rebar_prv_eunit.erl
- test/rebar_ct_SUITE.erl
- test/rebar_eunit_SUITE.erl
- test/rebar_profiles_SUITE.erl
with this change 'EUNIT' will only be set when running the eunit provider and 'COMMON_TEST' will be set by the ct provider. this does mean users that run both eunit and ct tests will see a recompile when alternating between the two test runners
> make omar happy

- src/rebar_prv_shell.erl
Following suggestions from @psyeugenic, this code terminates and waits
for the termination of the port handling IO before booting our own,
which should get rid of annoying warnings.
We also allow for the failure to shutdown the user worker under
kernel_sup, since it is likely not there anymore in many scenarios,
preventing crashes.
Tested on linux and OSX under escript and local install, with and without TERM=dumb. Windows testing still required.
Should fix https://github.com/erlang/rebar3/issues/1028
> Fix bugs/race conditions in shell

- src/rebar_prv_path.erl
By default, the dependency only handled versioned packages and top-level
source dependencies, and locks were being ignored.
This patch makes it so locks and package deps are being considered,
generating full-blown path lists.
Should fix #1117
> Support all deps & locks in rebar3 path

- README.md
The name changed in the move. This should fix the build status thingy.
> Fix Travis build status image in readme

- .travis.yml
With this change we can update the website to have the stable version number of the download. I think we don't need 'nightly' and people who need that can build from source.
I think we are also due for a 3.1.0 release, right?
> change travis config to only upload escripts for tags (stable releases)

- src/rebar_dist_utils.erl
- src/rebar_prv_shell.erl
- test/rebar_dist_utils_SUITE.erl
This commit moves the handling of distribution config and starting out
of rebar_prv_shell and into rebar_dist_utils. The module is able to
handle standard config options and boot a distributed node mode. This
could be used in plugins (once it is exposed) and other providers like
CT.
Configuration is also expanded so that options like:
{dist_node, [{sname, atom()}, {name, atom()}, {setcookie, term()}]}
can be used and will be handled as a default. The config handler
supports similar terms from the command line being parsed in if the
calling provider supports them.
A test suite is added for configuration handling.
---- 
This is open for comments in how to handle the options or how to name them.
> Extract dist config handling, support {dist_node, ...}

- src/rebar_git_resource.erl
I've tried to compile project with git in .app.src vsn
Project was tagged as 1.0.0, but resulting .app vsn becomes 1.0.0+build.6.reff0aec24
```
$ git lg
* f0aec24 - (80 minutes ago) Fixed ct — Kozlov Yakov (HEAD -> master, tag: 1.0.0, origin/master)
... 5 commits before
```
```
$ git log --oneline --no-walk --tags --decorate
f0aec24 (HEAD -> master, tag: 1.0.0, origin/master) Fixed ct
```
I've found that `HEAD -> master` doest match pattern in [rebar_git_resource](https://github.com/erlang/rebar3/blob/master/src/rebar_git_resource.erl#L204)
> Fixed git version bug

- src/rebar_agent.erl
When an app contains one of the modules we can't afford to get upgraded
without breakage (i.e. erlware_commons, providers, getopt), skip
reloading that application from the rebar3 agent, such that it can keep
on working in subsequent calls.
Blacklisted:
- erlware_commons (broke on ec_cmd_log)
- providers (core to functionality)
- cf (useful to not explode on colors)
- cth_readable (only used for CT suites, but incompatibilities may break
whole runs)
> Blacklist apps to reload

- src/rebar_prv_common_test.erl
- src/rebar_prv_eunit.erl
If we try to use the ct_slave in `rebar3 ct`, net_kernel:start is required each time.
In rebar2 it was not that necessary.
I want that the setting of dist_node is applied to ct and eunit.
> supported dist_node in ct and eunit

- src/rebar_prv_shell.erl
Somehow swapping the tty handler once more fixes everything. I guess we
were missing a step somehow.
Probably fixes #768
> Fixes logging from remote shells in rebar3 shell

- src/rebar3.erl
- src/rebar_dir.erl
- test/rebar_dir_SUITE.erl
Allows overwrite the default cache directory using the environment variable REBAR_CACHE_DIR.
There's some discussion about this in https://github.com/erlang/rebar3/issues/1116
> Allows overwrite default cache dir using REBAR_CACHE_DIR

- src/rebar_prv_shell.erl
When using rebar3 shell, the `rebar_agent` process started from `init` never ends (in order to process shell commands with `r3:do/1`), but the init process keeps waiting forever in `'starting'` state. Applications like riak_core refuse to start in this situation.
A possible workaround is using `sys:terminate(rebar_agent, normal)` right after start, but of course you are not able to use the agent any more.
This is a quick and dirty fix to fool the init process into thinking we have stopped and the normal node starting process can go on. Of course a 'final' solution should be more elegant... maybe starting rebar_agent as an independent process?
> Fix shell node startup

- src/rebar_prv_cover.erl
- test/rebar_cover_SUITE.erl
closes #1057 and #1179 
this is technically a breaking change but i think most people would say including test suites in coverage is a bug. it could be gated behind an option if anyone disagrees tho
> don't generated coverage for `extra_src_dirs`

- src/rebar_prv_update.erl
Fix for https://github.com/erlang/rebar3/issues/1200
> filter available package versions individually by buildtools

- src/rebar_git_resource.erl
sry for opening the same PR twice couldn't figure out how to rebase; I think I went too far to fix/didn't understand how to do it. (Still learning git)
Debug log(s) was showing the following: 
```
===> 	opts: [{use_stdout,false},
{debug_abort_on_error,
[76,111,99,107,105,110,103,32,111,102,32,103,105,
116,32,100,101,112,101,110,100,101,110,99,121,32,
102,97,105,108,101,100,32,105,110,32,
"/home/...../_build/default/lib/recon"]}]
```
The PR is to make it human readible and result in the following. 
`"Locking of git dependency failed in /home/..../_build/default/lib/bear"
`
> Debug log update

- src/rebar_app_utils.erl
- src/rebar_config.erl
This adds support for their format both on the first read and when
looking for modifications to dependencies.
> Don't die when source deps with [raw] are used

- src/rebar3.erl
Formatted errors can accidentally contain substrings which are control
sequences for io:format/2. This is a naive attempt to handle such cases.
One example is running xref on the following module
(assuming module m does not exist)
```
-module(handle_error).
-export([f/0]).
f() -> m:'bobby~stables'().
```
```
$ rebar3 xref
===> Compiling myapp
===> Running cross reference analysis...
escript: exception error: bad argument
in function  io:format/3
called as io:format(<0.23.0>,
"\e[0;31m===> \e[1mWarning: handle_error:f/0 is unused export (Xref)\nWarning: handle_error:f/0 calls undefined function m:bobby~stables/0 (Xref)\n\n\e[0m\e[0m",
[])
in call from rebar3:handle_error/1 (/Users/gomoripeti/git/rebar3/_build/default/lib/rebar/src/rebar3.erl, line 279)
```
> Handle control sequences in formatted errors

- src/rebar_prv_upgrade.erl
- test/rebar_upgrade_SUITE.erl
When the operation for an unlock takes place in the config of a umbrella
application, the `unlock` provider does not see the dependency in the
`deps` value of the config (since it only includes the deps at the root
of the project) and ignores these.
Ref: #1193
> Bugfix for upgrading deps of umbrella apps

- src/rebar_prv_cover.erl
Dependent libs is required for some module when cover compiling.
So all dependencies should be available on code path.
This fixes #1148 issue.
This P/R also fixes #1149 test fails on travis (maybe, in my case, tests is all  ok.)
> Fix compile error case when cover compilation

- src/rebar_utils.erl
- test/rebar_deps_SUITE.erl
- The configured stuff in rebar3 takes precedence over the ENV
- The env is then chosen
fixes #1228
> Support ENV config for proxy values

- src/rebar_file_utils.erl
- src/rebar_prv_common_test.erl
- src/rebar_prv_shell.erl
- src/rebar_utils.erl
- test/rebar_ct_SUITE.erl
Follows the same pattern as `shell` to set env variables for applications from a config file but in this case for the common test provider.
Examples:
```
$ rebar3 ct --sys_config=config/sys.config
```
In `rebar.config`:
```
{ct_opts, [{sys_config, ["config/sys.config"]]]}
```
> add support for passing a sys_config to common test

- src/rebar_base_compiler.erl
- src/rebar_erlc_compiler.erl
- src/rebar_file_utils.erl
- test/rebar_file_utils_SUITE.erl
Supercedes https://github.com/erlang/rebar3/pull/1174 with the fixes on config name.
> Compiler source paths in output are now relative

- src/rebar_base_compiler.erl
- src/rebar_erlc_compiler.erl
- src/rebar_file_utils.erl
- test/rebar_file_utils_SUITE.erl
By default rebar3 displays compiler sources as absolute paths in their
original location, which is under the build dir.
This change introduces an option 'compiler_source_format' to format
sources in two alternative ways:
relative
absolute
When either 'relative' or 'absolute' are specified, the file is
resolved to its original location when it is a link. When 'relative'
is specified, the path is displayed relative to the current working
directory. When 'absolute' is specified, the path is absolute.
The default value is 'unchaged' which leaves the compiler source
unchanged.
This is arguably too flexible as I suspect most people would opt for
'relative' all the time - it's the most compact representation of the
file and is sufficient to find the source given cwd. The change
however is meant …
> Option to format compiler sources

- src/rebar_erlc_compiler.erl
- test/rebar_compile_SUITE.erl
changed include files were not properly picked up by `erlc_compiler`
in cases where they were in directories relative to the application
source and not the current working dir of rebar3
fixes #1199
> normalize include dirs to absolute paths during compilation

- src/rebar_prv_shell.erl
i think this is correct, but i didn't think too hard about it. it fixes this tho:
```erlang
Eshell V7.3  (abort with ^G)
1> ===> No script_file specified.
===> Found shell apps from relx.
===> Found config from relx.
===> Loading configuration from "/Users/talentdeficit/dev/erlang/myapp/config/sys.config"
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump
===> Uncaught error: {badmatch,[]}
===> Stack trace to the error location: [{rebar_prv_shell,
maybe_boot_apps,1,
[{file,
"/Users/talentdeficit/dev/erlang/rebar3/_build/default/lib/rebar/src/rebar_prv_shell.erl"},
{line,268}]},
{rebar_prv_shell,shell,1,
[{file,
"/Users/talentdeficit/dev/erlang/rebar3/_build/default/lib/rebar/src/rebar_prv_shell.erl"},
{line,107}]},
{rebar_prv_shell,do,1, …
```
> ignore return value of `rebar_utils:reread_config` in shell provider

- src/rebar_prv_deps_tree.erl
As I mentioned back here https://github.com/erlang/rebar3/pull/867#issuecomment-147767501 ,
"the unicode vertical box-drawing character on line 73 needs the same treatment".
This fixes the issue (#1140).
> Fix unicode rendering of deps tree (issue #1140)

- src/rebar3.erl
Setting DEBUG/QUIET environment variable to the empty string now acts
the same as unsetting it. Unsetting is not always easy/possible.
Slight backwards incompatibility here, but the previous behavior wasn't
"principle of least surprise".
> Let DEBUG="" and QUIET="" mean disable the option

- src/rebar_prv_dialyzer.erl
- test/rebar_dialyzer_SUITE.erl
Handle the situation where we build an empty PLT or try to analyse an empty app. Either of these might be a fix for #1261.
I also reworded the building message so it is possible to tell the difference between building and adding.
> Handle empty PLT or app when using dialyzer

- rebar.config
- rebar.lock
To use the default cookie of a linux machine rather than having to set it in the vm.args.
Only change from 3.19 was [RelX PR](https://github.com/erlware/relx/pull/488/commits)
> Relx upgrade to version 3.20.0

- src/rebar_base_compiler.erl
rebar_base_compiler allows to be called with two types of options: a
dictionary, or a rebar_state record. In the later case, the options are
taken out with a call from rebar_opts, which fetches options that have
been inserted in the application via rebar_app_info as part of the
app_discovery phase, and are a list.
This yields a possibility that options used when formatting warnings can
either be a list of a dict, and we only used lists when making checks.
This ended up breaking 3rd party compiler users (i.e. LFE compile
plugin) since they were calling us with a dict rather than our own
internal records.
This patch supports both types of lookups to avoid issues.
> Fix opts check when compiler called with dict opts

- src/rebar_prv_dialyzer.erl
**VERSION**
```
$> ./rebar3 version
rebar 3.2.0 on Erlang/OTP 18 Erts 7.3.1
```
**WHY**
when running `DEBUG=1  rebar3 dialyzer`, I got following error:
```
...
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump
===> Uncaught error: {case_clause,{error,not_valid}}
===> Stack trace to the error location: [{rebar_prv_dialyzer,read_plt,
2,
[{file,
"/home/gbour/DEVEL/erlang-rebar3/_build/default/lib/rebar/src/rebar_prv_dialyzer.erl"},
{line,253}]},
{rebar_prv_dialyzer,
update_base_plt,4,
[{file,
"/home/gbour/DEVEL/erlang-rebar3/_build/default/lib/rebar/src/rebar_prv_dialyzer.erl"},
{line,364}]},
...
```
the reason was $HOME/.cache/rebar3/rebar3_18.3.4.1_plt was empty.
`dialyzer:plt_info()` is returning  **{error, not_valid}** tuple, which is not …
> fix catching  `not_valid` error on dialyzer

- src/rebar_prv_escriptize.erl
- test/rebar_escriptize_SUITE.erl
When rebar.config contains a `escript_main_app` option, but the specified app doesn't exist in the build directory, print an error instead of crashing.
I reused the `bad_name` error, but I'm not sure if that's good or if it would be better to make a new error.
Also adds a pair of tests for the `escript_main_app` option.
> Handle `escriptize` when the specified app is missing

- src/rebar_prv_escriptize.erl
https://github.com/erlang/rebar3/pull/1249 introduced a mechanism by
which escript dependencies of applications only would be included; this
required adding a filter to skip system libraries in the OTP root
because that tends to break escripts in very nasty ways.
However, the problem came that some libraries are just not in the
escript path but may still be included; for these libraries the path
prefix check failed as they return `{error, bad_name}` from
`code:lib_dir(Dep)` rather than just the path they're in --
specifically, this happens with top level apps.
The issue was reported in https://github.com/erlang/rebar3/issues/1294
and the current patch fixes it by accepting a `bad_name` dep as valid,
since it is obviously not in the root path.
> Fix filtering of system libraries in escriptize

- rebar.config
- src/rebar_prv_escriptize.erl
Resolves https://github.com/erlang/rebar3/issues/1223 and adds a hook for non-windows systems:
- ./bootstrap  9.95s user 1.55s system 102% cpu 11.234 total
- rebar3 escriptize  0.49s user 0.14s system 101% cpu 0.623 total
> Hookable escript

- src/rebar_prv_help.erl
Previously the help task would crash when given more than two
arguments. After this change it instead print a message:
Too many arguments given. Usage: rebar3 help [<namespace>] <task>
> Print error on too many help arguments

- src/rebar_app_utils.erl
The trim_all option used in binary:split/3 is not supported in 17.x.
This patch makes an equivalent operation by eliminating empty split
fragments. From the docs:
trim
Removes trailing empty parts of the result (as does trim in
re:split/3.
trim_all
Removes all empty parts of the result.
The new expression is therefore equivalent to the old one, but with the
added benefit of compatibility.
Fixes #1275
> Equivalent trim_all in bin split for <17.x

- rebar.config.sample
- src/rebar_prv_cover.erl
Add config option to ignore certain modules from the cover.
```erlang
{cover_excl_mods, [
statsderl_profile,
statsderl_tests,
statsderl_utils_tests
]}.
```
If I add tests, would this be accepted?
> Add support for cover_excl_mods

- src/rebar_app_utils.erl
Specifically, when fetching an application where the expected hash is
unknown, the hash is validated from the hex index; when the index is
available, the hash is fetched fine and later inserted in the lock file.
However, if the index is not available, the call would simply crash.
This patch fixes thing so that instead, the index is refreshed before
giving up and failing.
Should fix #1313
> Fix crash when doing hash check with missing index

- src/rebar_prv_cover.erl
- test/rebar_cover_SUITE.erl
this prevents provider chains like `eunit, ct, proper` from misreporting cover
stats from providers later in the sequence
> reset accumulated coverdata on writing out to disk

- src/rebar3.erl
Insert a newline before printing the stacktrace so that the term is
easier to read and copy. This is a more conventional way to print
traces, and is, for instance, the way it's done by make and python.
> Print stacktrace in a more conventional way

- src/rebar_agent.erl
In reference to https://github.com/erlang/rebar3/pull/1317, support load erlang code atomically but load nifs non-atomically.
> Atomically load changed erlang modules. Non-atomically load nifs. Reference to https://github.com/erlang/rebar3/pull/1317 

- src/rebar_file_utils.erl
- test/rebar_file_utils_SUITE.erl
Fix #1324.
In some cases, mv will throw a warning, while still moving the files correctly and returning a 0 return code:
"mv: can't preserve ownership of ... Permission denied".
> Prevent crashing when `mv` warns and report warnings to the user instead.

- src/rebar_agent.erl
This should log if a module failed to load for whatever reason. 
Pretty important for the user to be aware if this ever happens on compile so they don't pull their hair out trying to figure out whats wrong.
Can someone review this if using ?ERROR macro is correct here?
> log error if a module failed to load_file, the user should be aware

- src/rebar_prv_cover.erl
the `cover` tool relies on having cover compiled versions of the modules to be analyzed in order to generate accurate coverage
fixes #1327
> compile + cover compile prior to analyzing coverdata

- src/rebar_erlc_compiler.erl
- src/rebar_prv_xref.erl
- test/rebar_xref_SUITE.erl
At @inaka, sometimes we implement behaviours but sometimes we implement _behaviors_, because we like to live on the edge (o_O).
rebar3 uses behaviours to determine which modules to compile first and it also treats them nicely when running xref. This PR adds support for doing the same things with _behaviors_.
> Add support for behaviors, and not just behaviours

- src/rebar_erlc_compiler.erl
- test/rebar_compile_SUITE.erl
When an include file is set in a private path (i.e. src/), the rebar3
compiler would not add them to the {i, Path} params -- only include/ and
the project root were being added.
This meant that when some extra source directories were added to the
compile job, such as test/ when running under the test profile, the
private include paths could not be shared with the test module.
This patch fixes the issues (and adds tests) for such a specific case by
adding all the configured include paths to the {i, Path} erl_opts
arguments, yielding successful compile runs.
Discussed in https://github.com/ferd/rebar3_proper/issues/8
> Fix private includes when compiling in test profile

- src/rebar3.erl
erlang:get_stacktrace() gets the last stacktrace, regardless of where it was caught, so it is not wise to call it multiple times.
> Fix stacktrace printing in DEBUG=1 mode. Fixes #1347.

- src/rebar_prv_update.erl
- test/mock_pkg_resource.erl
- test/rebar_deps_SUITE.erl
- test/rebar_pkg_alias_SUITE.erl
Aliasing only had a bit of ad-hoc support in rebar3, and various issues
have encountered problems related to the package names not mapping
properly with the application name. One such issue is
https://github.com/erlang/rebar3/issues/1290
The problem has been hard to find because it only impacts transitive
dependencies (not top-level ones) of other packages. The root cause for
this is that the application name was not being tracked by rebar3's internal
index, only the package name and its version were.
When a given application was a package app, the data for the application
name would be reconstructed from the lock file, but only if it were a
top-level app or a dependency of a source application where parsing the
lock file is necessary to know what comes next.
When a transitive dependency …
> Properly support package aliasing and alt names

- src/rebar_prv_as.erl
- test/rebar_as_SUITE.erl
checks on hd(...) and so on could not handle empty lists.
solves https://github.com/erlang/rebar3/issues/1354
> Prevent crashes in `rebar3 as` with no tasks

- src/rebar_prv_common_test.erl
- test/rebar_ct_SUITE.erl
`rebar3 ct --spec foo.spec,bar.spec,baz.spec` now works
also added support for the `join_specs` flag on the command line
> experimental: allow test specifications to be passed via the command line

- src/rebar_prv_help.erl
A very small fix of rebar3 usage description (`rebar` -> `rebar3`):
```
$ rebar3 help
Rebar3 is a tool for working with Erlang projects.
Usage: rebar [-h] [-v] [<task>]
...
```
```
$ rebar3 help
Rebar3 is a tool for working with Erlang projects.
Usage: rebar3 [-h] [-v] [<task>]
...
```
> Fix usage decription of 'rebar3'

- src/rebar_prv_dialyzer.erl
- test/rebar_dialyzer_SUITE.erl
Closes #1367. Use app/mod names instead of regex. Also allows excluding whole applications and then adding a subset of their modules. Note that this makes it possible to have profiles with project apps in the PLT and will fail on ambiguous cases. I think this also clears up the code for what gets added to PLT/analysis.
* exclude_apps - never use applications for PLT/analysis
* base_plt_mods - add modules to base PLT (overrules exclude_apps)
* plt_extra_mods - add modules to PLT (overrules exclude_apps)
* exclude_mods - never use modules for PLT/analysis (overrules all)
> Add exclude_apps/mods, plt_extra_mods, base_plt_mods config

- src/rebar_erlc_compiler.erl
- src/rebar_file_utils.erl
makes it easier to at least test edoc improvements if the project itself passes.
> Allow rebar3 to edoc itself

- src/rebar.hrl
- src/rebar3.erl
- src/rebar_config.erl
> Always read REBAR_CONFIG env var when loading config

- src/rebar_packages.erl
This is to fix the following bug:
```
$ DEBUG=1 rebar3 upgrade
===> Load global config file /Users/waisbrot/.config/rebar3/rebar.config
===> Expanded command sequence to be run: [{default,app_discovery},
{default,install_deps},
{default,lock},
{default,upgrade}]
===> Evaluating config script "/Users/waisbrot/git/webhooks-hub/_build/default/lib/dogstatsd/rebar.config.script"
===> Evaluating config script "/Users/waisbrot/git/webhooks-hub/_build/default/lib/erlcloud/rebar.config.script"
===> Evaluating config script "/Users/waisbrot/git/webhooks-hub/_build/default/lib/jsx/rebar.config.script"
===> Evaluating config script "/Users/waisbrot/git/webhooks-hub/_build/default/lib/dogstatsd/rebar.config.script"
===> Evaluating config script …
```
> Unify different styles of missing_package error

- src/rebar_dir.erl
- src/rebar_erlc_compiler.erl
- src/rebar_prv_eunit.erl
- test/rebar_compile_SUITE.erl
- test/rebar_dir_SUITE.erl
This pull request adds the option {recursive,boolean()}, indicating whether or not rebar3 should search recursively for source files to compile. The options can be set on two levels:
top level - sets the default for the project: 
` {erlc_compiler,[{recursive,boolean()}]}.`
per source directory:
`{src_dirs,[{"src",[{recursive,boolean()}]}]}.`
`{extra_src_dirs,[{"test",[{recursive,boolean()}]}]}.`
The variants are chosen after the discussion in [issue #1345](https://github.com/erlang/rebar3/issues/1345).
This feature is needed for testing of split-out applications from erlang/OTP, where data dirs (*_SUITE_data) in test contain .erl files that must not be compiled by rebar3. Reasons for this can be
a) the files should not be compiled at all, e.g. because the test suite operates on the .erl …
> Add 'recursive' option

- src/rebar_opts.erl
- test/rebar_profiles_SUITE.erl
Addresses https://github.com/erlang/rebar3/issues/1397
Ensures merged compiler options end up in the correct order to maintain profile precedence.
Moves the merge functionality from rebar_opts:merge_opts/2 to a standalone function to ease extension and debugging.
> Correct precedence of compile options merged from profiles.

- src/rebar.app.src
- src/rebar_prv_get_deps.erl
a no-op provider that depends on lock that is slightly more discoverable and user friendly
> add `get-deps` provider

- src/rebar_base_compiler.erl
- src/rebar_erlc_compiler.erl
- src/rebar_prv_eunit.erl
- src/rebar_templater.erl
The regex mistakenly matched too many files (any character followed by
an underscore) rather than only files starting in '._'
This properly escapes the expressions to work in all cases.
Fixes #1410
> Fix regex match for ignored file

- src/rebar_prv_shell.erl
Like for instance: {app, "0.1.0", '='}
> shell: don't crash apps that use release version operators

- src/rebar_prv_eunit.erl
this pr makes the eunit provider file ending agnostic to allow for use with lfe/elixir/alpaca and refines the deduplication of test modules to ignore modules that are part of the application being tested
> refine eunit test detection

- src/rebar_prv_common_test.erl
- test/rebar_ct_SUITE.erl
Bug: option 'spec' is not specifically handled when merging options
from the command line with options from rebar.config. Due to this, if
the config specifies a 'spec', then this will take precedence over any
'dir' and/or 'suite' on the command line.
This commit takes special care of all options that can be used to
select tests - meaning that if any of the options 'spec', 'dir',
'suite', 'group' or 'case' are specified on the command line, then all
'spec', 'dir', 'suite', 'group' and 'case' options in rebar.config
will be ignored.
See also https://github.com/erlang/rebar3/issues/1389
> Improve merge of command line options and config options in CT

- rebar.config
- rebar.lock
fixes erlware/relx#553 which prevents people from running long node name releases, we should also cut a new rebar3 patch release as this will probably impact a lot of people
> Bump relx to 3.22.1

- src/rebar_prv_shell.erl
This patch makes it possible for other beam languages, like alpaca, to specify the shell. Example can be seen in https://github.com/alpaca-lang/rebar_prv_alpaca/blob/shell/src/rebar_prv_alpaca_shell.erl#L56 which uses https://github.com/lepoetemaudit/alpaca-repl/blob/master/src/alpaca_shell.erl
> add option to pass args to user_drv for custom shells

- .editorconfig
Notes:
- Tested with Sublime Text Editor. (http://editorconfig.org/#download)
- Changed .editorConfig to .editorconfig for consistency. Since Sublime on Linux wasn't picking up the config file.
- Added [skip ci] since no actual changes to the code base are being made.
- EditorConfig Website: http://editorconfig.org/
- Let me know if I missed anything! :smile: 
https://github.com/erlang/rebar3/issues/1443
> [FEATURE] Add .editorconfig Settings.

- README.md
I'm no English expert here. So feel free to close this pull request if I'm mistaken, just following a rule of thumb. "Hyphenate two or more words when they come before a noun they modify and act as a single idea." 
Also "In case of problems" doesn't sound right. I think the proper wording is "In the case of ...".
Again, correct me if I'm wrong.
> Fixed missing hypens, and improper wording in README.md

- src/rebar.hrl
- src/rebar_base_compiler.erl
- src/rebar_dialyzer_format.erl
- src/rebar_dir.erl
- src/rebar_prv_dialyzer.erl
1.  Extract code path formatting out of compiler: this allows to reuse the code for any provider that formats source files out to the user, without worry of introducing new weird bugs. The option to configure it does remain compiler-centric for backwards compatibility.
2.  Enable path reformatting for Dialyzer
It may break backwards compat with projects that manually called the dialyzer formatter out of rebar3, but we never documented or expected this to be exposed so I'm not too worried about the risk.
Before:
```
===> Analyzing 8 files with "/home/ferd/code/self/shunk/_build/default/rebar3_18.1.5_plt"...
_build/default/lib/shunk/src/shunk_tcp_client.erl
24: Invalid type specification for function shunk_tcp_client:diff/2. The success typing is (atom(),port()) -> 'todo'
43: Function …
```
> Relative dialyzer paths

- src/rebar_file_utils.erl
- test/rebar_file_utils_SUITE.erl
This is due to a stall a bunch of tests in appveyor and on windows in general.
Turns out a bunch of semantics for file moving were flat out wrong and different between windows and POSIX. This PR adds a bunch of tests for the expected behaviour that I roundtripped between a windows10 and a linux computer to make sure they agree on the behaviour and that it works the same.
There's some ugly stuff there, such as `xcopy` not handling long paths properly, forcing us to move to `robocopy`, which does not allow renaming as part of moving a file. This requires using temporary directories to rename files as an intermediary to avoid clobbering.
For directories this isn't a problem, but the `mv` behaviour has to be replicated still because it is not the default on windows with robocopy.
> Fix `mv` on windows

- src/rebar_prv_new.erl
- src/rebar_templater.erl
When the `new` command is run from a locally installed rebar3 (`rebar3
local install`), the builtin templates would be labelled as custom
because of directories.
This patch fixes it by splitting off the rebar3 priv dir from the user's
configured plugin path for custom ones, and introducing a new internal
label for builtins (since handling must remain different from escripts)
This fixes issue #819
> See template local install same builtin as escript

- src/rebar_erlc_compiler.erl
- test/rebar_compile_SUITE.erl
on 19.x forward the compiler should now take into consideration the value
of the environment variable `ERL_COMPILER_OPTIONS` when deciding whether
or not to recompile a module
> consider `ERL_COMPILER_OPTIONS` when recompiling

- test/rebar_compile_SUITE.erl
Fixes #1412
@talentdeficit this doesn't check all regexes -- the base compiler, eunit, and templater are ignored, but it captures it in the compiler. I think this might be enough.
> Add regression test for #1410

- THANKS
- src/rebar_prv_cover.erl
- test/rebar_cover_SUITE.erl
Adds a new option `{cover_excl_apps, Apps}` to exclude apps from coverage
analysis by name.
> Allow exclusion of apps in cover

- src/rebar_prv_eunit.erl
> catch badarg exception from eunit in `rebar_prv_eunit`

- src/rebar_app_discover.erl
- src/rebar_app_info.erl
- src/rebar_prv_plugins.erl
- test/rebar_src_dirs_SUITE.erl
This lets people who use custom directories layout without leaving the
.app.src in src/ to still see their app build.
Should fix https://github.com/erlang/rebar3/issues/1475
----
The call is exported with a backwards-compatible value in multiple places however, and that yields areas where we still look for src/ even if that's not what is configured.
> Add respect for src_dirs option in app_discover and app_info

- src/rebar_prv_clean.erl
The wildcard usage could fail on some OSes by being passed directly and
just not finding libs and erroring out
should fix appveyor failure where windows build is now broken.
> Fix wildcard usage in rebar3 clean

- bootstrap
- rebar.config
- src/rebar_prv_escriptize.erl
This also patches up a problem for hooks when dealing with directories
with spaces in them, and reduces complexity of bootstrap file.
Fixes https://github.com/erlang/rebar3/issues/1491
> Windows escripts get cmd autogenerated

- src/rebar_prv_upgrade.erl
Fix a small typo in the help text fro the `upgrade` command.
> Fix typo in help text for upagrde command

- src/rebar_utils.erl
rebar_file_utils:cp_r uses rebar_utils:escape_chars to ensure that the file names are safe to use, but it doesn't escape double and single quotes. If the file name includes those characters, they disappear when the shell processes them and we get "file not found" errors.
The main culprit here is eunit, that creates reports whose names are `TEST-file_"myfile.app".xml`, and I wish it didn't but I think escape_chars should still do its job all the way.
> rebar_utils:escape_chars handles quotes

- src/rebar3.erl
In my OTP installation inets was not installed so I encountered into this #836 at runtime.
This patch fixes it (tested on 17, 18 and 19)
I noticed that in #838 inets was left out from the wrapper fun `ensure_running`, but I don't see any reason for doing that. If apologize if I'm missing something. 
Bye!
> Properly warn on missing rebar3 deps: add inets

- src/rebar_prv_common_test.erl
- test/rebar_ct_SUITE.erl
The option `{spec,Specs}` is allowed in `ct_opts`, but
`rebar_prv_common_test:test_dirs/3` did not take into account that `Specs`
could be a string only, i.e. not a list of strings.
> Allow single test spec in ct_opts

- test/rebar_eunit_SUITE.erl
if and when we upgrade to 19.3 on travis the eunit suite is going to have an error
> eunit in 19.3 errors if `init_per_*` isn't paired with `end_per_*`

- rebar.config
- rebar.lock
Just a re-tag of 3.22.3 which got wrongly pushed to hex without any dependencies
> Bump relx to 3.22.4

- src/r3.erl
- src/rebar_agent.erl
This uses the very risky '$handle_undefined_function'/2 export from the
r3 and rebar_agent modules to allow meta-calls that can support plugins
and all other rebar3 extensions.
This is nasty but very tempting. Currently we only support:
- r3:do(Command)
- r3:do(Namespace, Command)
There is currently no way to pass arguments to the function such that we
can, for example, run cover analysis or tests on a subset of suites.
With the new abuse of '$handle_undefined_function'/2, we can detect the
unused commands (since they are not exported) and re-route them:
- r3:Command()
- r3:Command("--args=as a string")
- r3:Command(Namespace, "--args=as a string")
Of course, in doing so, we make it impossible to use the 'do' provider
(as in 'rebar3 do ct -c, cover') since the 'do' function is already …
> Abuse error_handler to get free metacalls in r3

- src/rebar_log.erl
As of 1.0.0 of erlware-commons it now supports 3 values for intensity
https://github.corp.openx.com/mirrors/erlware-erlware_commons/blob/1.0.0/src/ec_cmd_log.erl#L75
This just allows 'none' to be passed in via the REBAR_COLOR environment variable.
> REBAR_COLOR supports all ec_cmd_log intensity options

- .travis.yml
- src/rebar_prv_common_test.erl
It can't even fetch packages from Hex anymore because of old SSL/TLS
libraries, and so it can't bootstrap anymore either. Plus R20 comes out
soon, and 5 major versions is quite enough.
> Drop R15 support

- src/rebar_opts.erl
- test/rebar_profiles_SUITE.erl
Adds tests and supercedes https://github.com/erlang/rebar3/pull/1422
> Issue #1416: Merge erl_files_first separately and avoid sorting.

- src/rebar_prv_common_test.erl
This is based on issue #1517 where out of nowhere, CT has returned a
user's error code directly. This in turn caused a crashdump in rebar3
itself.
This patch handles the unexpected cases by:
a) not trying to format them
b) converting them to an error whenever they happen
The execution flow is still interrupted, but we should fail with a
clearer error than a crashdump.
> Handle internal CT failures

- src/rebar_fetch.erl
In contrast to `ec_file:delete`, `rebar_file_utils:rm_rf` will also delete
write-protected files on Windows which is needed for git object files.
Fixes #1483.
> Use rm_rf instead of ec_file:delete.

- src/rebar_relx.erl
This is so that some of them can be enforced
(such as warnings_as_errors) on relx's task like
generating a release or a release upgrade.
Continuation of work started in relx in the context of issue erlware/relx#554 and subsequent fix erlware/relx#559
> Let relx know about application erl opts

- src/rebar_git_resource.erl
Let me give you a bit of a context here:
- I found this while I was trying to use a test dependency which is not being locked;
- tried to remove this restriction https://github.com/erlang/rebar3/blob/master/src/rebar_prv_install_deps.erl#L383 and see what's happening;
- the version for my test dependency was set to a 7 chars short SHA;
- noticed that the comparison was always happening between the fully long SHA and the short SHA provided, hence it'll always return true for `needs_update`, and that means it'll always try to fetch the source for the dependency;
- this can be tested as well with a custom plugin hosted on github (see https://github.com/alinpopa/test_git_short_sha as an example for this)
Conditions to replicate this issue:
- make sure you have a dependency that is not locked …
> Fix git SHAs comparison for update.

- priv/templates/LICENSE
- priv/templates/otp_app.app.src
- priv/templates/otp_lib.app.src
The default license created with rebar3 templates is a BSD 3 clause
license. However the .app.src file generated do not include the license
there.
This adds the license type, fixing #1447.
> Match template license app to default license, switch default to Apache 2.0

- src/rebar_prv_upgrade.erl
- test/rebar_upgrade_SUITE.erl
If a dependency someone tries to upgrade is not found in the locks, but actually exists in one of the other currently used profiles, allow all dependencies under that profile to be upgraded.
This is a bit weird, but since the upgrade process works on all unlocked dependencies and that profiles are never locked, this gating mechanism allows to name any profile dep to upgrade them all.
I'm not actually sure this is a desirable feature for this reason, since, well, holy hell, that's not elegant nor intuitive. On the other hand, there is no current way to upgrade profile dependencies, and no good plan to lock profile dependencies (since profiles are arbitrary and that makes for *a lot* of possible combinations of locking), I'm wondering if enabling this 'accidental' behaviour isn't better …
> Allow profile deps upgrade

- src/rebar_relx.erl
- test/rebar_release_SUITE.erl
This mostly moves a lists:reverse/1 which ensures that profile overlays
are run first but keeps the order of overlays otherwise.
> Avoid reversing relx overlays.

- .gitignore
- src/rebar_prv_xref.erl
- test/rebar_xref_SUITE.erl
When a given behaviour module does not exist, rebar3 brutally crashes.
This patch makes it so instead, there is a warning output menitoning the
missing behaviour, and this one is omitted from the unused function
calls check. This means that unused calls will instead be shown for the
module implementing a non-existing behaviour, as if no behaviour were
declared in the first place.
Fixes #1570
> Prevent xref crashes with undef behaviours

- src/rebar_prv_shell.erl
I noticed this when trying to include entop in a release. Entop uses
cecho which takes over the terminal, so you do not want it loaded or
started.  According to http://erlang.org/doc/man/rel.html, when you
specify a Type of none it should not load or start, but the code for
it's modules should be loaded.  This patch ensures the code is not
loaded or started, but doesn't do anything with the code paths.
At the very least this allows me to start a shell in the case where
I have an application of type none, and the application is neither
loaded nor started.
> Rebar3 shell supports booting applications with type 'none'

- src/rebar_prv_bare_compile.erl
Similarly to PATH env variable, this allows to pass paths to bare
compiler which do not fit nicely into a single wildcard structure.
Colon (":") is used as separator.
This provides more flexibility when rebar is used in a offline/hermetic
environment, e.g. #958 and #1281.
> Bare compiler: support multiple paths wildcards.

- src/rebar_erlc_compiler.erl
This was technically an issue before OTP20 but the changes here https://github.com/erlang/otp/pull/1367/files#diff-7a0a8b020276e896d2ae816ccfcfe62eL1481 resulted it modules being recompiled on every run with no changes by the user.
The issue is Erlang does not store all options in the beam chunks, before this was not noticed because the ones it leaves out are not commonly used. With the above changes this was always the case because rebar3 adds an `{outdir, ...}` option. So when comparing the past compilation options to the new it would find they have changed and recompile every module.
This patch instead checks that any of the new options are those considered to effect compilation by Erlang and only then is the module recompiled.
In my opinion `warnings_as_errors` should be removed from …
> recompile only if new option effects code generation

- src/rebar_prv_edoc.erl
- flipped mistaken variable assignment so edoc configuration can be parsed appropriately
> Edoc config error

- src/rebar_prv_xref.erl
If deps app has xref post compile hook and you use include_lib in your app then compilation failed with an error `can't find include lib`.
App1 has `{provider_hooks, [{post, [{compile, xref}]}]}`.
App2 has this app1 in Dependencies and uses include_lib to include header file of app2.
Compilation of app2 failed with an error `can't find include lib`
You can reproduce this error by executing rebar3 compile for this project https://github.com/MikhailKalashnikov/rebar_issue2
This problem occurs because in `rebar_prv_xref:do` code path is reset to default `rebar_utils:cleanup_code_path(rebar_state:code_paths(State, default))` and we lose pathes for compiled apps `ebin` which are added by rebar3 during compilation.
> Fix cleanup_code_path for xref compile hook

- src/rebar_prv_xref.erl
This can be reproduced by running xref analysis against rebar3 plugin projects which don't list rebar3 as an explicit dependency -- calls to certain bundled modules ('rebar_state', 'rebar_api', 'ec_cnv', ...) will result in a failed pattern match as these modules appear to have had their abstract code stripped.
> Avoid xref crash upon undefined functions in modules without debug_info

- priv/templates/gitignore
#1297 is not enough.
`*.iml` is module infomation file for IntelliJ IDEA.
> Ignore IntelliJ IDEA file

- bootstrap
- rebar.config
- rebar.lock
Get more up-to-date root certs. This was blocked for a while because
certifi wouldn't build on windows, but this is now fixed, with minimal
changes to the use case -- only a small change in the bootstrap script
is required.
The new certifi lib is also a few megabytes lighter than before, which
is good for rebar3.
> Upgrade certifi & ssl_verify_fun dependencies

- src/rebar3.erl
- src/rebar_opts.erl
- test/rebar_profiles_SUITE.erl
When a config file exists at the root of a project, defines a given
configuration value for a given profile, and that a sub-application
(umbrella app) also has the same profile defined with the same key (but
different values), the configuration values of the sub-application's
profile would get silently dropped.
The problem being that when the function to merge profiles is applied
recursively, it is applied to each profile (so it will merge on the keys
test, prod, etc.) rather than to each of the values of each profile.
This patch reworks the profile merging so that the current behaviour is
respected overall (a profile cannot be cancelled by a subdep's
non-existant profile since its value should have been ignored), but
ensures that sub-deps' profiles are otherwise applied recursively with …
> Fix recursive profile merging, particularly for umbrella apps

- src/rebar_prv_cover.erl
Hey,
Given module __a__ with 1 line, and module __b__ with 99 lines 
```bash
|------------------------|------------|
|                module  |  coverage  |
|------------------------|------------|
|                     a  |        0%  |
|                     b  |      100%  |
|------------------------|------------|
|                 total  |       50%  |
|------------------------|------------|
```
```bash
|------------------------|------------|
|                module  |  coverage  |
|------------------------|------------|
|                     a  |        0%  |
|                     b  |      100%  |
|------------------------|------------|
|                 total  |       99%  |
|------------------------|------------|
> Fix total coverage

- src/rebar_prv_escriptize.erl
During the building of escripts, multiple passes are done. Two of them
may end up duplicating content: one that gathers all of the beam files
that will be needed for the app to work, and a second one that goes over
the ebin/ directory of the root application to grab all the stuff in
there, prior to the run.
This allows to grab whatever could be required for runtime without
breaking the rest (or so I think), and sticks them at the front of the
archive, where it needs to sit for things to work fine.
Whenever the ebin/ directory contains a pre-compile .beam file, it gets
fetched both from the first pass described and the latter one. This
results in duplicate entries in the resulting zip files used for the
escript and makes the executable larger than it needs to be.
The patch is a simple 1:1 …
> Remove duplicate ebins from escripts

- priv/templates/umbrella.template
Gets in line with more common usage of the wording, as discussed in
issue #1421 and https://www.reddit.com/r/erlang/comments/6sd01p/help_terribly_frustrated_with_the_erlang_build/
> Add an alias of 'release' template as 'umbrella'

- src/rebar_opts.erl
- test/rebar_release_SUITE.erl
Specifically, this impacts profiles. It appears that relx as a whole
requires its configuration to be merged in one tuple order (New takes
precedence over Old), whereas the overlays require the opposite (Old
takes precedence over New) since the operation order on disk is
important to work well.
This patch reorders overlay values such that the overlay of a profile
takes place *after* the basic overlay, ensuring that the profile actions
take place after the basic ones; this allows profiles to properly
overwrite files as expected (see #1609)
This is done while adequately maintaining the order of operations that
were required as part of #1563
Overlay vars of profiles are also checked to be working fine, along with
a test.
This fixes #1247 and #1609
> Fix ordering of overlays and overlay vars in Relx

- src/rebar_dir.erl
- test/rebar_dir_SUITE.erl
When fetching src_dir values, some relative paths can be inserted. When
deduplicating the paths on the fetch, this fact means that logically
duplicate (but literally different) directories can be returned at once.
By normalizing the names, duplication bugs can be resolved.
Fixes #1622
> Fix relative src_dir specifications to avoid double .app.src file detection

- src/rebar_file_utils.erl
- test/rebar_ct_SUITE.erl
Resolving the referenced config files resulted in a list in a list, `[{app, [...]}, [{app, [...]}]]`, and because of this it would not set those config values in `reread_config` which uses a list comphrension `[... || {Application, Items} <- Config, ...]`.
Since `consult_config` always returns a list of length 1 we can safely take the head of the returned list to fix this issue.
> fix sys config merging

- src/rebar_dir.erl
- test/rebar_dir_SUITE.erl
The previous patch at #7c959cc fixed the usage of duplicate values
for directories through relative paths, but mistakenly went overboard
and dropped the `./` path, which is still fairly common. Similarly for
`../`.
The code is modified to special-case such values and keep the code
working.
Fixes https://github.com/erlang/rebar3/issues/1632 because paths like `./../` would yield a crash or an empty
string and now if a relative path is all that can be obtained, this is what
will be kept. Some fun edge cases like `./.././.././` cannot be made fully
normal in some cases and gets reduced to `../..`.
> Corrects a fix to src_dir values

- src/rebar_git_resource.erl
- src/rebar_hg_resource.erl
Those aren't supported and so a warning should be output. Fixes #1003
> Warn user when a local git or hg resource is used

- src/rebar.app.src
- src/rebar_app_info.erl
- src/rebar_otp_app.erl
- test/rebar_pkg_alias_SUITE.erl
-  Add a description in compiled app file if undefined. Same default value as used in relx and other environments, but as reported in #979 some tools don't like having no description available.
- The parsing functions in app_details were used inconsistently, and the returned values were bad in some clauses; things only worked because they are never used within rebar3. This ensures the return types are consistent on all clauses.
- bundling in quickfixes (rollback to git versionning -- I bad messed up a commit) and test patch to find nondeterministic data.
> Various fixes related to .app files

- src/rebar_file_utils.erl
- src/rebar_otp_app.erl
Rather than trying one method and then the other, allow the caller to
specify the encoding of the expected file. All other schemes are risky
and won't work well.
Rollback the function's default interface to the binary format in case
any plugin used it for non-unicode content, preserving backwards compat.
Fixes https://github.com/erlang/rebar3/issues/1644
> Avoid guessing on utf8 decoding of app files

- src/rebar_prv_unlock.erl
- test/rebar_unlock_SUITE.erl
Fixes bugs in behaviour where `rebar3 do unlock, other_cmd` was not equivalent of `rebar3 unlock && rebar3 other_cmd` because the `unlock` provider forgot to update the internal state before returning.
> Fix unlock state carry, which broke `do` sequences with `unlock` in them.

- src/rebar_core.erl
- src/rebar_utils.erl
When a global plugin is used both locally and within the project, there
are cases when the rebar3 program will hard crash (killed in do_boot).
This has been traced to plugin-handling in compilation, where the same
code path may be purged twice in a row without further reloading for the
compile operation.
This of course yields the result where the code handling on the VM kills
all processes holding references to the module in memory, in this case
the rebar3 process itself.
By deduplicating the paths first, we ensure at most one purge before
reloading plugins and paths, and this prevents a hard crash.
> Prevent hard crash on duplicate plugin paths

- src/rebar_prv_update.erl
I am not sure about option {relaxed, true}. 
In my case, it also works without it.
Should I add it? Like in this place:
https://github.com/erlang/rebar3/blob/3.4.4/src/rebar_pkg_resource.erl#L110
> fixed handling of proxy username and password when fetching registry

- bootstrap
- rebar.config
- rebar.lock
- src/rebar_dialyzer_format.erl
- src/rebar_dir.erl
- src/rebar_file_utils.erl
- src/rebar_git_resource.erl
- src/rebar_hg_resource.erl
- src/rebar_hooks.erl
- src/rebar_packages.erl
- src/rebar_pkg_resource.erl
- src/rebar_prv_app_discovery.erl
- src/rebar_prv_bare_compile.erl
- src/rebar_prv_common_test.erl
- src/rebar_prv_dialyzer.erl
- src/rebar_prv_eunit.erl
- src/rebar_prv_local_upgrade.erl
- src/rebar_prv_path.erl
- src/rebar_prv_shell.erl
- src/rebar_relx.erl
- src/rebar_string.erl
- src/rebar_templater.erl
- src/rebar_utils.erl
- test/rebar_ct_SUITE.erl
- test/rebar_dialyzer_SUITE.erl
- test/rebar_install_deps_SUITE.erl
- test/rebar_profiles_SUITE.erl
- test/rebar_test_utils.erl
- test/rebar_unlock_SUITE.erl
This replaces all deprecated function usage by alternative ones based on
a version switch enacted at compile time, preventing all warnings.
This will likely introduce some possible runtime errors in using a
Rebar3 compiled on OTP-20 or OTP-21 back in versions 19 and earlier, but
we can't really work around that.
A bunch of dependencies have been updated to support OTP-21 without
warnings as well.
Resolves #1636, supersedes #1659
> OTP-21 readiness, Full Unicode support

- src/rebar_prv_install_deps.erl
When fetching deps, if this is a clean repo there will be extensive
messages warning that dependencies which have already been fetched are
being skipped. For large projects being built and tested in a clean
environment this significantly increases the noise level of the build.
This modification adds an additional rebar option
(deps_warning_on_conflict) that will allow disabling these warning
messages. If deps_error_on_conflict is set, an error will still be
thrown. This will not change default behaviour of rebar.
There is a similar outstanding issue:
https://github.com/erlang/rebar3/issues/1105
However this seems to be a push for not outputting warnings when the dep
version is the same, rather than disabling warnings altogether.
> Allow silencing skip warnings when fetching deps

- src/rebar_opts.erl
- test/rebar_profiles_SUITE.erl
Current rebar3 uses debug_info rules where debug_info is added by
default, and no_debug_info prevents the default from being added, and
removes any explicit debug_info, if any. The problem is that if
'no_debug_info' is anywhere in the config for a run, it cannot be
removed even with other profiles. additionally, no_debug_info ignores
special tuples like {debug_info, {Mod, Data}} and {debug_info_key, Key},
which can be used to add debug info and encrypt it (in lieu of plain
debug_info) respectively.
This patch makes it so that the following rules are in place:
- the first option seen takes priority, allowing profile overrides by
the ordering rules
- because the compiler apparently does not care for that order (it does
not have to), the overriden options shall be explicitly deleted
- any …
> Make debug_info rules clear

- src/rebar_prv_compile.erl
The Erlang compiler runs based on a global state built from currently
loaded libraries and the configured code path that is available. For
this reason, the rebar3 compiler job unloads all plugin paths before
calling the Erlang compiler.
However, this causes a problem when an application uses a custom
resource handler with a dynamic version in their .app.src file since the
plugin that can be used to find the version has been unloaded.
Fortunately, the compile phase that runs the version handling is
distinct from the phase that uses the Erlang compiler. This patch fixes
the problem by re-loading the plugins' paths in memory before generating
the .app file, and before unloading them afterwards.
It appears that unloading them is unnecessary because the hooks after
that will re-load them, but …
> Fix compilation for custom resources dynamic vsn

- src/cth_retry.erl
- src/rebar_prv_common_test.erl
This commit adds a common test hook along with the `cth_readable` stuff whose role is to track failing test cases, and create a test specification out of them.
The test specification is dumped on disk at `_build/<profile>/logs/retry.spec` and can be accessed by calling `rebar3 ct --retry`. This will auto-load the spec file if it can be found and re-run the failing cases.
If any other argument is found on the list specifying tests, the `--retry` argument is ignored.
All code for this is marked as experimental in case we end up (keeping and then) dropping the feature.
Sample failing run:
```
$ ./rebar3 ct --suite test/rebar_as_SUITE.erl
...
===> Running Common Test suites...
%%% rebar_as_SUITE ==> as_basic: OK
%%% rebar_as_SUITE ==> as_multiple_profiles: FAILED
%%% rebar_as_SUITE ==> …
```
> Add experimental support for ct --retry option

- src/rebar_prv_common_test.erl
- src/rebar_prv_cover.erl
- src/rebar_prv_eunit.erl
- test/rebar_cover_SUITE.erl
- test/rebar_ct_SUITE.erl
Adds option for `eunit` and `ct` to set the name of the coverdata file exported when cover is enabled. this will allow for aggregating cover stats of multiple different `ct` or `eunit` runs -- not simply aggregating `ct` and `eunit` runs together.
> add eunit and ct option to set coverdata file name

- rebar.config
- src/rebar_plugins.erl
- systest/all_SUITE.erl
- systest/all_SUITE_data/resource_plugins/rebar.config
The path reloading of plugins had been fixed properly, but the problem
is that the paths it was using to re-load only considered the current
compile step, rather than the overall state of plugins. As such, the
reloaded paths after plugin compilation only reloaded the *latest*
plugin and not the other ones.
This fix forces the addition of all built plugin paths to the code paths
after a plugin compile job is run. This ensures that the path is clean
for initial plugin deps (only add those that are required), and is
re-made total after the fact (add all the plugins possible).
This commit also includes a system tests suite that can be run
optionally; the problem with this plugin mechanism was impossible to
find through mocked dependencies, and a working counterexample was
provided to us. The …
> Fix Plugin path handling (again!)

- src/rebar_file_utils.erl
Removes the /is switch to robocopy for win7, and has no ill effect as tested on Win10.
This should hopefully fix #1680 -- CC @hgisinger
> Fix file handling on Windows 7

- bootstrap
The bootstrap script has been mostly unchanged for a long period of
time, and has not benefited from all the changes and improvements that
rebar3 itself had, including (but not limited to) path escaping,
handling of directories on windows, and edge case management when it
comes to file and symlink handling.
This patch brings the updates seen in rebar_string_utils, rebar_utils,
and rebar_dir into the bootstrap script so that fewer people have build
issues when starting from source, from scratch.
Fixes #850
> Update bootstrap script // fix windows issues

- src/rebar_prv_escriptize.erl
- test/rebar_escriptize_SUITE.erl
Although fairly irregular, the presence of a subdirectory in ebin/ while
running rebar3 escriptize would crash the run and generate a dump.
Since ebin subdirectories are generally not supported (adding a path for
an application only adds ebin/ and no subdirectories to the VM's path
set), we just silently ignore the directory altogether.
Fixes #1693
> Fix escriptize failure when ebin/ has subdirs

- bootstrap
Updating the bootstrap script in #1689 made it so symlinks that already
exist return `exist` rather than ok, in line with the regular code.
However the bootstrap module wouldn't handle this case.
This fixes the problem by ensuring that `exists` is as valid as `ok`.
Fixes #1691
> Fix repeated bootstrap runs

- README.md
URL goes to 404 page, corrected URL to avoid confusion.
> Corrected Erlang Solutions Download URL [skip ci]

- src/rebar_prv_alias.erl
- test/rebar_alias_SUITE.erl
The way arguments are passed by the alias provider is not compatible
with all rebar providers/commands. Especially the release (relx)
provider does not like getting its arguments as a plain string. It
expects its arguments in a pre-parsed format as returned by
getopt:parse/2.
Other commands, e.g. eunit, seem to be fine with both ways of argument
passing. Therefore, this fix changes the alias provider argument passing
to the getopt format in general.
Basically, this is a port of this tsloughter/rebar_alias#1 PR.
> Issue #1704: Fix alias provider argument passing

- src/rebar3.erl
- src/rebar_prv_deps_tree.erl
This PR sets unicode option for standard_io at the very entry point of rebar3.
The issue was:
Using eunit test cases weith titles with unicode characters
```
long_test_() ->
[{"タイトル", fun() -> timer:sleep(100) end}].
```
(`タイトル` is "title" in Japanese Katakana), output is in escaped format like
```
Top 10 slowest tests (0.134 seconds, 13.3% of total time):
foo_tests:long_test_/0: \x{30BF}\x{30A4}\x{30C8}\x{30EB}
```
Rebar3 3.4.4 works nice, but 3.4.5 does not.
The direct cause is `~ts` pattern in [1] (it IS right.)
Fixing direction:
Set unicode option for starndard_io.
Before this PR,  tree command uses it but others don't.
It's possible to set option in eunit runner. This PR chooses to use it
at entry point because of rebar3 now should supoort unicode as in [2].
[1] …
> Set unicode option for standard_io at entry point

- src/rebar_packages.erl
- test/rebar_pkg_SUITE.erl
Rebar3 would solve a version constraint to the first version available if it there was no version that matches the constraint because of the `foldl` we used starting at `HeadVsn`.
> rebar_package: do not return first package version for constraint with no match

- src/rebar_env.erl
- src/rebar_hooks.erl
- src/rebar_utils.erl
This adds and exports the necessary parts to use env variables like REBAR_DEPS_DIR inside provider hooks. It addresses this issue in port_compiler: https://github.com/blt/port_compiler/issues/30
There will be a separate pull request in that repo as well.
This branch is based off of https://github.com/erlang/rebar3/pull/1698 and should not be merged before that one. But in order to use env variables in port_specs of deps, you actually have to run the port_hooks for the deps. So this depends on the mentioned pull request.
> Env for providers

- src/rebar_prv_update.erl
These warnings just confuse users. We should really only bother the user if they try to use one of these packages, not every time they update the package index.
> use debug level for logs about bad package versioning

- src/rebar_dir.erl
- src/rebar_state.erl
- test/rebar_profiles_SUITE.erl
Ensures that directories inside _build/ have a fixed nomenclature: makes it impossible for `rebar3 as a,b` to create sometimes `_build/a+b` and other times `_build/b+a`.
I got caught by it when developing offline. Plugins were pulled to a+b but then rebar3 would decide to use `b+a` and would fail to load plugins.
Next step would be to symlink plugins instead of re-fetching them when using a new `as` combination. That would probably be an issue provided that plugins are (generally?) un-version'ed.
> sort-as: force an order on multiple profiles

- bootstrap
- rebar.config
We got funny interactions since PR #1656:
- the last `debug_info`-related option seen in a list of options after
profile merge is kept, allowing later profiles from overtaking earlier
ones
- if you go `rebar3 as a,b,c compile`, the options from profile A come
before B, which come before C, so C's options win
- overrides are applied in order of profile as well, giving a priority
to a later profile than an earlier one
- The values in overrides are prepended rather than suffixed to the
existing list
- this means if we have to overrides adding options, such as `default`
adding `no_debug_info', and `dialyze` adding `debug_info`, the
results are `[debug_info]` as `dialyze` is applied first, and then
`[no_debug_info, debug_info]` as `default` overrides are applied
- the final result is …
> Make rebar3 work with dialyzer internally

- src/rebar_utils.erl
- test/rebar_utils_SUITE.erl
We've had multiple tickets opened because of unclear PROXY settings when
the scheme is missing form the URI. To be helpful, we instead add them
dynamically whenever they're missing.
Example issues:
- https://github.com/erlang/rebar3/issues/1747
- https://github.com/erlang/rebar3/issues/1697
> Handle Schema-less Proxy URLs in ENV vars

- .travis.yml
- rebar.config
- src/rebar_app_info.erl
- src/rebar_hg_resource.erl
- src/rebar_prv_escriptize.erl
- src/rebar_prv_unlock.erl
Some still remain from erl_type calls from Dialyzer, but most of them
are handled.
Decided to just ignore rebar_alias since playing with the type specs of
abstract code format is just a nightmare and hard to do cross-versions I
guess.
> Fix various Dialyzer warnings

- src/rebar3.erl
- test/rebar_profiles_SUITE.erl
When adding the 'TEST' macro to the test profile, we mistakenly sourced
the erl_opts values from the base profile rather than the test profile
itself.
This means that in cases where the base profile set an option such as
'no_debug_info' and a profile overrode it with 'debug_info', the default
options would get injected within the test profile, and broke the
precedence rules, yielding incompatible values.
This patch fixes things by adding the macro to the values sourced from
the test profile itself, fixing the issue.
Fixes #1715
> Fix precedence rules of erl_opts for test profile

- src/rebar_prv_local_upgrade.erl
Since packages store etags on disk directly, the local install feature
can no longer depend on this; we instead port the etag feature back to
local providers only.
Fixes #1760
> Fix local upgrade etag handling

- src/rebar.app.src
- src/rebar_string.erl
- test/rebar_dir_SUITE.erl
- this is done by adding a HiPE dependency, which makes calls to erl_types work in analysis 
- also in this: adding a test for directories, and fixing some indent
> Clear all dialyzer errors

- src/rebar_packages.erl
- src/rebar_prv_local_install.erl
This should provide more help to users directly and avoid having them go
through opening tickets for help.
Fixes #1767
> Display warnings when cache dirs are read-only

- src/rebar_file_utils.erl
- src/rebar_prv_compile.erl
- test/rebar_dir_SUITE.erl
This PR augments what is found at #1763 by @danikp
Original Description
---------
While using src_dirs options it's possible to set first level directories under app folder, but setting something deeper will fail on copying files to _build folder. so following example will work
```
{src_dirs, [
"src",
"src2"
]}.
```
and this one not
```
{src_dirs, [
"src/lib",
"src/mail",
"src/test",
"src/view",
"src/websocket"
]}.
```
failing with error
> cp: cannot create directory '/some/path/to/project/_build/default/lib/web/src/lib': No such file or directory
that happens cause cp command not creating missing path parts. This PR comes to solve it by trying to create destination folder with all parent folders in path.
-------
Difference with Original
------
The original branch had a test we both …
> ensure dest exists before copying to it and fix src_dirs symlinking

- rebar.config
Had mistakenly only disabled it for deps.
> Re-disable debug_info on prod profile

- priv/templates/escript_rebar.config
- rebar.config
- src/rebar3.erl
- src/rebar_prv_local_install.erl
fixes an issue when shell is terminated with an error "Bus error: 10",
on attempt to run rebar shell with verbose logging
Error example:
```
$ ./rebar3 help ct
Run Common Tests.
Usage: rebar3 ct [--dir <dir>] [--suite <suite>] [--group <group>]
[--case <testcase>] [--label <label>]
[--config <config>] [--spec <spec>]
[--join_specs <join_specs>]
[--allow_user_terms <allow_user_terms>]
[--logdir <logdir>] [--logopts <logopts>]
[--verbosity <verbosity>] [-c [<cover>]]
[--cover_export_name <cover_export_name>]
[--repeat <repeat>] [--duration <duration>]
[--until <until>] [--force_stop <force_stop>]
[--basic_html <basic_html>] [--stylesheet <stylesheet>]
[--decrypt_key <decrypt_key>]
[--decrypt_file <decrypt_file>]
[--abort_if_missing_suites [<abort_if_missing_suites>]]
[--multiply_timetraps …
```
> start at least one async thread in async thread poll

- rebar.config
When allowing Dialyzer to work internally, we moved a bunch of
config (such as no_debug_info) to the prod profile, but the escript
included files remained locked onto the default profile.
Because the bootstrapping phase now happened in a prod run, the priv/
dirs were never created for the default profile unless a prior run
existed, which hid the bug from us.
This patch overrides the path on the prod profile so that we don't rely
on accidental leftovers for things to work on a bootstrap phase as a
dev.
Fixes #1781
> Restore default templates in bootstrapped rebar3

- src/rebar_erlc_compiler.erl
- src/rebar_utils.erl
- test/rebar_utils_SUITE.erl
This PR resolves #1645. 
To be clear we can not abort if `""` is given, because it may be `[]` which is valid. Neither result in a fatal though, so it's a non-issue.  
TODO:
> Resolve string vs list crashing rebar3 

- src/rebar_prv_bare_compile.erl
- test/rebar_hooks_SUITE.erl
Fixes https://github.com/erlang/rebar3/issues/1804
> run compile provider in default namespace from bare

- src/rebar3.erl
- added type specs for following private functions:
- run/1
- set_options/2
- test_state/1
- safe_define_test_macro/1
- test_defined/1
The typespecs definitely need to be reviewed, dialyzer didn't complain but can be off sometimes of course. I did get a few other dialyzer warnings that are not caught by the test suite but will deal with those in another Issue/PR.
> Finish adding specs for private funs in rebar3.erl

- rebar.config
- rebar.lock
Opening this for an easy place to point users to get a branch they can try that pulls in an updated erlware_commons and relx before having to merge and release those.
And a place for feedback/comments on the solution, assuming it works for people.
Related PRs to relx and erlware_commons:
https://github.com/erlware/relx/pull/661
https://github.com/erlware/erlware_commons/pull/135
> otp-21 eperm fix: bump of erlware_commons and relx

- src/rebar_erlc_compiler.erl
Background:  Some projects. in the wild use atoms (module names) in erl_first_files (which may or may not be valid and/or work)
Purpose: Instead of throwing these projects a curve ball we should provide them a meaningful warning or error. 
Concerns: I think this should be an abort instead of warning, though I'm still unclear as to whether module names (atoms) in erl_first_files is indeed valid at some level.
> Warn but succeed when atoms are passed to erl_first_files

- src/rebar_agent.erl
add option(refresh_paths & refresh_paths_blacklist) for support set refresh_paths when reload modules.
I add this for resolve some app(like ranch or amqp_client) will crash when use rebar3_auto to recompile and reload modules.
> smarter shell code reloading, add env options for refresh_paths & refresh_paths_blacklist

- bootstrap
- rebar.config
- rebar.lock
Includes an update to parse_trans on an OTP-21 friendly version
> Bump certifi

- src/rebar_erlc_compiler.erl
This is a modification of function of effects_code_generation of rebar_erlc_compiler.
> add report in the effects_code_generation, as it is the short form for both report_errors and report_warnings

- src/rebar.hrl
- src/rebar_hex_repos.erl
- src/rebar_pkg_resource.erl
- src/rebar_string.erl
- test/rebar_pkg_repos_SUITE.erl
auth token are kept in a hex.config file that is modified by the
rebar3 hex plugin.
Repo names that have a : separating a parent and child are considered
organizations. The parent repo's auth will be included with the child.
So an organization named hexpm:rebar3_test will include any hexpm
auth tokens found in the rebar3_test organization's configuration.
> add hex auth handling for repos

- src/rebar_prv_shell.erl
- src/rebar_utils.erl
This requires some fancy dynamic work since the logger is started as
part of the kernel and we lost the sys.config from users when working
from there.
We start conservatively by making it an optional thing, turning it on
only where we know it to be safe.
The changes are applied _after_ having loaded the rest of configs so if
an inoffensive error happens, the shell works (with a bad error message)
rather than plain exploding.
Fixes #1868
> Reload logger config in shell

- src/rebar3.erl
- src/rebar_hex_repos.erl
- src/rebar_packages.erl
- src/rebar_pkg_resource.erl
- src/rebar_prv_install_deps.erl
- src/rebar_resource.erl
- test/rebar_pkg_SUITE.erl
- test/rebar_pkg_alias_SUITE.erl
Also removes the printing of the source from upgrading info message.
> move packages to top level of of hexpm cache dir

- src/rebar_app_discover.erl
- src/rebar_plugins.erl
top level default profile plugins are installed in the run_aux
function. This commit removes the plugins from the plugin opts
of an application that is also at the top level and skips the
default profile when installing top level plugins in
project_apps_install so they aren't handled twice.
> reset default profile app plugins to empty if at the top level

- src/rebar_prv_install_deps.erl
- test/rebar_install_deps_SUITE.erl
@marianoguerra brought up how noisy the warning about skipping deps was for some of his projects. While this is in large part because we don't lock plugins (and we mute the warning if it is a lock) I noticed it is printing them even if there is no conflict, which was the purpose of printing the warning in the first place.
So this commit fixes it to not print the skip if its the same source tuple (name, verison, checksum).
> only print skip warning if version is different

- rebar.config
- src/rebar_app_discover.erl
- src/rebar_app_info.erl
- src/rebar_erlc_compiler.erl
- src/rebar_prv_plugins.erl
- test/rebar_compile_SUITE.erl
- test/rebar_hooks_SUITE.erl
- test/rebar_test_utils.erl
Fix for #1860 
When REBAR_CONFIG was set it would not effect the top level app's configuration because app_discover was rereading the top level rebar.config which ignored REBAR_CONFIG. Instead this patch has it use the existing configuration from REBAR_CONFIG.
I think it looks like more changes than it really is... The main change is to not reload the `rebar.config` for a top level application from disk. The related opts for a top level app are already read in and parsed into the State.
> properly support top level app erl_opts from REBAR_CONFIG os var

- src/rebar.hrl
- src/rebar_app_utils.erl
- src/rebar_packages.erl
- test/mock_pkg_resource.erl
- test/rebar_pkg_SUITE.erl
- test/rebar_pkg_alias_SUITE.erl
- test/rebar_pkg_repos_SUITE.erl
retired packages are now used the same as any other but a warning will be printed when it is resolved.
prerelease versions are skipped unless explicitly given as the version in the constraint or lock file.
> warn if the matched package is retired, skip prerelease

- src/rebar_erlc_compiler.erl
However, we add a once-printed deprecation warning for the new
interface.
Warning is:
`===> Calling deprecated rebar_erlc_compiler compiler module. This module has been replaced by rebar_compiler and rebar_compiler_erl, but will remain available.`
> Re-add erlc compiler; plugins need it

- src/rebar_prv_compile.erl
This needs to happen or else the user gets a more confusing error message later about how there is no .app file.
> throw builder error when returned from project build

- src/rebar_app_info.erl
- src/rebar_pkg_resource.erl
- src/rebar_state.erl
- src/rebar_utils.erl
app_info was turning any vsn into a binary which the vcs_vsn function interprets as being an actual version and not something like <<"git">>. original_vsn shouldn't be converted as it is then not longer "original".
> fix resolving versions from vcs

- src/rebar3.erl
- src/rebar_api.erl
- src/rebar_compiler.erl
- src/rebar_hooks.erl
- src/rebar_packages.erl
- src/rebar_paths.erl
- src/rebar_plugins.erl
- src/rebar_prv_common_test.erl
- src/rebar_prv_compile.erl
- src/rebar_prv_dialyzer.erl
- src/rebar_prv_edoc.erl
- src/rebar_prv_eunit.erl
- src/rebar_prv_xref.erl
- test/rebar_compile_SUITE.erl
- test/rebar_paths_SUITE.erl
- test/rebar_plugins_SUITE.erl
This updates and replaces how most of the path handling in rebar3 is being done. Instead of adding paths here and there mostly at random, this attempts to take a more systematic approach of tracking currently-used modules and replacing them explicitly, while caring for plugins or deps to be in proper order.
Implements the fixes proposed at #1899 
Also fixes a path bug in the compiler.
> Refactor env path handling and fix some bugs related to it

- src/rebar_utils.erl
- test/rebar_hooks_SUITE.erl
Dollar Variable expansion (`$VAR`) was inadvertently disabled for
windows variables, although %VARIABLES% already worked. This reduced the
portability of hooks in general.
This was disabled more than four years ago, I'm in fact not quite sure it had ever
worked as intended since `expand_sh_flag/1` wrapped the env value in a way that
`proplists:get_env/3` _always_ returned `[]`. This is re-expanding them. This might
actually be a bit risky to enable at this point.
Additionally, tests would fail on windows due to bad quoting of paths:
the path C:/a/b/c would fail when passed to the command
`cmd /q /c C:/a/b/c` because it would interpret /a /b and /c as 3
options. Using quotes makes the tests pass. This one fix should at least
be safe on its own, but I'm curious as to how it ever passed …
> Fix shell hook expansion on windows

- src/rebar_log.erl
In some cases, such as when the global rebar.config file contains typoes
and invalid terms, the rebar3 executable fails when trying to log the
error since it hasn't been set yet, such as in #1792
This patch fixes that by going for a fallback mechanism.
> Fallback when logging isn't initialized

- src/rebar_git_resource.erl
- src/rebar_hg_resource.erl
This PR is a simpler and mergeable version of #1853 by @shamis, since
the provider changed format enough to make merging difficult.
Compared to #1853, this also puts the responsibility on each resource to
check rather than adding a new optional callback.
The process dictionary is use as a warning/check cache.
> check if git/hg is installed

- src/r3.erl
- src/rebar_agent.erl
This is mostly useful for tests, where a test suite of any kind can be
interrupted halfway through so that the user can probe the running
system to see what is happening.
This is done as follows:
1. the user must call `r3:break()` in a test suite
2. the user runs the task as `r3:async_do(Task)`
3. the test holds up and the user can do whatever
4. the user calls `r3:resume()` and the test proceeds as normal
A safeguard is added so that breakpoints are only triggered in the shell
in async mode
Sample session:
$ rebar3 shell
...
1> r3:async_do(ct).
ok
...
Running Common Test suites...
%%% rebar_alias_SUITE: .
=== BREAK ===
2> % <do some checks>
2> r3:resume().
ok
3> .....
%%% rebar_as_SUITE: ...........
%%% rebar_compile_SUITE: ......
...
> Allow Breakpoints during task runs

- priv/templates/app_rebar.config
Uncommenting the sys.config shell setting in app template rebar.config
works now as expected.
> Fix misleading config in app template

- src/rebar_app_discover.erl
Without this the locks for dependencies would not be loaded. Not an issue for package deps but it is for checkouts and git deps.
> set app's dir before setting app_info deps

- src/rebar3.erl
Like resources, compilers has to be set for the global state that ultimately gets thrown away, if global plugins are to be able to be fetched and compiled.
> fix compilation of global plugins

- src/rebar_prv_plugins.erl
I believe project plugins should also be listed when displaying plugins by: `rebar3 plugins list`
> Fix plugins list display to include project plugins

- src/rebar_otp_app.erl
This change broke inclusion of modules that are built straight to beam files and have no `.erl` file in the src dirs for them.
I don't think the removal of beams that are built from extra src dirs is required though... I kept it there since I'm just reverting to the old functionality, but extra src dir beams aren't built to the ebin dir, so not sure why that is there. Unless we should be building extra src dir files to ebin instead of doing the annoying copying of source files.
> revert ebin_modules to include all beams minus extra_src

- src/rebar_prv_cover.erl
The old path handling routine would force loading a bunch of
applications, but it did not necessarily unload them aside from specific
calls that the other test handlers used to need to do, but no longer
needed under the updated path management of 3.7.0.
The leftover calls in the cover compilation bits caused some apps to be
loaded and to remain loaded before tests started.
Fixes #1958
> Fix path coverage loading artifacts

- src/rebar_app_info.erl
- src/rebar_app_utils.erl
Marked as WIP because I'm not exactly happy with it. I'd like to understand why the `app_utils` part needed to change. The `app_info` part I understand, the new `rebar_paths` wants to find a `.app.src` file to get details and that shit doesn't exist in mix projects.
Though may want to change how it is handling a case like that, catching the exception worked to at least get mix projects to build but isn't the cleanest solution I'm sure.
> fix for mix projects that don't have app.src files

- src/rebar_prv_upgrade.erl
Before this fix warnings were displayed during package upgrade when `rebar3` and `hex` package names were different. For example "mixer" / "inaka_mixer". Such deps are specified like:
```
{deps, [
{mixer, "1.0.1", {pkg, inaka_mixer}}
]}.
```
On branch master `rebar3 upgrade` gives:
```
===> Failed to update package from repo hexpm
===> Failed to fetch updates for package mixer from repo hexpm
```
Note the package name ("mixer") in the warning message.
After the fix there is no warning.
> Fix pkg name during update by using pkg_name understood by hex

- THANKS
- src/rebar_prv_xref.erl
- test/rebar_xref_SUITE.erl
Closes #1905 
This PR is for supporting `module()` in xref ignores config list and via `-xref_ignore()` module attribute. 
The current specification (prior to this PR) for xref ignores is : 
`[{module(), function(), arity()} | {module(), function()}]`. 
However,  it is often desirable to ignore an entire module for varying reasons. This patch updates the specification to:
`[module() | {module(), function(), arity()} | {module(), function()}]`
TODO:
> Support ignoring entire modules in xref results

- priv/shell-completion/bash/rebar3
- priv/shell-completion/fish/rebar3.fish
- priv/shell-completion/zsh/_rebar3
- src/rebar_prv_eunit.erl
- test/rebar_eunit_SUITE.erl
This PR adds `--generator` option for rebar3 eunit.
The option is useful when we add new eunits.
Here is an example
`./rebar3 eunit --generator some_app:util_functions_test_`
> Add --generator option for eunit

- src/rebar_hg_resource.erl
I got a case clause when I tried to fetch a hg dep.
===> rebar_fetch exception error {case_clause,undefined} [{rebar_hg_resource,
check_type_support,
0,
[{file,
"/opt/rebar3-3.8.0/src/rebar_hg_resource.erl"},
{line,
200}]},
.....
===> Failed to fetch and copy dep: {hg,"****"}
> Fix bad clause when validating support of hg resources

- priv/templates/otp_app.app.src
- priv/templates/otp_lib.app.src
The maintainers field was hard deprecated in rebar3_hex, this updates the template per that change.
> update template moving maintainers into extras field

- bootstrap
This should avoid common problems when upgrading across versions where
old code kind of messes up a lot of things and clearing _build keeps
being required.
This was suggested on IRC.
> Clear _build/bootstrap on each bootstrap run

- src/rebar_file_utils.erl
This PR fixes systests on darwin where previously the recursive `cp` would fail due to everything being copied after the last forward slash. Specifically, everything in  `systest/all_SUITE_data/` would be
copied but not `all_suite_data` dir itself which the tests expected.
> Remove trailing forward slash before recrusive cp on darwin in rebar shell utils

- src/rebar_compiler_erl.erl
When the commit at https://github.com/erlang/rebar3/commit/8c4a74a3ed9ddd9841e6596ca86b81f3d43906c0
introduced a recursive search for build elements, it accidentally did so
using a function that accepts a regex for its match.
In doing so, if a behaviour or include had a name such as
`common_prefix` and that multiple other modules used the name
`common_prefix_<rest_of_name>`, all the other files would be seen as
dependencies to be checked in a directed graph.
This resulted in continuous re-checking of files that kept depending on
each others and blew the compile time up exponentially.
By using a delimitation on the regex (`^<modulename>$`), the build comes
back down to finding only the right files and becomes fast again.
Fixes #1997
> Fix performance regression in compiler around behaviours

- src/rebar_prv_deps_tree.erl
This change makes it so umbrella projects get ordered in a way more
in-line with what we do with non-umbrellas.
For example, a non-umbrella app (rebar3 itself) gives output like:
└─ rebar─3.8.0+build.4270.refaece1d7 (project app)
├─ bbmustache─1.6.0 (hex package)
├─ certifi─2.3.1 (hex package)
├─ cf─0.2.2 (hex package)
├─ cth_readable─1.4.2 (hex package)
├─ erlware_commons─1.3.1 (hex package)
├─ eunit_formatters─0.5.0 (hex package)
├─ getopt─1.0.1 (hex package)
├─ hex_core─0.4.0 (hex package)
├─ parse_trans─3.3.0 (hex package)
├─ providers─1.7.0 (hex package)
├─ relx─3.28.0 (hex package)
└─ ssl_verify_fun─1.1.3 (hex package)
The current (prior to this patch) output for an umbrella project looks
like this:
├─ bootstrap─0.0.2 (git repo)
├─ dirmon─0.1.0 (project app)
├─ fake─0.1.0 (project …
> Reorder rebar3 tree output on umbrella apps

- src/rebar_git_resource.erl
Partially reverts commit f52a115ea9d66c812f68200383d769ac300a2828
Fixes #2003. (The single quotes cause the path to be mis-parsed in the windows command prompt, git cannot find the repo, and therefore rebar reports that "Locking of git dependency failed".)
Needs tests to prevent a future regression. (Sorry, this is outside my expertise / time available.)
> Use double quotes in git shell command on Windows

- src/rebar_compiler.erl
- test/rebar_compile_SUITE.erl
This change fixes cases where changes in .hrl files would not be picked
up in .erl files that are in extra source directories (such as those
defined with `extra_src_dirs` or modules in the test/ directory during a
CT or Eunit run).
The problem was due to the way the Directed Acyclic Graph (DAG) of
dependencies between files was being loaded and stored by the compiler
modules.
Prior to this fix, a single DAG would be used for all runs. On a regular
run, the prior DAG is loaded from disk, re-checked, and if changed, it
would get re-written to disk with the changes deciding what to
re-compile. However, whenever extra source directories were specified, a
second run would be done which swaps target directories around in the
compiler modules.
Bug 1: this second run was done without properly …
> Fix handling of updated files in extra_src_dirs

- src/rebar_prv_shell.erl
Allows to select one of many releases conditionally.
Default behaviour should be unchanged from existing one.
Can filter on only the version or only the name, or both.
> Add --relvsn and --relname to rebar3 shell

- src/rebar_agent.erl
by default, all apps except internal rebar3 ones can be blacklisted.
Some months ago, someone added support for configurable lists within
rebar3 itself using the .app env.
This PR re-exports that functionality from the rebar.config file, so
that one can set something like:
{shell, [
{app_reload_blacklist, [cowboy, ranch]}
]}.
Which will allow to prevent applications that often crash when being
reloaded from doing so. For example, cowboy and ranch processes can be
stuck in an accept call for multiple reloads in dev, which ends up
causing large failures.
> Support setting shell hot code loading blacklists

- THANKS
- src/rebar_prv_plugins.erl
Fixes #1417 
Running `rebar3 plugin list` now outputs the following
```
$ rebar3 plugins list
--- Global plugins ---
rebar3_hex (4.1.0)
```
> Include version in plugin list

- src/rebar_hex_repos.erl
- test/rebar_pkg_repos_SUITE.erl
- Modified rebar_hex_repos:auth_config/1 to abort on error except in
the case of enoent, in which we return an empty map.
Example output for the two unhappy cases:
```
===> Error found in auth config (/Users/starbelly/.config/rebar3/hex.config) at line 3: syntax error before: '=>'
```
and
```
===> Error reading auth config (/Users/starbelly/.config/rebar3/hex.config) : eacces
```
TODO:
> Abort when file:consult/1 returns an error in rebar3_hex_repos:auth_config/1

- src/rebar_prv_escriptize.erl
Previously all escriptize hooks from all apps in the project were
executed, which could lead to issue in case of dependencies on artifacts
which are created by these hooks.
Now the behaviour is similar to the handling of other non-global hooks.
> Fix provider hook handling for escriptize

- src/rebar_app_utils.erl
- src/rebar_prv_deps.erl
- test/rebar_deps_SUITE.erl
As explained in #1864, the `deps` command was printing an * even when deps were updated.
This PR makes the command call `rebar_fetch:needs_update/2` for each of them in order to print or not the *
> Fix rebar3 deps command

- src/rebar_packages.erl
For some odd reason, from time to time I get (persistent) `eaccess` errors in `tab2file`. I still have to investigate, where these come from, but I think the error should be non-fatal.
> Catch errors in writing the package cache

- src/rebar_compiler.erl
- src/rebar_compiler_erl.erl
This PR supercedes #2039, which had the following description:
> Support for parallel compilation of *.erl file was dropped before 3.0 release.
> However, our tests for a project containing ~500 source files show substantial gain, lowering compilation time from 58 seconds to 18 on a MacBook Pro 15" (4 cores, 8 threads), and to just 10 seconds on Xeon-D machine.
This patch does two things on top of @max-au's PR:
1. it broadens the interface for the compiler module so that non-first-file modules can possibly be parallelized. This is done by dynamically switching on `[ListOfFiles]`, which remains sequential as
before, or `{[SeqPriority], [Parallel]}`, which divides regular files between higher priority ones and those that can be in parallel
2. implements this mechanism in the rebar compiler, …
> Enable parallel build

- rebar.config
- rebar.lock
Lots of goodies:
- [Include dist and epmd arguments from vm.args in remote console and nodetool calls](https://github.com/erlware/relx/pull/710)
- [Don't require a cookie in the start script](https://github.com/erlware/relx/pull/708)
- [use RELX_OUT_FILE_PATH to write configs generated from `.src` files](https://github.com/erlware/relx/pull/700)
- [Only create `$RUNNER_LOG_DIR` when `start` is called in extended start script](https://github.com/erlware/relx/pull/699)
- [Fix inclusion of vm.args.src in tarball](https://github.com/erlware/relx/pull/698)
- [Fix parameter shift on win32 for extension commands](https://github.com/erlware/relx/pull/695)
> upgrade relx to 3.30.0

- .cirrus.yml
Just need to get the github application enabled for this repo. I sent a request to the erlang account to do so through github but I don't know who that goes to.
> add cirrus ci config to test against linux, osx and windows

- src/rebar_app_utils.erl
- test/rebar_compile_SUITE.erl
Resolves #980 
This currently just checks for the existence of the description and applications
keys and that the applications list has kernel and stdlib in it.
If there are other things that could be linted, I would be happy to add them.
> Add basic linting for .app file

- src/rebar_prv_install_deps.erl
- src/rebar_resource_v2.erl
- test/rebar_deps_SUITE.erl
- test/rebar_install_deps_SUITE.erl
Changes
```erlang
===> Upgrading lager ({pkg,<<"lager">>,<<"3.6.8">>})
===> Downloaded package, caching at /home/pete/.cache/rebar3/hex/hexpm/packages/lager-3.6.8.tar
===> No upgrade needed for amqp_client
===> No upgrade needed for jsx
===> Upgrading lager ({pkg,<<"lager">>,<<"3.6.9">>})
===> Version cached at /home/pete/.cache/rebar3/hex/hexpm/packages/lager-3.6.9.tar is up to date, reusing it
```
into
```erlang
===> Upgrading lager v3.6.8
===> Version cached at /home/pete/.cache/rebar3/hex/hexpm/packages/lager-3.6.8.tar is up to date, reusing it
===> No upgrade needed for amqp_client
===> No upgrade needed for jsx
===> Upgrading lager v3.6.9
===> Version cached at /home/pete/.cache/rebar3/hex/hexpm/packages/lager-3.6.9.tar …
```
> format hex packages in a nice/human way

- .cirrus.yml
This never passes even if it works on Windows 10 machines and on Circle
CI's runs.
> Disable windows on Cirrus CI

- .cirrus.yml
- .travis.yml
- rebar.config
- src/rebar.hrl
- src/rebar_utils.erl
- fixes some bad typespecs that crashed tests on OTP-22
- removes namespaced_types workaround from when `dict()` became `dict:dict()`
- deprecates OTP-17 while adding OTP-22 to keep our version window identical (done in CI)
> OTP-22.0 readiness

- src/rebar_app_discover.erl
- test/rebar_compile_SUITE.erl
Overrides should apply to a layer below where they are declared. This
patch makes it so if the project root is an application (i.e. it isn't
'root' and therefore not an umbrella project), we omit applying
overrides in rebar_app_discover.
This in turn required changing a bunch of tests, because all the tests
worked with the idea that all overrides applied to all apps to validate
that they get inherited properly. The changes re-structure the cases so
they are written with an umbrella app, demonstrating that the changes
stick.
This addresses https://github.com/erlang/rebar3/issues/2082 partially (still need to add docs)
The big risk here is whether any important project in the wild
relied on the bad application of at-large overrides to make their main
app in a non-umbrella work. I'm thinking …
> Do not apply overrides to a root application.

- src/rebar_prv_shell.erl
> add support for reading in environment variables from a file

- src/rebar_utils.erl
There was a bug in latest rebar3 when running rebar3 ct on OTP 17.5. The ct process would be terminated automatically without any error printed. 
After digging it turned out the configuration file, either defined in rebar.config or passed by parameter --sys_config is not loaded properly when running rebar3 ct. 
From the release here: https://github.com/erlang/otp/releases/tag/OTP-17.0 we can see {persistent, boolean()} is supported from otp 17, so when reread_config, rebar3 should call application:set_env(App, Key, Val, [{persistent, true}]) for OTP releases **>** 17. 
After the modification, locally rebar3 ct now works properly.
> bug when reread_config running on OTP 17

- .cirrus.yml
Maybe this will work for publishing escripts when a new release is tagged.
> try CIRRUS_TAG != '' for triggering cirrus for new tags

- src/rebar_app_utils.erl
- src/rebar_prv_compile.erl
- test/rebar_compile_SUITE.erl
This allows to reduce the number of noise to only checking deps' app
files when they're built, rather than on every run.
Since main apps and checkouts are still compiled every time, the linting
takes place there and then with a higher frequency.
Potential alternative implementation to #2081
> Only lint app files when compiling

- src/rebar_compiler_erl.erl
This fix addresses an issue when compilation of a dependency fails due to some configuration change.
The crash report `Uncaught error: {badmatch,{error,enoent}}` is not helpful for figuring out the cause of the crash, so the `Source` file name is added to the exception thrown.
> Make missing file report more comprehensive

- src/rebar_dir.erl
- test/rebar_dir_SUITE.erl
This PR allows one to specify the REBAR_GLOBAL_CONFIG_DIR via an env var. The env var takes precedence over `rebar_global_config_dir`  in state which in turns takes precedence over the fallback value of $HOME. 
This came up in light of https://github.com/tsloughter/rebar3_hex/issues/113
>  Support rebar config dir env var

- src/rebar_prv_edoc.erl
- test/rebar_edoc_SUITE.erl
- test/rebar_edoc_SUITE_data/foo/apps/foo/rebar.config
- test/rebar_edoc_SUITE_data/foo/rebar.config
This adds an additional loading and merging of options for EDoc using
the values from the top-level along with those specified in the
rebar.config of an umbrella application.
The app-specific config values are prepended to the global ones; this
can likely cause some problems with manual path handling, but is
unlikely to happen in practice and the rest seems to work fine based on
order
Fixes the issue in #2114
> Ensure EDoc opts in umbrella apps are respected

- src/rebar_app_discover.erl
- src/rebar_prv_app_discovery.erl
- test/rebar_discover_SUITE.erl
This supercedes #2112 by incorporating its fix, adding tests to it, and patching up cases that weren't properly covered by the patch.
> Fix crash when a dependency is missing app.src file

- src/rebar_prv_dialyzer.erl
The `rebar3 dialyzer` command crashes when `debug_info` is missing (or `no_debug_info`) with an obscure message about Core Erlang:
```
$ rebar3 dialyzer
===> Compiling rf
===> Dialyzer starting, this may take a while...
===> Updating plt...
===> Resolving files...
===> Updating base plt...
===> Resolving files...
===> Removing 194 files from "/Users/jkakar/.cache/rebar3/rebar3_22.0.1_plt"...
===> Adding 9 files to "/Users/jkakar/.cache/rebar3/rebar3_22.0.1_plt"...
===> Error in dialyzing apps: Analysis failed with error:
Could not scan the following file(s):
Could not get Core Erlang code for: /Users/jkakar/src/github.com/rufus-lang/rufus/rf/_build/default/lib/rf/ebin/rufus_typecheck_func_return_type.beam
Could not get Core Erlang code for: …
```
> rebar3 dialyzer: Warn when debug_info is disabled

- src/rebar_utils.erl
OTP kernel application use "logger_level" configuration for configuring
level in primary configuration.
rebar3 uses "logger_info" for this purpose - ths is little bit confusing
and probably mistake.
This commit will unify behavior between kernel and rebar3o
Fixes: 0303567d95f0 ("Reload logger config in shell")
> Fix reloading logger_level

- src/rebar_compiler_erl.erl
Ey up,
I've got a fair sized purerl project (https://github.com/purerl/) and noticed it was taking quite a bit of time to compile suddenly after a recent rebar update, it was hanging between
```
===> run_hooks("/home/robashton/[redacted]/apps/[redacted]", pre_hooks, erlc_compile) -> no hooks defined
------ HANG IS HERE
===> erlopts [ redacted ]
```
So I dug into the source code to work out why this was the case.
https://github.com/erlang/rebar3/blob/master/src/rebar_compiler_erl.erl#L81
Is the start of my issues, each file generated by the purerl compiler has -file attributes up the wazoo, with each function having a reference back to the original .purs file in my source/package structure. For example
```purescript
-file(".psc-package/id3as-20190706_2/arrays/v5.0.0-erl1/src/Data/Array/NonE …
```
> de-duplicate dependency list in rebar_compiler_erl.erl

- src/r3_hex_api.erl
- src/r3_hex_api_key.erl
- src/r3_hex_api_package.erl
- src/r3_hex_api_package_owner.erl
- src/r3_hex_api_release.erl
- src/r3_hex_api_user.erl
- src/r3_hex_core.erl
- src/r3_hex_core.hrl
- src/r3_hex_erl_tar.erl
- src/r3_hex_erl_tar.hrl
- src/r3_hex_filename.erl
- src/r3_hex_http.erl
- src/r3_hex_http_httpc.erl
- src/r3_hex_pb_names.erl
- src/r3_hex_pb_package.erl
- src/r3_hex_pb_signed.erl
- src/r3_hex_pb_versions.erl
- src/r3_hex_registry.erl
- src/r3_hex_repo.erl
- src/r3_hex_tarball.erl
- src/r3_safe_erl_term.xrl
version 0.5.1 is a maintenance release of hex_core specifically for rebar3 which contains a configuration update. Prior to v0.5.1 if no repo_organization key was set this could result in a function clause error. The behavior is to now set repo_organization to undefined in this case.
> Update vendored in hex_core to version 0.5.1

- src/rebar_prv_edoc.erl
- test/rebar_edoc_SUITE.erl
When in umbrella mode (or through multiple profiles), users can specify
macros for EDocs based on either the {def, ...} or the {macros, ...}
arguments.
This patch replaces the prior options merging for umbrellas to use the
rebar3 tup_umerge utils to remove identical duplicates while preserving
correct ordering, and manually merges the {macros, ...} definitions
while ke eping the correct precedence rules since these appear (given
their behaviour) to be all individually extracted and passed as `{d,
...}` to  the compiler so that epp expands them. This compiler
function freaks out on any re-defined macros and explodes.
Do note that the macros with `{def, ...}` are edoc macros and do not
suffer from that issue, safely deduplicating multiple definitions.
this fixes #2131
> Fixing duplicate macro definition in umbrella edoc

- src/rebar_state.erl
Found this because one of the `rebar_mix` providers was returning an error tuple and that caused rebar3 to crash since it tried to simply append a `"\n"`
I also change the log type to warning since it doesn't, and shouldn't, stop execution if a provider fails to init since we don't know if it will be used or not.
> format error from provider init and print as warning

- README.md
Just stumbled across a couple typos.  Looks like there was a missing word in "we using".  And I added a comma separating the subordinate clause "For binary packages".
Fun stuff.
> Fix a couple typos in readme

- THANKS
- src/rebar_dir.erl
- src/rebar_relx.erl
- test/rebar_release_SUITE.erl
As proposed and refined in issue [1254](https://github.com/erlang/rebar3/issues/1254).
> Support `profile_string` overlay var in releases

- bootstrap
Otherwise we only get silent failures. This has been fixed a while ago
in mainline rebar3 but never in the bootstrap script.
> Handle missing OTP apps better

- rebar.config
- rebar.lock
- src/rebar_templater.erl
- test/rebar_new_SUITE.erl
Fixes #2161 
Since we generate text or erlang files, it seems useless to escape HTML by default.
As a drive-by thing, I updated bbmustache to its latest version.
> Disable bbmustache escaping

- src/rebar_prv_clean.erl
- test/rebar_compile_SUITE.erl
This will allow project with larger dependencies sets to clean only the
apps they want to when testing or changing small things, rather than
forcing a rebuild of the whole dep set.
Also allows cleaning up apps, not just deps.
> Allow cleaning specific apps or deps only

- src/rebar_dist_utils.erl
Windows does not have the same quoting rules as Unix so we need to use platform independent quoting. Also for os:cmd like operations we do not expect the program to read any input so in order for it to work on windows we should put `-noinput` there.
See #2113 and https://bugs.erlang.org/browse/ERL-994 for more details.
> Fix epmd start on windows

- src/rebar_string.erl
This function was used for trimming the version from a `{file, File}` app
vsn in .app.src but caused a crash because it did not exist.
> add rebar_string:trim function for removing all leading/trailing whitespace

- src/r3_hex_api.erl
- src/r3_hex_tarball.erl
- src/rebar_git_resource.erl
- src/rebar_utils.erl
Team RabbitMQ tests OTP versions from 20.3 to master in our CI/CD pipelines. Recent OTP master changes introduce additional warnings that make Rebar bootstrap fail.
Unfortunately, there is no URI utility function module that's both available in OTP 20 and not deprecated in OTP 23. So this PR suppresses a few warnings for now. I hope that's acceptable.
> OTP 23 [master] compatibility

- src/rebar_hex_repos.erl
In r3_hex_core.erl we set default hex config. For example, we set the
api_organization to be undefined. By merging the hex auth config into
the default config this way round we allow users to override the default
config.
> Allow users to override default hex auth config

- THANKS
- src/r3.erl
- src/rebar_agent.erl
Fixes #2199. async_do with arguments is useful for debugging a particular suite/test
with r3:break()
Example session:
Add r3:break() in recompile_when_hrl_changes test in test/rebar_compile_SUITE.erl
rebar3 shell
...
1> r3:async_do(default, ct, "--suite=test/rebar_compile_SUITE.erl --case=recompile_when_hrl_changes").
ok
Running Common Test suites...
%%% rebar_compile_SUITE:
=== BREAK ===
2> r3:resume().
ok
3> .
All 1 tests passed.
> Allow passing arguments in r3:do and r3:async_do

- src/rebar_prv_shell.erl
This warning is emitted every single time one starts a shell with applications
configured for automatic startup (e.g. `{shell, [{apps, [cowboy]}]}`).
Infortunately it does not make any sense: people who use this feature need it
to interact with their application or library during development, and are
therefore subjected to the warning every single time they start the shell even
though this is the right way to use it.
While the shell is not to be used to run applications in productions, those
who do it won't be stopped by a warning.
Ultimately, the warning annoys people who use the feature as intended, and do
nothing to stop people who abuse it. Thus I believe it should be removed.
See https://github.com/erlang/rebar3/issues/2206.
close #2206
> remove warning when booting applications in the shell

- src/rebar_prv_dialyzer.erl
- test/rebar_dialyzer_SUITE.erl
Usage:
1. Command `rebar3 as test dialyzer` adds modules from `test` directories for check due to the fact that rebar3 adds "test" to `extra_src_dirs` in test profile.
OR
2. Add directories you want to run dialyzer also on to `extra_src_dirs` in your rebar.config:
```erlang
{profiles, [
{dp, [{extra_src_dirs, ["tests"]}]}
]}.
```
and run `rebar3 as dp dialyzer`
> Run dialyzer for extra_src_dirs

- src/rebar_utils.erl
The problem is that the shell util handlers receive a byte stream, which
we handle as a list coming from a port. However the byte stream is utf-8
encoded in most systems, which breaks encoding expectations (binaries
only) for Erlang.
This patch turns the list of characters to a binary for all shell calls,
before re-encoding it properly as unicode lists to keep the format compatible.
Fixes #2205
> Proper Unicode handling in port process output

- src/r3_hex_api.erl
- src/rebar_git_resource.erl
- src/rebar_hex_repos.erl
- src/rebar_uri.erl
- src/rebar_utils.erl
- test/rebar_uri_SUITE.erl
- test/rebar_utils_SUITE.erl
See #2191 for the background.
The new module attempts to act as a shim between `http_uri` (deprecated in OTP 23) and `uri_string` (available as of OTP 21+) with as little wheel reinvention as possible.
> Introduce rebar_uri to avoid deprecation warnings on OTP 23 [master]

- vendor_hex_core.sh
We're planning to move the vendor.sh script from hex_core to hex,
but if you'd prefer it stays there it's not a problem. Thought by
moving it here I think it's a bit easier to use anyway.
cc @ericmj @starbelly
> Add vendor_hex_core.sh

- src/rebar_compiler.erl
- src/rebar_compiler_dag.erl
- src/rebar_prv_compile.erl
This is another tricky commit towards replacing the current module
analysis with EPP. The compiler DAG is now being shared across multiple
applications being compiled, rather than a per-application basis, which
promises to allow better ordering, parallelism, and more thorough
invalidation of runtime dependencies when they are modified.
This however required changes:
- The compiler DAG is no longer private to `rebar_compiler`, and has
been extracted to the `rebar_compiler_dag` module
- The compiler DAG is now started by the `rebar_prv_compile` module,
which oversees the calls to `rebar_compiler` for each OTP application
- The compiler DAG has been refactored to use a "dirty flag" to know if
it was modified, rather than just tracking modifications in a
functional manner, since the scope …
> Split up the compiler DAG

- src/rebar.hrl
- src/rebar_config.erl
The code was written at the time only one lockfile version was being
explicitly tagged (1.1.0), and all the other older ones were untagged.
In introducing the 1.2.0 format for external hashes, the current version
check still took place, but no provisions were made to explicitly check
between older or newer versions. As such, rebar3 would warn (prompting
people to upgrade) every time a lockfile on the 1.1.0 version (which is
likely over 99% of those in the wild as of today) would be encountered,
we'd prompt people to upgrade.
This patch introduces a constant for the list of supported tagged
versions for config/lock files, which allows to drop warnings when
rebar3 can transparently upgrade the lock file for the user.
It pre-supposes a potential "unsupported lock file" error could be added …
> Eliminate lock file warnings when upgrading from 1.1.0 locks

- bootstrap
When recompiling rebar3 itself, the path swaps and cleaning removes the
modules loaded from _build/bootstrap, but the VM still manages to
discover those in _build/prod from previous builds of the escript when
building the new escript, which causes weird failures when compilers get
modified between releases.
The fix is to just clear _build/prod as part of the init of the
bootstrap script, the same way we already clear _build/bootstrap.
> Fix bootstrap crashes when compilers get modified

- src/rebar_dir.erl
This enables relative paths for checkouts_dir configuration variable.
> rebar_dir: return _checkouts path in a canonical form

- src/rebar_git_resource.erl
It is quite normal to have git 2.17.1 on MacOS X.
> rebar_git_resource: allow non-single-digit git versions

- src/rebar.hrl
- src/rebar3.erl
- src/rebar_pkg_resource.erl
This closes PR #2197 and its parent issue #2196 
It looks like the value of `rebar_packages_cdn`  being used as the `repo_url` was being used up until https://github.com/erlang/rebar3/pull/1884 , though it is no clear why.
> re-enable use of rebar_packages_cdn in rebar_pkg_resource

- src/rebar_prv_bare_compile.erl
Currently, we just write to ebin/ in the current working directory; this
implies that the source _should_ always be in the same subpath as the
ebin/ directory.
In the cases of utils like Mix, which store downloaded dependencies in
deps/ and artifacts in _build/, this may force more rebuild or less
caching that would be ideal.
This PR adds --outdir / -o as options to the bare compiler, which lets
the user specify another path, with a default kept to $CWD.
> Allow specifying the outdir in bare compiler

- src/rebar_git_resource.erl
- src/rebar_hex_repos.erl
- src/rebar_uri.erl
- src/rebar_utils.erl
- test/rebar_uri_SUITE.erl
- test/rebar_utils_SUITE.erl
Reintroduces patches from #2195 but with some variations to unbreak the branch:
- Normalize path behaviour to always be "/" across versions
- Normalize port visibility behaviour to match input string when
appending
- restore rebar_utils function to avoid breaking random plugins that
peek into our libs for their stuff
- Support URIOpts equivalent and protocol-based overrides; the behaviour
there is not necessarily consistent across versions in terms of what
ports are returned (http_uri always returned a port but uri_string
only returns it if explicitly specified -- we choose the latter
behaviour on newer releases), but the calls work to ensure URI parsing
consistently works across versions
The latter judgement call is a bit of an odd one; for consistency we
could always mandate ports, but …
> OTP-23 compatibility and warning removal

- src/rebar_prv_shell.erl
Fixes https://github.com/erlang/rebar3/issues/2242
Filters out dead processes that can't return process info.
> Fix race condition in rebar_prv_shell boot

- bootstrap
- rebar.config
- src/rebar_compiler.erl
- src/rebar_compiler_dag.erl
- src/rebar_compiler_epp.erl
- src/rebar_compiler_erl.erl
- src/rebar_prv_compile.erl
- test/rebar_compile_SUITE.erl
- test/rebar_compiler_dag_SUITE.erl
- test/rebar_compiler_epp_SUITE.erl
This continues the Compiler refactor sequence in #2200 and switches code analysis to be done with EPP, which can understand macros and conditionally expand paths.
At the same time, this PR expands things to analyze all project Apps as one unit, which in turn allows properly detecting cases such as behaviours, parse transform, or include files changing in other applications forcing a re-build of the local ones.
The one limitation is that EPP won't easily allow the case where a public include file includes private include files, and the public include file is included by a foreign module; in such a case changes to the private headers won't be seen outside of their original app.
The apps are sorted in proper build order according to the new DAG, and should allow for interesting parallelism …
> Switch to EPP analysis covering all apps at once when compiling

- bootstrap
- src/rebar_utils.erl
Solves #2071, IPV6 support for proxy, by trying to resolve proxy
host name without specific IP address family. If it fails, it
attempts a different IP family, and in case that succeeds, it
sets up HTTP client profile to use IP family that worked.
> rebar3: ipv6 support for proxy

- src/rebar_git_resource.erl
rebar3 uses following git invocation when it needs to generate
vsn to put into app.src:
git -c color.ui=false log --oneline --no-walk --tags --decorate
It may return something like some_repo/some_project/12345678,
with some characters preceding actual hash. This leads to some
unusual version written into application resource file, e.g.
{vsn, "some_repo/some_project/123456678"}.
This does not work well with semantic versioning, and also
produces unexpected OTP application names and folder names,
e.g.
myapp-some_repo/some_project/12345678
> rebar_git_resource: fix {vsn, git} parser

- src/rebar_dir.erl
- src/rebar_file_utils.erl
- test/rebar_file_utils_SUITE.erl
As suggested in #2223, `make_absolute_path/2` and `make_normalized_path/2`
should, instead of being exported in `rebar_dir`, be moved to
`rebar_file_utils` and renamed (decided to simply remove the `make`
from their names since in that module there is already a path related
function called `canonical_path`).
> Move `absolute_path/2` and `normalized_path` to `rebar_file_utils`

- src/rebar_prv_common_test.erl
Implements #1734. In case of not being able to create the
symlink rebar3 warns through `?DEBUG`.
> Add symlink to the `ct_run` of the last commot test run

- src/rebar_prv_xref.erl
Closes #2108. Changes the path to be printed to a relative path
to the current directory.
Also removes the `exports_not_used` warning from the default ones,
as Tristan suggested.
> xref improvements: now outputs relative file paths

- src/rebar_prv_bare_compile.erl
Would close erlang#2202. In case of no apps found when calling
`rebar_state:project_apps(State)` rebar3 now throws an error with
a warning.
> Return an error if no apps are found when using bare compiler

- src/rebar_compiler.erl
- src/rebar_compiler_dag.erl
- src/rebar_compiler_erl.erl
- src/rebar_erlc_compiler.erl
- test/rebar_compile_SUITE.erl
This allows to do quicker re-compile option validation by not requiring
to access the disk and check all candidate erlang files for option
changes. This also opens up the way to compilers that produce more than
one artifact per file.
This is not exactly optimal on all fronts but should still be faster than the old thing.
Related to #2200
> Track build artifacts in DAG

- src/rebar_prv_escriptize.erl
setlocal not required as not setting rebarscript
rebarscript not required as we can use %~dpn0 directly
%~dpn0 is (d)irectory, (p)ath and (n)ame of script file, without (e)xtension.
**NOTE:** On windows, a clean clone of rebar3, bootstrap.bat, rebar3 escriptize, followed by rebar3 ct fails producing a rebar3.crashdump.
It also constantly says 
_===> Rebar3 detected a lock file from a newer version. It will be loaded in compatibility mode, but important information may be missing or lost. It is recommended to upgrade Rebar3._
Is that normal for master?
> Simplify windows script

- src/rebar_prv_dialyzer.erl
- test/rebar_dialyzer_SUITE.erl
This patch enables two features:
* in rebar.config, {diazlyer, [{plt_apps, all_apps}]} makes rebar3 to
add all project files into PLT for subsequent analysis
* rebar3 ct --app=myapp allows single application success typing
This allows workflow suitable for large codebases:
* "rebar3 ct dialyzer --succ-typings=false" to build PLT with all apps
* "rebar3 ct dialyzer --app=myapp" to perform success typing of myapp
> rebar3 dialyzer support: single-app success typing, project apps in PLT

- .github/workflows/main.yml
- .github/workflows/nightly.yml
- .github/workflows/publish.yml
The `aws` command is installed in `ubuntu-latest` but the commands were running in the container without it. Using `setup-erlang` it installs to the VM instead of running a container.
> use setup-erlang instead of container for github action nightly

- src/rebar_dist_utils.erl
executing `rebar3 shell` when epmd is not running causes a crash log
```erlang
=SUPERVISOR REPORT==== 5-May-2020::10:44:23.655292 ===
supervisor: {local,net_sup}
errorContext: start_error
reason: {'EXIT',nodistribution}
offender: [{pid,undefined},
{id,net_kernel},
{mfargs,{net_kernel,start_link,
[['dderl@127.0.0.1',longnames],false]}},
{restart_type,permanent},
{shutdown,2000},
{child_type,worker}]
=CRASH REPORT==== 5-May-2020::10:44:23.654275 ===
crasher:
initial call: net_kernel:init/1
pid: <0.550.0>
registered_name: []
exception exit: {error,badarg}
in function  gen_server:init_it/6 (gen_server.erl, line 358)
ancestors: [net_sup,kernel_sup,<0.46.0>]
message_queue_len: 0
messages: []
links: [#Port<0.49>,<0.547.0>]
dictionary: [{longnames,true}]
trap_exit: true
status: running
heap_size: …
```
> checking epmd is started without a crash

- rebar.lock
- src/rebar.app.src
- src/rebar_app_discover.erl
- src/rebar_app_info.erl
- src/rebar_app_utils.erl
- src/rebar_fetch.erl
- src/rebar_git_resource.erl
- src/rebar_git_subdir_resource.erl
- src/rebar_prv_path.erl
- test/mock_git_subdir_resource.erl
- test/rebar_compile_SUITE.erl
- test/rebar_test_utils.erl
Todo:
- Add tests to the common test suite. Currently been testing with a new test case added to https://github.com/tsloughter/rebar3_tests
- Clean up the continual parsing of "source". Continually using a 2, 3 or 4-tuple depending on how the source was defined is a mess. This should probably become a record.
- Figure out what format is best so that old rebar3's has a useful error or warning about not supporting a dep's definition if it encounters the new sparse dir option
- Bump the lock version
> sparse-git checkout dependencies

- rebar.config.sample
- src/rebar.hrl
- src/rebar_app_utils.erl
- src/rebar_dir.erl
- src/rebar_env.erl
- src/rebar_prv_plugins.erl
- test/rebar_compile_SUITE.erl
- test/rebar_test_utils.erl
> output checkouts compilation to _build/<profile>/checkouts/

- src/rebar_compiler.erl
- src/rebar_compiler_dag.erl
- src/rebar_compiler_erl.erl
- src/rebar_parallel.erl
- src/rebar_prv_compile.erl
This is a big PR, more easily reviewed by commit.
- [Extract artifact tracking to DAG module ](https://github.com/erlang/rebar3/commit/90bead231032af39dcdf54dde47d85259cd1030a): I just cleaned up a thing that was a bad abstraction, and re-located artifact tracking within the DAG module. This was necessary when attempting an [unsuccessful parallelism effort](https://github.com/erlang/rebar3/compare/master...ferd:parallelize-compile) that didn't yield good results in practice. Also fixes a bug where `erl_first_file` entries weren't properly tracked in the DAG.
- [Extract & Generalize parallel queue from compiler](https://github.com/erlang/rebar3/commit/235543d398087694a1cc86ce558cb0794be4f4bd) where I take @max-au's code to turn module-level compiling parallel and moved it out to a …
> Another Compiler Refactor: Performance & Cleanup

- src/rebar_file_utils.erl
- test/rebar_compile_SUITE.erl
- test/rebar_file_utils_SUITE.erl
- test/rebar_hooks_SUITE.erl
Starting with OTP-22, Erlang started changing how volume names are handled in
windows: filename:join/1 drops drive letters, filename:split/2 and
file:absname/1 use c:/ as a form instead of c:\\\\
We adjust the file_utils and their tests accordingly.
Rebar3.14 has new tests that were not windows ready and those are fixed.
Relx has two failing tests that are not covered in this branch.
Tested in Windows 10 with Powershell.
> Fix tests in Windows; adjust absolute paths

- src/rebar_prv_escriptize.erl
Since the compiler refactor changed the order of steps and all hooks get
applied at once, knowing which app is being escriptized isn't really
obvious, particularly when many apps individually define their own 'main
app' and they get run at once.
This adds the name of the main app being run when escriptizing it to make
it clear what goes on, especially if there are failures.
This was reported in https://github.com/erlang/rebar3/pull/2211#issuecomment-615937628
> Name the app being escriptized

- rebar.lock
- src/rebar_git_resource.erl
Not all of the changes to the git resource were reverted when
the sparse checkout support was moved to a new resource,
git_subdir_resource. This fixes issues caused by these changes
that were accidentally left.
> revert change to lock for regular git resource from PR #2239

- .github/workflows/main.yml
- .gitignore
- bootstrap.ps1
- rebar.config
- rebar.config.sample
- rebar3.ps1
- src/rebar_prv_escriptize.erl
You must have been expecting this ;)
This adds bootstrap.ps1 and a powershell escriptize wrapper for windows.
rebar.config setting is, for example, `{escript_wrappers_windows, ["cmd", "powershell"]}` which will write BOTH <escript>.cmd and <escript>.ps1.
Can be set to both, one, the other, or none at all.
Updated rebar.config to create both.
Updated workflow to make use of ps1 version.
> Add powershell script generation option for escriptize on windows; use for rebar3 itself

- rebar.config
- rebar.lock
- src/rebar_relx.erl
I haven't gone over this closely after realizing its blocked by https://bugs.erlang.org/browse/ERL-715 but I figured I'd still open this PR for reviews.
I may work on resolving the `release_handler` issues myself so this can be merged sooner than later.
> add --all option for release building in parallel

- src/rebar_prv_bare_compile.erl
None of the version checks are considered safe enough by mix
maintainers, and so the agreed upon mechanism is to just set this
environment variable, which will be supported implicitly by rebar3
versions that can handle it.
This lets build artifacts (aside from some priv/ issues with plugins) to
properly be located within their build folder rather than the deps
folder, as the --outdir switch would otherwise have done.
CC @starbelly was this merged in mix?
> Support ENV var for mix in the bare compiler

- src/rebar_git_subdir_resource.erl
Commit 029cbcc7 changed the return value of `rebar_git_resource:lock_/2`
> Fix git_subdir after "revert change to lock for regular git resource"

- src/rebar_utils.erl
As reported by Alexey Pronin, this would let people potentially pass in
URLs that can call to command execution.
While running arbitrary code is kind of our bread and butter, it makes
sense to at least play nicely and escape more characters:
- the pipe (`|`) which can be used to run subcommands
- the tab (`\t`) which the shell interprets as a space.
- the home directory (`~`) just because the expansion could behave funny
- redirection (`<` and `>`) to avoid problems with data setting up
streams
> Escape more characters for shell stuff

- src/rebar_app_discover.erl
- src/rebar_app_info.erl
- src/rebar_otp_app.erl
- src/rebar_prv_compile.erl
- src/rebar_state.erl
I forgot to push this and don't remember if it was complete or not.
The issue was pointed out by @max-au with the latest relx. It would get the vsn like, `{cmd, "..."}` or `git` instead of what that evaluates to. The change is to have a separate key for the evaluated version and the original version.
> add vsn that is the evaluated application vsn

- src/rebar_opts.erl
- test/rebar_compile_SUITE.erl
This patch aims to make rebar3 delete a dependency by first looking for
its name (fixing `del` on hex dependencies) and if that isn't found
remove it as always, keeping its current behaviour with the `del` override.
Closes #2126.
> Match on dep name in overrides

- src/rebar_prv_compile.erl
- src/rebar_prv_plugins_upgrade.erl
- test/rebar_plugins_SUITE.erl
this fixes the issue where using 'rebar3 plugins upgrade P'
would result in a plugin's .app file having an empty
modules list. The code this replaces hadn't been touched
since rebar3 3.0.0-beta.3 and a lot of improvements have
gone into dep handling and the compiler since then. This
change should take advantage of those changes.
> prv_plugins_upgrade: fix compilation of upgraded plugins

- src/rebar_templater.erl
Hi,
I wanted to have an easy way to select different kind of license for my projects based on defined template. Unfortunately, rebar3 supports variable templating only on the target files and templates' names. I added the support of templating in the `From` part of the execution. That means it is now possible to add a variable in the source and not only the destination. Here an exemple:
```erlang
{description, "Custom app with ct test and c_src directory"}.
{variables, [
{license, "apache-2.0", "default license"}
]}.
{dir, "{{name}}"}.
{dir, "{{name}}/src"}.
{dir, "{{name}}/test"}.
{dir, "{{name}}/c_src"}.
{template, "_app/LICENSE-{{license}}", "{{name}}/LICENSE"}.
{chmod, "{{name}}/LICENSE", 8#644}.
{template, "_app/README.md", "{{name}}/README.md"}.
{chmod, "{{name}}/README.md", 8#644}. …
```
> Add templating feature for "from" file/template

- rebar.config
- src/rebar_prv_common_test.erl
rebar3 would crash if the option `{keep_logs, N}` was present and
there were more than N run directories in the log dir, so if the
option is found we keep the N-1 newest directories and delete the
rest.
While we are at it, as this should fix the crash, let's limit the
number of logs runs to keep from test runs in rebar3 to 5.
> Fix keep_logs option crashing when having more than N directories

- src/rebar_prv_common_test.erl
Would otherwise crash at `lists:split/2`.
> Add extra pattern matching clause to not crash handling with keep_logs

- src/rebar_compiler_dag.erl
- src/rebar_compiler_epp.erl
- src/rebar_compiler_erl.erl
This PR contains 3 commits, that work best together, but could also be applied independently.
First, for large projects, rebar_compiler_erl spends vast majority of time re-scanning file system in order to find parse_transform/behaviour file by the name (e.g. "cth_readable" parse_transform that is applied to all files for "TEST" profile). When there are several hundred directories to scan, it becomes a bottleneck.
Caching results of this scan helps to bring down analysis of a large repo from 11 minutes to just 3, on 8-core intel CPU.
Second improvement runs EPP concurrently within an application, saving considerable amount of time for large applications.
Last change circumvents documented interfaces for digraph save/load, and uses internal undocumented structures. Better approach would be …
> rebar3 Erlang compiler: performance improvements

- rebar.config.sample
I was a bit surprise at the fact the option is named `--shell` on the CLI, but `script_file` in `rebar.config`, so add this small example in the hopes this doesn't surprise others.
I don't actually know if the online documentation features a section on what `rebar.config` is supposed to look like, for the various "commands".
> Feature shell.script_file in rebar.config.sample

- src/rebar_prv_local_install.erl
Removes all existing applications in `~/.cache/rebar3/lib` while leaving the top-level directory (`lib`) intact.
Should close #2307, as `local upgrade` calls to `local install`'s `extract_escript`.
I did not find any tests related to either module, if there's any let me know so that I can update this PR :)
> Extract rebar3 libs in a version dependent directory when using local commands

- src/rebar_prv_lock.erl
- src/rebar_prv_upgrade.erl
- src/rebar_state.erl
- test/rebar_compile_SUITE.erl
Closes #2334.
Any feedback on the wording or how I am getting the checkout dependencies is welcome :)
> Improve warnings about checkout dependencies when locking and upgrading

- src/rebar_compiler_epp.erl
- test/rebar_compile_SUITE.erl
This was due to a subtle mistake in the new code in
https://github.com/erlang/rebar3/pull/2322 which optimized the search
behaviour of files not found by EPP. The patch mistakenly always kept
the top-level src/ directory for an app even if it did a lookup in
recursive ones.
This patch tracks and maintains the proper subdirectory hierarchy. To
keep performance adequate, the lists:keyfind/3 function is used, which
is also now a NIF to the same extent as lists:member/2; manual lookups
would likely end up reducing performance, particularly in deep
hierarchies.
A test case has been added to track the regression.
Reported by @elbrujohalcon
CC @max-au
> Fix Recursive Behaviour Lookup Regression

- .github/workflows/publish.yml
The last release failed to upload to S3 automatically. I noticed the nightly action has been working and uses a different command, so switching this to match nightly and hopefully work next time.
> use 'aws cp' when copying escript to s3

- src/rebar_prv_xref.erl
The previous warning (`"Warning: ~ts is undefined function (Xref)"`) reinforces the idea that `xref` is not reporting the context, in this specific analysis type. In any case, it'll show up as a duplicate on the reports:
```erlang
===> Warning: ko:ko/0 is undefined function (Xref)
src/mylib_app.erl:12: Warning: mylib_app:start/2 calls undefined function ko:ko/0 (Xref)
```
I'm unaware of how to obtain the analysis scope, in this particular case. I'm also thinking that these options are basically mutually exclusive (`undefined_function_calls` v. `undefined_functions`).
> Prevent crash when function deemed undefined has no local context

- rebar.config.sample
... especially for those that rely on the sample `rebar.config` from the get-go.
Marginally related to #1904.
> Add xref_ignores to sample config file

- src/rebar_paths.erl
- src/rebar_prv_xref.erl
- test/rebar_paths_SUITE.erl
This commit changes mainly the `rebar_paths` module by adding a
new `runtime` target. When using that target, `rebar_paths:get_apps/2`
will, for each project app, find all their `applications` and
`included_applicactions` and filter those that could be found
in rebar3's state.
> Change xref paths to only those of runtime deps

- src/rebar_compiler_epp.erl
I experienced timeout error like (file names are modified because it happened in closed source build):
```
===> Failed to get dependencies for /xxx/src/foobar.erl
{timeout,{gen_server,call,
[rebar_compiler_epp,
{resolve,"supervisor.erl",
["/xxx/include",
"/xxx/src"]}]}}
```
This does NOT occur in my development environment but does
- on a small VM with single CPU core and a remote disk, and
- in continuous integration build environment (not sure what hardware/virtualization).
By adding explicit 60 second timeout, the error disappears.
-----
In my development environment (with relatively good CPU and SSD), I did some print-debug and found:
- is_dir call at https://github.com/erlang/rebar3/blob/master/src/rebar_compiler_epp.erl#L131 sometimes takes milliseconds to tens of milliseconds
- …
> Use infinity timeout for rebar_compiler_epp resolve call

- src/rebar_prv_as.erl
Before:
```
→ rebar3 as global plugins list                               
===> No entry for profile global in config.                                      
--- Global plugins ---                                                                                                                                             
rebar3_hex (6.9.6+build.293.ref85a6cb4)      
```
After:
```
→ rebar3 as global plugins list                               
--- Global plugins ---                                                           
rebar3_hex (6.9.6+build.293.ref85a6cb4)                                          
```
Fixes #2369
> Ignore `global` and `default` in empty profiles warning for `as`

- src/rebar_compiler_mib.erl
- test/rebar_compile_SUITE.erl
This is required for compile order to be maintained in a post-3.14 world.
Fixes #2372
> Specify dependencies for MIB files

- src/rebar_templater.erl
Looking into `bbmustache`'s code the crash can be fixed by always turning the author's name into a binary with `unicode:characters_to_binary/1`.
Closes #2374.
> Handle unicode in author's name in templates

- src/rebar_base_compiler.erl
> Patch `rebar_base_compiler` to handle extensions with no leading dot

- README.md
The link was missing a `tutorials` in the path.
> Update link for Rebar 2.x to Rebar3

- src/rebar_templater.erl
This commit changes rebar3 to check for name clashes of the
modules created from its templates with existing Erlang modules
to produce a non-blocking warning for each clashing module.
It does so by checking if any of the modules that will be created
is already defined in the path and, to do so, reimplements the function
`code:all_available/0` when rebar3 is used with a version of Erlang/OTP
older than 23.0, as said function was added in that release.
Should close #1386.
> Make rebar3 templates check for name clashes

- src/rebar.hrl
- src/rebar3.erl
- src/rebar_api.erl
- src/rebar_app_discover.erl
- src/rebar_base_compiler.erl
- src/rebar_compiler.erl
- src/rebar_compiler_dag.erl
- src/rebar_compiler_epp.erl
- src/rebar_compiler_erl.erl
- src/rebar_compiler_mib.erl
- src/rebar_core.erl
- src/rebar_erlc_compiler.erl
- src/rebar_fetch.erl
- src/rebar_file_utils.erl
- src/rebar_git_resource.erl
- src/rebar_hooks.erl
- src/rebar_log.erl
- src/rebar_parallel.erl
- src/rebar_pkg_resource.erl
- src/rebar_prv_compile.erl
- src/rebar_prv_install_deps.erl
- src/rebar_state.erl
- src/rebar_utils.erl
This is a progressive rework of https://github.com/erlang/rebar3/pull/2009. I'm hoping to drive a major improvement in usability by directly tying some behaviours to the config value that impacts things, we could get some discoverability out of it on top of friendlier debugging output.
Currently the following commits are part of the PR:
- Introduce Diagnostic Mode (82cc665):
?DIAGNOSTIC mode is intended to be used for rebar3 maintainers to debug
and understand issues. It shows all the things and all the data and
works with the assumption that people has intent to use the source code
to debug things. An equivalent call is added to `rebar_api`.
?DEBUG mode is promoted to user-oriented debugging, based on the idea
that what they care about is figuring out their interactions with the
tool. A …
> Rework DEBUG=1 mode to be user-centric output and introduce separate DIAGNOSTIC=1 mode for implementer-level logging

- src/rebar_pkg_resource.erl
- src/rebar_prv_plugins_upgrade.erl
Upgrading dependencies already checked for package updates before running
the upgrade task. Plugins didn't have that mechanism in place and that
made upgrading plugins over hex trickier since users could be stuck a
long time without running an update manually.
This fix mostly readapts existing dep code to the context of plugins to
look them up one at a time and run the update as part of the upgrade.
> Run pkg updates on plugin upgrades

- src/rebar_relx.erl
[Fix #1880]
From what I could gather these options were taken/copied from `relx` 3.x then `verbose`/`log_level` was removed from `relx` but the option stayed documented in `rebar3`.
> Remove verbosity option that was taken out in relx 4.x

- src/rebar_agent.erl
- src/rebar_compiler_dag.erl
- src/rebar_compiler_erl.erl
- src/rebar_fetch.erl
- src/rebar_parallel.erl
- src/rebar_paths.erl
- src/rebar_prv_common_test.erl
- src/rebar_prv_cover.erl
- src/rebar_prv_edoc.erl
- src/rebar_prv_escriptize.erl
- src/rebar_prv_eunit.erl
- src/rebar_prv_help.erl
This moves some more stuff to DIAGNOSTIC, and adds a few statements to DEBUG output that give hints towards options that can be used to impact results, and make for a more googleable experience.
Advertise the DEBUG=1 variable in the help output as well.
Example output for escriptize is pretty nifty now:
```
<previous providers elided>
===> Running provider: escriptize
===> Running hooks for escriptize in app rebar (/home/ferd/code/self/rebar3) with configuration:
===>    {pre_hooks, []}.
===> Building escript for rebar...
===> Creating escript file /home/ferd/code/self/rebar3/_build/default/bin/rebar3
===> bundled applications:
[getopt,erlware_commons,providers,bbmustache,ssl_verify_fun,certifi,
cth_readable,relx,cf,eunit_formatters,rebar]
===> escript options:
===>    {escript_shebang, …
```
> Reworking more of the DEBUG output to be friendly

- src/rebar_file_utils.erl
- src/rebar_utils.erl
Fixes #2371 
when match file link result, if output match ok fail, then recheck link target, if target is is link file already do nothing.
fix match error in `rebar_util:sh_loop`.
> Fix compile issue on windows when language is not english

- src/rebar_hex_repos.erl
- test/rebar_pkg_repos_SUITE.erl
(fixes tsloughter/rebar3_hex#184)
The issue was that the bytes were written "as is" on disk, while Erlang source files are expected to be utf8 (and no longer latin1) by default since Erlang/OTP 17.0 (as per https://erlang.org/doc/reference_manual/character_set.html)
e.g. byte <<200>> (0xC8) is not valid utf8, but was written as is, causing `file:consult` to raise an encoding error.
It is preferable not to rely on default behavior, and specify an encoding both at write and read time.
This PR specifies utf8 (probably more future-proof than latin1) when calling `file:write_file` and adds the encoding at the top of the file for future reads via `file:consult` (as per https://erlang.org/doc/reference_manual/character_set.html#source-file-encoding).
The test writes to the actual config at the …
> set explicit encoding when reading and writing hex config

- bootstrap
Downloading dependencies during build is not possible in some environments like nix.
Nix pre-download all the deps into `_build/default/lib` and disable internet access during build.
So, `_build/default/lib` shouldn't be deleted at startup.
> Support pre-fetched deps for nix.

- src/rebar_opts.erl
`del_deps` is used in `del_opts` and option is not always in dependency format.
> Fix endless recursion in del_dep

- test/rebar_compile_SUITE.erl
Completes the fix presented in #2381
Uses an existing test to simply inject the regression.
> Add regression test for dep override infinite loop

- bootstrap
- src/rebar_compiler.erl
- src/rebar_compiler_dag.erl
- src/rebar_compiler_erl.erl
- src/rebar_plugins.erl
- src/rebar_prv_compile.erl
- src/rebar_prv_install_deps.erl
- test/rebar_compile_SUITE.erl
- test/rebar_compiler_dag_SUITE.erl
This fix is done in three parts:
1. Add the compiler version to the data tracked in the DAG, and extract
it from source file (when the DAG isn't around) for comparisons. Then
on each build job, check for the compiler version as a build option
like every other one.
A change in compiler version represents a change in build options,
which triggers a rebuild
2. Make it work for deps. This is done by reworking DAGs metadata
annotations so that they contain the compiler version and can
invalidate the culling of deps done by the install_deps phase when
the DAG is mismatching, and then handing off the dep set to be
rebuilt more deeply with the regular definition in 1.
3. Make it work for plugins. This requires more work because plugins
that can find their ebin/ dir are assumed to be pre-built. …
> Trigger rebuilds when OTP compiler version changes

- src/rebar_hex_repos.erl
- test/rebar_pkg_repos_SUITE.erl
- add function that allows the complete removal of an entry from auth
config
- add test for rebar_hex_repos:remove_from_auth_config/2
- update test/rebar_pkg_repos_SUITE:auth_read_write_read/1 to use mocks so
we don't append to actual hex.config files
> Add rebar_hex_repos:remove_from_auth_config/2

- src/rebar_resource_v2.erl
Unless I understand the code wrong, the custom state always comes last in resource_run.
> Fix spec for download callback

- src/rebar_prv_path.erl
A first bash for conversation regarding issue #2420 
My initial thought was "I'll just do what rebar3 shell does", but that of course doesn't work because that would make everything very slow indeed, so instead I just add the calculated checkouts dir to the list that then gets filtered by an 'dir exists' clause.
As it stands, that would  mean that priv/src would be to the symlinks back to _checkouts, so maybe they'd  just be better off using checkouts_dir which would  do that for us..
> Attempt to add checkout location to rebar3 path

- src/rebar_relx.erl
There seems to be an intention in the relx:build_relup code to support `Release`, `ToVsn` and `FromVsn` to be `undefined`, but that does not work nor does the spec allow for it. So this PR fixes rebar_relx to work with `--relname` and `--relvsn` and informs the user that you have to give these options.
Another option would be to also fix relx:build_relup/4 to allow `Release`, `ToVsn` and `FromVsn` to be `undefined` to be undefined.
> Fix relup cmd arguments and add validation

- src/rebar_prv_shell.erl
The shell plugin has to reset the logger by fetching its configuration and
re-applying it later. In the current state, `maybe_reset_logger/1` will only
re-apply part of the configuration (the `config` key), which does not include
other settings such as filters and formatters.
The effect can be demonstrated by adding filters or formatters to `~/.erlang`
and running rebar3 shell on any project (without any --config argument, this
one reload the logger env; updating the kernel/logger environment in
`~/.erlang` fixes it).
For example:
```erlang
logger:set_handler_config(default, #{formatter => {logger_formatter,
#{template => ["> ", msg, "\n"]}}}).
```
This patch makes sure the default handler is re-created with its entire
original configuration.
> fix logger reset for the shell plugin

- .dockerignore
- Dockerfile
Based on the closest Alpine Erlang version currently supported by
rebar3. Allows people to mix and match different versions of
the Erlang VM and rebar3 using multi-stage docker builds.
> Add a docker recipe for rebar3 itself

- src/rebar_dir.erl
- src/rebar_prv_dialyzer.erl
Forgot I did this. Was going to wait until I updated all of the cases of files being output but meh..
> output relative paths in dialyzer provider

- .github/workflows/publish.yml
If this works, from now on creating a tag will result in a github release being created and escript being uploaded to it as an asset. So after tag is created we'll wait for github to create the release and then can edit it to add the changelog info to it.
> create release and upload escript for new tags

- src/rebar_relx.erl
- test/rebar_release_SUITE.erl
- test/rebar_test_utils.erl
This PR adds support for reading the relx configuration from a file when generating a release.
Rebar will continue to use the `rebar.config` relx section as the preferred source of truth, but if there is no such section it will use the configuration from default file `relx.config`.
However if the `--config` flag specifies a configuration file it will be preferred over of the configuration from `rebar.config` or `relx.config`.
I've added a test that should cover these different scenarios.
> Add support for relx config file

- src/rebar_compiler.erl
- src/rebar_compiler_dag.erl
- src/rebar_compiler_erl.erl
- src/rebar_prv_compile.erl
This patch fixes incorrect behaviour of rebar_compiler_epp that
finds dependencies in _build/test/lib/... folder when rebar3 is run with
test profile. It is caused by code:lib_dir() pointing to _build
directory (when ebin is added to code path). Problem originates in
OTP that expects "include" and "ebin" directories being next to each other,
but rebar3 separates build artifacts and include files.
This patch also significantly speeds up analisys, caching file-to-application
mapping and avoiding repeated lookup for the very same gen_server/...
> rebar_compiler: fix DAG and speed-up analysis for large repositories

- CONTRIBUTING.md
Apparently the docs at rebar3.org do not contain the list of available plugins - the docs at rebar3.readme.io do.
> Fixed link to list of plugins.

- src/rebar_prv_common_test.erl
With the current behavior, rebar3 removes all cth_readable hooks from the config and adds the ones it wants. This however only works when using atoms only (which is normally used).
If we add a config to the hooks in the `rebar.confg`, the whole thing breaks:
```erlang
{cth_hooks, [{cth_readable_failonly, []}]}
```
because `(Hooks -- AllReadableHooks)` assumes everything to be atoms. The type signature however is:
```
{ct_hooks,[my_cth_module]}
{ct_hooks,[{my_cth_module,[{debug,true}]}]}
{ct_hooks,[{my_cth_module,[{debug,true}],500}]}
```
(see https://erlang.org/doc/apps/common_test/ct_hooks_chapter.html)
This change is needed for https://github.com/ferd/cth_readable/pull/34 to work correctly.
> fix injection of cth_readable to allow for hook configuration

- src/rebar_git_resource.erl
This improves performance quite a bit since we do not need to actually produce the list of commits, split it, and count the number of lines, but can get the count directly from git.
> Use "git rev-list --count" to count refs

- bootstrap
Since the bootstrap script is executed before the compilation of
rebar_uri takes place, it can't rely on its functions. The functions are
used for the proxied calls and therefore need to be there before deps
required for rebar3 itself are fetched.
Folding it in is the only way to go while maintaining compatibility with
all versions, and we incur a mandatory warning for call paths that are
gonna be dynamically done but won't error out in practice.
> Fold rebar_uri calls into bootstrap script

- src/rebar_pkg_resource.erl
The original debug output prints the `repo_url` from the pkg RepoConfig, which is not the actual URI to fetch from, maybe using a HEX_CDN, or a private repo URL like erlang/rebar3#2346. 
This patch prevents confusing and benefits for debuging.
> Print actural download repo in DEBUG output

- src/rebar_prv_compile.erl
Before this change even if there are no virtual apps the DAG is reloaded, in our system this takes ~3 seconds. With this change we give up before loading the DAG if there are no virtual apps.  Rebar3 behavior should not change other than better performance. This change has been tested by running rebar3 ct
> Do nothing if there are no extra virtual apps.

- src/rebar3.erl
- src/rebar_hex_repos.erl
- src/rebar_packages.erl
- src/rebar_pkg_resource.erl
- src/rebar_state.erl
Not only `r3_hex_repo:get_tarball` need to use `rebar_packages_cdn`, but also all the other exported functions from `r3_hex_repo`.
Since only `get_package` and `get_tarball` are used, I apply cdn option with them but the rests.
Maybe this should be a config option inside the vender hex_core.
> Use rebar_packages_cdn for fetching package resource

- src/rebar_compiler.erl
- src/rebar_compiler_dag.erl
- test/rebar_compiler_dag_SUITE.erl
The change does not consider a dependency on an .hrl file from one app to another as an ordering dependency between the two apps. Instead it resolves all the .hrl dependencies completely and uses the resolved dependencies instead. This means that it's much less likely that there are circular dependencies between apps for compiler ordering meaning that the ordering is much more likely to be correct even for projects which have circular .hrl dependencies.
The change I made to the tests was to add a dependency from a .hrl in app3 to a source file in app2.
More discussion about this change in https://github.com/erlang/rebar3/discussions/2465
> Modify algorithm to decide compilation order between apps to resolve header dependencies

- src/rebar_hex_repos.erl
- src/rebar_packages.erl
- src/rebar_pkg_resource.erl
A few issues exist in the current code:
1. the DEBUG information for a brand new package when no index cache is
present outputs private hex keys
2. recently merged branches had debug output I Felt could be cleaner (see https://github.com/erlang/rebar3/pull/2479)
This commits fixes both by adding helper function to the rebar_hex_repos
module whose role is to anonimize the information and also provide a
stringified version of each repo config for debugging purposes.
The new output should look something like:
...
===> Getting definition for package hex_core from repo hexpm (#{api_url => <<"https://hex.pm/api">>,name => <<"hexpm">>,
repo_name => <<"hexpm">>,repo_organization => undefined,
repo_url => <<"https://repo.hex.pm">>,repo_verify => true, …
> Sanitize repo configuration in DEBUG output

- src/rebar_prv_common_test.erl
- test/rebar_ct_SUITE.erl
The common_test application accepts for the group option groups
or path of groups. This adds support for specifying grou paths in
the form "g1.g2.g3".
refs #2444
> Common test: make group paths work for --group "[g1,g2],g3" option

- src/rebar_compiler_erl.erl
- src/rebar_erlc_compiler.erl
rebar3 handles its own worker processes for compilation so having compile:file spawn additional processes is a waste.
I thought we already did this. Maybe there is a reason we shouldn't that I forgot?
> pass no_spawn_compiler_process to compile:file/2

- rebar.config.sample
I'm not sure if the version choice is OK, but don't expect `rebar3` consumers to copy-paste without thinking about consequences either.
> Add useful example constraint

- src/rebar_compiler.erl
- src/rebar_compiler_erl.erl
The first commit omits some code path additions that aren't required.
The rest address additional issues have been reported where path juggling clashed between rebar3 dependencies and projects' own dependencies, particularly on the first build where the path is added for the first time to a project.
The fix _is_ to make the code path use `code:add_patha/1` to make it go above rebar3's in-memory deps.
However, when building with profiles, using `code:add_patha/1` lowers some resolving cache speed to resolve apps and paths, which is why @max-au had replaced it with `code:add_pathz/1`. In order to see if build speeds could be preserved, the third commit adds a conditional check where the performance fix is maintained when apps are _not_ part of the rebar3 dependency tree as well.
This would …
> More path juggling fixes

- src/rebar_prv_shell.erl
This commit adds a parameter to `rebar.config` shell section:
{shell, [
{apps, [megaco, tools, runtime_tools]},
{log, info | debug}
]}.
This commit adds a parameter to `rebar.config` shell section:
{shell, [
{apps, [megaco, tools, runtime_tools]},
{log, info | debug}
]}.
With 'info' (default), behaviour stays as before.
With 'debug', "===> Booted megaco" messages are printed with debug verbosity level,
and are available when rebar3 is run with DEBUG=1 environment variable.
> rebar3 shell: implement various modes to print "booted" message

- src/rebar_prv_plugins.erl
- src/rebar_prv_plugins_upgrade.erl
- src/rebar_utils.erl
Closes #2491.
As per the doc.s and a validation (over Slack), about the expected behaviour, this pull request aims at having `rebar3 plugins upgrade` (no target plugin) work.
> Have "rebar3 plugins upgrade" work without specifying plugin name

- src/rebar_prv_escriptize.erl
In the current state, in a multi-application project, the escriptize plugin
will only allow building a single application as an escript, and will force
developers to provide a "main" application with the escript_main_app
configuration variable.
This commit add a command line option for the escriptize plugin which let the
user select the application to build the escript for. The escript_main_app
configuration variable is still used if it is set for backward compatibility.
> add an option to select the application to build an escript for

- src/rebar_relx.erl
Without this, unexpected errors (i.e. due to a badmatch) that isn't
thrown properly get to be silently ignored and considered a success.
> Relay unexpected relx return values

- src/rebar_prv_escriptize.erl
- test/rebar_escriptize_SUITE.erl
Otherwise we end up in a situation where we get a hard crash.
Fixes https://github.com/erlang/rebar3/issues/2520
> Catch and report missing escript dependency

- src/rebar_compiler_dag.erl
- src/rebar_compiler_epp.erl
- src/rebar_compiler_erl.erl
- test/rebar_compile_SUITE.erl
This fixes https://github.com/erlang/rebar3/issues/2534
While fixing the bug reported above, as explained in https://github.com/erlang/rebar3/issues/2534#issuecomment-820393110
I found out that the DAG preparation took in include paths that were
explicit, and did not resolve them properly (and therefore silently
failed to track updates). On the other hand, the compiler worked fine,
which highlighted a difference between options passed to EPP via the
compiler, and those we pass internally when building the DAG.
I fixed this, which in turn caused problems with test cases for
recursive parse transforms; the reason being that modules were being
resolved as source files under `_build/`, which turned out to be due to
the EPP resolver we wrote that would go recursive in all directories to
find …
> Fix DAG resolving for recursive directories

- src/rebar_prv_dialyzer.erl
> Make dialyzer output file format configurable

- src/rebar_compiler_erl.erl
- test/rebar_compile_SUITE.erl
Annoying issue reported by users who had deeply nested source
directories. The patches I've added to the compiler recently worked well
up to 1-2 levels of nesting (which we tested for), but I messed up the
merging of recursive path lists by doing them only at the top level.
So when people had deeper-nested source structures, the paths were
passed incorrectly and ignored some source files when resolving the
DAG.
Fix this so the path lists are merged at a level-order rather than only
at the top, ensuring proper resolving.
> Fix bad compiler path nesting

- src/rebar_prv_plugins.erl
- test/rebar_plugins_SUITE.erl
Fixes https://github.com/erlang/rebar3/issues/2440#issuecomment-823051052, as introduced by https://github.com/erlang/rebar3/commit/10404ab802415e9b515250a496f4726c367407ed#diff-8ea8ad4be21eabc13455daec52b69545db813e2e08597683d9a4f6c0fce7b187R67.
I'm trying to come up with a test.
> Fix `plugins upgrade` for non-tuple specification

- src/rebar_hooks.erl
- test/rebar_hooks_SUITE.erl
Otherwise, arguments for one command are potentially passed to an
incompatible one.
Fixes #2545
> Strip CLI args from provider hooks

- src/rebar_prv_dialyzer.erl
Hello,
[included_applications](https://erlang.org/doc/design_principles/included_applications.html) is not a much-used feature afaik. When toying around with the feature I got some dialyzer errors (Callback info about the ... behaviour is not available) when I defined a behaviour in the included application and used it in the primary application. This should fix it :)
> Treat applications and included_applications the same way when builing Dialyzer PLTs

- .github/workflows/main.yml
- .github/workflows/nightly.yml
- .github/workflows/publish.yml
- Dockerfile
- bootstrap
- rebar.config
- rebar.config.sample
- src/rebar_compiler_epp.erl
- src/rebar_string.erl
- test/rebar_test_utils.erl
- vendor_hex_core.sh
What this pulls in:
* https://github.com/uwiger/parse_trans/pull/41
* https://github.com/uwiger/parse_trans/pull/42
* https://github.com/uwiger/parse_trans/pull/43
After I saw that a bump was required, I decided to adapt to min. OTP ~21~(now) 20
> Increase OTP 24 readiness + move to OTP 20 min.

- src/rebar_prv_escriptize.erl
This brings the behaviour of `rebar3 escriptize` in line with `rebar3 release` by enabling it to bundle compiled dependencies found on ERL_LIBS (excluding OTP apps).
Currently, `rebar3 escriptize` fails when the escript's `.app` file specifies a dependency which is available on ERL_LIBS but not specified in `rebar3.config`.
Fixes #2551
> allow use deps on ERL_LIBS in escriptize

- rebar.config.sample
- src/rebar.hrl
- src/rebar_app_discover.erl
- src/rebar_app_info.erl
- src/rebar_app_utils.erl
- src/rebar_fetch.erl
- src/rebar_otp_app.erl
- src/rebar_prv_clean.erl
- src/rebar_prv_dialyzer.erl
- test/rebar_discover_SUITE.erl
- test/rebar_test_utils.erl
This adds the ability to configure the default naming of the `.app.src` and `.app.src.script` files for application discovery:
- `application_resource_extensions` can be set  to define extension to the resource files
- the extensions will be tried to be resolved from left to right
- `.app` files are still handled like before (not configurable)
- `mix.exs` files are handled, but can be disabled (by removing from extension list), I'm not sure if this is the right thing todo here, or if they should be special cased like the `.app` files
Note: This still needs tests added.
> add support to configure application resource naming

- .github/workflows/main.yml
- .github/workflows/nightly.yml
- .github/workflows/publish.yml
- README.md
- src/rebar_prv_escriptize.erl
The burden of 5 major versions is too high, use the fact that people are
gonna want to switch to OTP-24 for the JIT to clamp down on how much
backwards compat we sign up to reasonnably support and do the same as
what the OTP team is doing.
> Only support 3 newest OTP versions

- src/rebar_httpc_adapter.erl
- src/rebar_pkg_resource.erl
- test/rebar_pkg_repos_SUITE.erl
This will help add ways to increase observability, mocking for tests,
and future-proofing portability of browser options when talking to
hex.pm in the near future.
For the time being this is mostly a copy of the existing generated
adapter in hex_core.
> Introduce hex_core HTTP adapter for rebar3

- src/rebar_httpc_adapter.erl
- src/rebar_pkg_resource.erl
- test/rebar_pkg_repos_SUITE.erl
Resolves https://github.com/erlang/rebar3/issues/2564.
Based on https://github.com/erlang/rebar3/pull/2561, an adaptation of erlang@751fa916b81a444db74a7c37c6addfc7ffb8b511 for rebar3 3.13.x.
Per https://ferd.ca/you-ve-got-to-upgrade-rebar3.html:
> [The patch](https://github.com/erlang/rebar3/commit/17848f4c7711981806cd28bcd580eb96a2f9b660#diff-4b5af60b80cd23cfd32adbf1b5e7647c8d89a8d7046c89cee2be5a5ae14dc95fR14) is not that complex on new versions and should be relatively easy to port to older versions if anyone ends up wanting to help.
This should work for anyone on rebar3 3.13.2 either due to running an older OTP or still needing the old pre-compile hook behavior (https://github.com/erlang/rebar3/pull/2211#issuecomment-705888811).
> Introduce hex_core HTTP adapter for rebar3 (3.13.x)

- src/rebar_prv_plugins_upgrade.erl
This apparently never worked properly, the call being made swapped
arguments order, but kept the type correct enough that no type warning
would be raised.
This isn't a problem though, because before this optimization, people
were already used to calling 'rebar3 update' before upgrading a plugin.
This being fixed makes that call optional now.
> Fix optimistic registry update of plugins being upgraded

- src/rebar_prv_dialyzer.erl
this takes the current path formatting (which reuses compiler-specific
functions) and makes it contextual to knowing whether files exist or
not. The compiler path printing assumes all directory paths are
project-local, but PLTs only occasionally fit this description. On first
copies, they don't.
This currently yields output such as:
===> Building with 204 files in ../.cache/rebar3/rebar3_24.0.2_plt...
===> Copying ../.cache/rebar3/rebar3_24.0.2_plt to _build/default/rebar3_24.0.2_plt...
===> Checking 204 files in _build/default/rebar3_24.0.2_plt...
===> Adding 29 files to _build/default/rebar3_24.0.2_plt...
===> Doing success typing analysis...
===> Resolving files...
===> Analyzing 13 files with _build/default/rebar3_24.0.2_plt...
Whereas this patch instead allows the following …
> Normalize Dialyzer PLT paths

- rebar.config
- src/rebar_utils.erl
Got `Handshake Failure - {bad_cert,hostname_check_failed}` when making a request to a third-party mirror with wildcard certificates of hex repo. For example https://hexpm.upyun.com (from: https://hex.pm/docs/mirrors).
According to https://github.com/benoitc/hackney/issues/624#issuecomment-631340823
- https://bugs.erlang.org/browse/ERL-1232
> Fix ssl check hostname options for wildcard certificate

- src/rebar_app_discover.erl
In some rare cases (see https://github.com/erlang/rebar3/issues/2581 for a sample interplay between plugins
and recursive dep definitions with apps) there can be some interplay where
a dependency declares recursive directories but the lookup for app files does
not acknowledge these and causes problems.
This patch simply ignores such cases by stripping options; this should
have no backward compatibility impact since the value was just ignored
before anyway, but will prevent crashes in hard-to-reproduce cases.
Possibly fixes #2581 but I haven't been able to reproduce this in tests
since it seems to require a very peculiar setup to trigger.
> Prevent crashes on recursive src_dir definitions in deps

- bootstrap
bootstrap is always on an immediate run and should be skippable safely
when dealing with compiler versions.
As suggested by @saleyn in https://github.com/erlang/rebar3/issues/2584
> Drop bootstrap URI handling functions warnings

- src/rebar_prv_xref.erl
I'm not really sure how to provoke this, but I had a file that compiled in OTP24 via rebar3 to abstract code that started with a `-compile({no_warn_unused_record, [contract]}).`, so the first entry of the `AbstractCode` list was `{attribute,0,compile,{nowarn_unused_record,[[contract]]}}`. This PR filters the `AbstractCode` list for `-file` attributes before matching. I can make this more efficient if you want.
> Handle abstract code starting with a non-file attribute

- src/rebar_file_utils.erl
- test/rebar_file_utils_SUITE.erl
See the [linked issue](https://github.com/erlang/rebar3/issues/2596) issue for more details, but the motivation here is that nix, among other things it does, runs package builds as separate users with different temporary directories. But since for rebar3 the temporary file directory is always `/tmp`, it can potentially result in tests failing with permission issues for files created previously with a different user, that leaked into `/tmp`.
This PR makes rebar3 honour the `TMPDIR` environment variable when deciding what the directory for temporary files is on *nix is, avoiding such collisions.
> Make `rebar_file_utils:system_tmpdir/1` take `TMPDIR` envvar into account on *nix

- rebar.config
- src/rebar_prv_escriptize.erl
When developing `relx` and testing changes with `rebar3`, it is convenient to make `relx` a checkout dependency.
However, the current implementation of `escript_incl_extra` expects the output directory of `relx` to be under `_build/<profile>/lib/`, which is not the case if `relx` is a checkout dependency.
Fixes #2600
Due to the change in `rebar.config`, this is a **backwards-incompatible** change when using an older version of `rebar3` to build a new version of `rebar3`. But because the recommended way to build `rebar3` is with `./bootstrap`, perhaps this is okay.
1. Check out `rebar3`
2. Check out `relx` at `rebar3/_checkouts/relx`
3. Build `rebar3` using `./bootstrap`
4. Run `${path-to-rebar3-repo}/rebar3 release` on another project
- Before this fix, `rebar3` crashes as reported in …
> Add escript_incl_priv so escriptize priv dir inclusion works with _checkouts and profiles

- src/rebar_compiler_dag.erl
Assume that the original app order respects the dependency order as supplied by
the rebar3 dependency order. Then what we do is interleave the hard compile-
time dependencies as found by analysis to maintain their ordering constraints
into those given by the dependency order.
This should lower the chance of hitting conflicts when runtime dependencies
become compile-time dependencies via interactions in parse transform calls.
As described in #2563,
part of the previous approach's weakness is that we need to
seed the compile order with the dependency order for some
invisible compile-time dependencies (runtime ones turned
to build-time ones via calls to parse-transforms).
Unfortunately, topological sorting is insufficient due to how it
flattens apps. Assume the DAG contains:
a -> b
c -> d …
> Give compiler hints when handling run-time deps in parse_transforms

- src/rebar_prv_xref.erl
- src/rebar_relx.erl
This comes in coniunction with https://github.com/erlware/relx/pull/882, that allows RELX to accept in its state a method to filter xref warnings.
We pass to it the method that rebar3 currently uses to filter them based on the ignore-xref attributes in erlang file.
> rebar3 release to honour the ignore-xref attribute

- src/rebar_core.erl
- src/rebar_state.erl
Closes #2618.
`~p` uses `'` to print non-ASCII atoms, so that's avoided.
`~ts` is for the UTF-8 stuff.
This would go nicely with https://github.com/tsloughter/providers/pull/13, but it can be merged before that one's merged and tagged, too.
Also, I'm not sure if/how you wanna test this, so I'll wait for further guidance.
> Don't crash on printing non-ASCII characters

- src/rebar3.erl
The order of operations was swapped such that global plugins would be
installed outside of the configured GLOBAL_CACHE_DIR. Swapping the order
should allow it to work fine and fix https://github.com/erlang/rebar3/issues/2633
> Proper respect of GLOBAL_CACHE_DIR

- src/rebar_relx.erl
We have a use-case where we have alot of releases in an umbrella project. Building all releases takes a long time, and usually we only need a selected hand full. However, building them one at a time is also slow.
The release provider has already the functionality to build releases in parallel. This PR adds a --relnames option the works like --all in that it builds the highest version, but it takes a list of release names.
e.g. 
```
rebar3 release --relnames=rel1,rel2
```
If a release is not found, it fails on the first release, and does not start building any release:
```
rebar3 release --relnames=rel1,relnonsense
...
===> No releases exists in the system for relnonsense!
```
> add --relnames option to allow selectively building of multiple releases

- src/rebar_prv_plugins_upgrade.erl
- test/rebar_plugins_SUITE.erl
Adds support for `-a/--all` to `rebar3 plugins upgrade`, replacing the no argument functionality with the all flag.
See #2583.
> Support for all argument in upgrade plugin

- src/rebar_prv_upgrade.erl
- test/rebar_pkg_alias_SUITE.erl
- test/rebar_upgrade_SUITE.erl
Addresses #2583 for the upgrade command.
> Support for all argument in upgrade

- src/rebar_prv_unlock.erl
- test/rebar_alias_SUITE.erl
- test/rebar_unlock_SUITE.erl
This alters the behavior of the `unlock` command as outlined in #2583. Previously, calling `rebar3 unlock` with no further arguments would simply delete the `rebar.lock` file. This change requires the `--all` flag to unlock all dependencies, and makes calling `unlock` with no arguments an error. When specifying a list of dependencies to unlock, the behavior is unchanged. 
#2583 requests similar behavior for `upgrade` and `plugins upgrade`. These will be addressed in separate PRs.
> Support for all argument in unlock

- src/rebar_compiler_yrl.erl
Related to bug https://github.com/erlang/rebar3/issues/2652.
> Fix issue for duplicates options of 'parserfile' in 'yrl_opts'

- priv/templates/Makefile
The Apple M1 processor is not x86_64, so don't specify this architecture
for all C compilations on Mac OS.
> Fix NIF compilation on Apple M1.

- src/rebar_git_resource.erl
When trying to build one of our projects on dockerhub, we saw the automatic build failing with a badarg:
```
#12 129.8 ===> Uncaught error in rebar_core. Run with DIAGNOSTIC=1 to see stacktrace or consult rebar3.crashdump
#12 129.8 ===> Uncaught error: badarg
#12 129.8 ===> Stack trace to the error location:
#12 129.8 [{erlang,list_to_integer,["warning: refname '3.0.0rc4' is ambiguous.\n0"],[]},
#12 129.8 {rebar_git_resource,get_patch_count,2,
```
It appears that in a situation after `git checkout -b <TAG>`, when `rebar_git_resource:get_patch_count/2` is called, the cloned repo is in a state where it has a branch and a tag of the same name. This causes `git rev-list <TAG>..HEAD` to print "warning: refname '<TAG>' is ambiguous." to stderr, which in turn confuses a list_to_integer at the …
> git_resource: ignore stderr in get_patch_count when calling git rev-list

- src/rebar_git_resource.erl
Rebar3 uses git in interactive mode (the default mode), which can block the rebar3 process indefinitely when git asks for credentials.
Since git 1.3.0[1], the  `GIT_TERMINAL_PROMPT` environment variable[2] was added to prevent git from asking anything and failed if the git command cannot succeed without more information.
[1] https://github.com/git/git/blob/master/Documentation/RelNotes/2.3.0.txt
[2] https://git-scm.com/docs/git#Documentation/git.txt-codeGITTERMINALPROMPTcode
> Use git command in non interactive mode

- rebar.config.sample
- src/rebar_git_resource.erl
Where git revision is not specified for a dependency, check out and upgrade from the default branch (origin/HEAD) instead of the hardcoded `master`, consistently with rebar 2. Mostly to support GitHub repos where the default branch has been (re)named `main` or something else.
Resolves #2651.
> Use default branch for git and git_subdir resources with no revision

- src/rebar_fetch.erl
I recently have to debug a resource plugin and this log would have give me all the information I would have need.
> add a log in the needs_update

- src/rebar_dialyzer_format.erl
A possible typo is fixed: `detencted` -> `detected`
> Fix a typo

- src/rebar_prv_new.erl
- test/rebar_new_SUITE.erl
Fixes https://github.com/erlang/rebar3/issues/2675
Uses the now project-standard rebar3 error structures, which were
possibly not even there when we originally set up the provider for this.
> Error out on unknown templates in 'new' command

- src/rebar3.erl
- src/rebar_prv_plugins.erl
- test/rebar_plugins_SUITE.erl
There was some confusion in the code:
- `rebar_dir:global_config()` returns the default path
- `rebar_dir:global_config(State)` returns the configured path based on
the ENV overrides, and defaults to `global_config()` if nothing is
given
Since no State term existed at this point in time, we just called out
directly to the argument-free version of the call, but this ignored all
overrides. Instead, we call it with an initialized `rebar_state:new()` to
properly handle configuration from users, and then use the actual
configured state (if any).
> Fix global cache config overriding

- src/rebar_prv_eunit.erl
- test/rebar_eunit_SUITE.erl
This PR adds a `-t, --test` flag to the `eunit` task to be able to run individual test cases.
You can now run individual tests like this:
```console
$ rebar3 eunit --test=module1:func1+func2,module2:func1;func2
===> Analyzing applications...
===> Compiling app
===> Performing EUnit tests...
....
Finished in 0.019 seconds
4 tests, 0 failures
```
`+` is added as a test case separator for the same module since `;` is problematic to use in shells by default.
Thanks @ferd  and @richcarl for pointers on how to implement this.
> Add euint --test flag

- src/rebar_utils.erl
This causes `ssl` to use the default value of 10, fixing issues with longer certificate chains.
> Use default `depth` parameter for SSL

- src/rebar_relx.erl
When merging #2503 it was not taken for account that `include_erts` and the other variables can be present multiple time in the `RelxConfig`. This can occurs when a variable is define in a profile. Following is an `rebar.config` file example and the result before this fix.
```
{relx, [{release, {tt, "0.1.0"},
[tt,
sasl]},
{sys_config, "./config/sys.config"},
{vm_args, "./config/vm.args"},
{include_erts, false}
]}.
{profiles, [{prod, [{relx,
[
{include_erts, true}
]
}]}]}.
```
```erlang
[{mode,prod},
{output_dir,"/home/jbouchard/ws/erl/tt/_build/prod/rel"},
{overlay_vars_values,[{profile_string,"prod"}]},
{overlay_vars,
[{base_dir,"/home/jbouchard/ws/erl/tt/_build/prod"}]},
{overlay,[]},
{include_erts,"/usr/lib/er"},
{include_erts,true},
{release,{tt,"0.1.0"},[tt,sasl]}, …
```
> Do not discard parameters --system_libs and --include-erts when duplicate values exist

- src/rebar.app.src.script
- src/rebar_app_discover.erl
- src/rebar_prv_vendor.erl
The new experimental vendoring provider is called as `rebar3 experimental vendor`,
and works by doing the following:
- Detecting whether the app is an umbrella application (only works on
them)
- Fetching all dependencies for the project
- Moving all dependencies to the top-level vendor/ directory
- Telling the user to configure `{project_app_directories, ...}` to
include the vendored path
- Telling the user to move all `{deps, ...}` entries away from the
top-level `rebar.config` file and into sub-applications' files
This then works by changing all non-checkout dependencies into top-level
apps stored elsewhere than the user-supplied ones.
This should also implicitly empty the lock file on the next compilation.
When called again, the provider:
- Makes itself ignore the previous …
> Experimental vendoring provider

- src/rebar_prv_vendor.erl
Still no tests -- I ran it all by hand, but this worked fine!
Plugins that were vendored are not re-fetched in subsequent runs and can
be invoked without a problem. Re-bundling works the same and I added a
few quick checks to reduce errors being output.
> Support plugins in experimental vendor provider

- src/rebar_prv_path.erl
A naive addition to the list of directories being searched for path inclusion.
I *think* that as a result of how applications in rebar.config are named/sparse checkouted, that this assumption is valid across all of the git subdirs that we are currently using - but I don't know if that assumption is true in all cases. ( APP_NAME/apps/APP_NAME) ??.
Either way, this fixes our usages of path for #2686
> Attempt to find apps in git subdirs (sparse checkouts)

- .github/workflows/main.yml
- .github/workflows/nightly.yml
- .github/workflows/publish.yml
- .github/workflows/shelltests.yml
- README.md
- src/rebar_prv_shell.erl
Adds a requirement to support OTP-25, which also means deprecating
explicit support for OTP-22.
We've got a couple of macros we can remove, but let's call this a soft-deprecation for the time being.
> Support OTP 23..25 inclusively

- src/rebar_compiler_dag.erl
- src/rebar_compiler_mib.erl
- test/rebar_compile_SUITE.erl
- test/rebar_compiler_dag_SUITE.erl
This has two parts:
1.  Fix extension matching in compiler DAG
Turns out this didn't work! Now it does. The check of edge acted as a
workaround that prevented clearing more files than necessary, but when
multiple output artifacts existed, it over-deleted them, apparently.
So now this is properly checked as a bit of logic and all tests keep
passing.
2.  Track and match MIB file build artifacts in DAG
This allows incremental builds with these files.
> Track mib compilation artifacts

- src/rebar_relx.erl
- test/rebar_release_SUITE.erl
Without fetching the value otherwise, we ended up with a broken partial config like this:
[{output_dir,"/tmp/rc_example/_build/dev1/rel"},
{overlay_vars_values,[{profile_string,"dev1"}]},
{overlay_vars, [{base_dir,"/tmp/rc_example/_build/dev1"}},
{overlay,
[{template,"conf/sys.config",
"releases/{{default_release_version}}/sys.config"},
{template,"conf/vm.args",
"releases/{{default_release_version}}/vm.args"}]},
{dev_mode,true},
{extended_start_script,false},
{include_erts,false},
{overlay_vars,"conf/vars_dev1.config"},
{release,{rc_example,"0.1.0"},[rc_example]},
{sys_config,"conf/sys.config"},
{vm_args,"conf/vm.args"}]
Since the `overlay_vars` key was there twice, only the first one was consulted and the rest was ignored. The new format instead looks like this: …
> Properly carry overlay_vars settings for files in relx

- bootstrap
- src/rebar3.erl
- src/rebar_fetch.erl
- src/rebar_httpc_adapter.erl
- src/rebar_prv_local_upgrade.erl
- src/vendored/r3_hex_http_httpc.erl
If --offline or REBAR_OFFLINE=1 is given, inets is not started and
all calls to httpc:request/N are prevented. If any online resource
is needed, an error occurs rather than trying to fetch the online
resource.
The purpose is described in #1281 and #2640.
Combined with placing the dependencies in `_checkouts`, I think it makes it possible to build using dependencies provided manually (which is what's required in the scenario that all dependencies need to be separately reviewed and verified legally and security wise). When combined with #2642, even rebar3 itself can be built in this way.
> Add --offline option and REBAR_OFFLINE environment variable

- src/rebar_prv_shell.erl
Hey folks,
I'm not sure if there's an equivalent function in rebar3 or not, but I found a need to sort-of re-implement `erl -eval` but for the `rebar3 shell` command, so `rebar3 shell --eval "my_module:my_function()"`.
This implementation also works like `erl -eval` in that it supports multiple `--eval` arguments.
Thoughts?
> Add --eval option to `shell`

- apps/rebar/src/rebar_compiler_erl.erl
- bootstrap
1. It's normal not to find a file in the DAG nor on disk when it has
never been built before
2. The bootstrap deletion can be more aggressive since there's
vendoring, and will prevent straggling file issues.
> Reduce warnings around bootstrap and DAG operations

- apps/rebar/src/rebar_file_utils.erl
- apps/rebar/src/rebar_prv_common_test.erl
- apps/rebar/test/rebar_file_utils_SUITE.erl
When running `rebar3 ct`, `rebar_prv_common_test` copies the data folders
to a different location. If `{name}_SUITE_data` folder contains relative
symbolic links, the symbolic links might stop working since the path
might be different.
A solution is to add the `-L` option to `cp` so it dereferences the
symbolic links and copies the original content in the target file.
This is only done for the data folder but and won't change any code that
previously used `rebar_file_utils:cp_r`.
I asked in [erlangforum](https://erlangforums.com/t/what-is-the-best-way-of-providing-test-data-from-outside-the-suite-data-folder/1650) a few days ago because I thought it was `common test`
problem but today I realised that is rebar3 copying the files.
I'm not sure if this problem happens with Windows too since …
> Dereference symbolic links when copying files from ct data folder

- apps/rebar/src/rebar3.erl
The value was always overwritten after examining $HEX_CDN.
> Respect rebar_packages_cdn set in rebar.config

- apps/rebar/src/rebar_pkg_resource.erl
- apps/rebar/test/rebar_pkg_SUITE.erl
Absent entity tag list was not allowed before RFC 9110 published this June. However, it would be better not to send it. Cowlib, for example, treats it invalid, and Cowboy rejects such a request :)
I'm also not really sure if it's needed to conditionally request tarballs (`GET /tarballs/PACKAGE-VERSION.tar`). Seems like locally cached tarball can be used as long as its checksum is considered valid. Mix/Hex, for example, uses conditional requests only to fetch new package registry (`GET /packages/PACKAGE`).
> Do not send empty If-None-Match in tarball request

- apps/rebar/src/rebar_prv_dialyzer.erl
- apps/rebar/test/rebar_dialyzer_SUITE.erl
When the environment's OTP version supports `dialyzer --incremental` (see [the PR introducing it](https://github.com/erlang/otp/pull/5997)), enable an `--incremental`/`-i` option to `rebar3 dialyzer` in order to make it accessible.
In erlang/OTP#5997, we added an `--incremental` option to Dialyzer, however, in order to make good use of it from a rebar3 project, you'd probably want to have a corresponding option in `rebar3 dialyzer`, which is what I've added here.
This PR introduces quite a bare-bones option, since you could do more in terms of reading incrementality-specific metrics from Dialyzer and reporting them, but it at least allows some early experimentation when it detects an appropriate bleeding-edge OTP version with the necessary features. For older OTP versions, users won't see …
> Add support for `dialyzer --incremental` when available

- apps/rebar/src/rebar_prv_shell.erl
In Erlang/OTP 26 there is support for starting a shell session
from an escript instead of using the hack that is currently used.
So we make sure to use that method if possible.
See https://github.com/erlang/otp/pull/6144 for details on the new shell
Note: At the moment rebar3 is started with "-noshell" which is the default for escripts. In 26 it will also be possible to start an escript in "-noinput" and then change to "-noshell" or start a shell session depending on what the application wants to do. I don't know if rebar3 should change to "-noinput", but I thought I would just mention it so that you know that the possibility exists.
> Use shell:start_interactive to start shell if available

- .github/workflows/main.yml
- apps/rebar/src/rebar_prv_eunit.erl
The regression was added there and is fixed in the upcoming 25.1.1 release. All other cases are fine.
The code is untested because we can't run our own tests on 25.1 without failures, so just skip it entirely.
> Warn of EUnit issues on OTP-25.1

- apps/rebar/src/rebar3.erl
Mix and Hex don't use HEX_CDN for a long time.  Mix can run Rebar3 to compile dependencies.  To complete this Rebar3 may need to fetch plugins.  It would be nice to specify Hex mirror for both Mix/Hex and Rebar3 using one variable.
Can we deprecate HEX_CDN in favor of HEX_MIRROR? If so, I can update PR.
> Respect HEX_MIRROR environment variable

- apps/rebar/src/rebar_prv_packages.erl
Empty lists are not really expected for licenses or versions, but can be empty for link lists in package metadata.
Support them all the same because the code fix is trivial.
> pkgs command should support empty lists

- apps/rebar/src/rebar_prv_local_install.erl
See https://github.com/erlang/rebar3/issues/2751
By default we use the `VSN` variable and let it be overridden. But that variable is not prefixed to anything rebar3 so unrelated variables from random scripts are possible to break by doing this. 
I believe `VSN` is not documented anywhere, so we should be safe in changing it  right away.
CC @tsloughter
> scope local install VSN variable

- apps/rebar/priv/templates/gitignore
If you have other things in your project structure, e.g. `scripts/__main__.py` it would be ignored with the simple rule `_*` ("anything that starts with underscore anywhere").
It's better to use `./_*` meaning "anything that starts with underscore in the root folder (e.g. `_build`).
> Do not ignore everything starting with underscore recursively

- apps/rebar/src/rebar_prv_shell.erl
before this patch the output of `rebar3 help shell` looked like this:
```
--eval           Erlang term(s) to execute after the apps have been
started, but before the shell is 
presented to the 
user
```
> fix help shell output, --eval is misindeted

- rebar.config
Before this commit, `rebar3 release` outputs relx's info log without line breaks.
This commit adds RTX_LOG macro to relx's erl_opts.
Steps to reproduce:
1. `rebar3 new app foo`
2. `cd foo`
3. Append `{relx, [{release, {foo, "0.0.1"}, [kernel, sasl, stdlib, foo], []}]}.`
4. `rebar3 release`
At the step 4, expectation is that it outputs (reasonably) concise log lines, but it outputs:
```
% rebar3.head release
===> Analyzing applications...
===> Compiling foo
Solving Release foo-0.0.1Resolved foo-0.0.1release: foo-0.0.1
erts: 13.1.1
goals:
kernel
sasl
stdlib
foo
applications:
{kernel,"8.5.1"}
{stdlib,"4.1.1"}
{sasl,"4.2"}
{foo,"0.1.0"}
Assembling release foo-0.0.1...Release output dir /home/shino/g/rebar3/foo/_build/default/rel/fooRewriting .app file: …
```
> Add RTX_LOG macro option to top-level rebar.config

- apps/rebar/src/rebar_dialyzer_format.erl
Add missing message string formatting to `rebar3_dialyzer_format`.
The messages are specify in the [dialyzer.erl](https://github.com/erlang/otp/blob/master/lib/dialyzer/src/dialyzer.erl#L408) so I ran the following commands for finding missing messages:
```bash
grep '^message_to_string' otp/lib/dialyzer/src/dialyzer.erl |  sed 's/message_to_string({\([a-z_]*\),.*/\1/g' | sort > /tmp/otp.txt
grep '^message_to_string' rebar3/apps/src/rebar_dialyzer_format.erl | sed 's/message_to_string({\([a-z_]*\),.*/\1/g' | sort > /tmp/rebar3.txt
```
The missing message types are `callback_not_exported`, `contract_with_opaque`,  `map_update`, `missing_range`. The file already have a message formatting for `invalid_contract` but it has been divided in two functions in OTP project so my command shows it. …
>  rebar3_dialyzer_format: Add missing message formatting

- apps/rebar/src/rebar_prv_dialyzer.erl
- apps/rebar/test/rebar_dialyzer_SUITE.erl
The current state of Dialyzer incremental support was added before the code was shipped. There are 3 behaviours that can work:
1. Dialyzer in incremental mode expects one PLT file per project and that file is fully managed by Dialyzer
2. Dialyzer can work with a big global file shared by all projects and maintains all related updates based on each run
3. Rebar3 can store a global base incremental PLT file, and then use it as a foundation for a per-project file that once created keeps running
What we currently have in main for incremental mode is option 1. What Rebar3 did with classical PLTs was in option 3, and saved cross-project build time. It appears that Dialyzer can tolerate receiving an input PLT and an output PLT for incremental builds, which means option 3 ought to be supported, …
> OTP-26-rc1 support: Fix incremental dialyzer usage, and make it even more incremental

- .github/workflows/nightly.yml
- .github/workflows/publish.yml
The ubuntu-18.04 runner is [deprecated](https://github.com/actions/runner-images/issues/6002) and removed 2023/04/01.
Replace it with 20.04 so that [erlef/setup-beam can setup OTP23](https://github.com/erlef/setup-beam#compatibility-between-operating-system-and-erlangotp).
Forced runs (without the AWS interactions):
- [Publish](https://github.com/Nordix/rebar3/actions/runs/4552321276)
- [Nightly](https://github.com/Nordix/rebar3/actions/runs/4552321268)
> Lift Ubuntu runner in CI for Nightly and Publish

- apps/rebar/src/rebar_prv_common_test.erl
By default, common test should be redirecting log output via the cth_log_redirect hook. However, whenever we override the values to enable the stuff in cth_readable, we take that log redirection away.
This restores it so it is the same, so long as the user does not specify their own log values in it, which keeps the override/removal as-is.
> Maintain cth_log_redirect default in CT runs

- apps/rebar/src/rebar_compiler_dag.erl
- apps/rebar/src/rebar_parallel.erl
- apps/rebar/test/rebar_parallel_SUITE.erl
This addresses https://github.com/erlang/rebar3/issues/2767 by creating a pool mechanism in rebar_parallel that keeps as similar of an interface as possible as the queue mechanism, with the one caveat that it allows the asynchronous creation of tasks rather than requiring them all at start time.
The mechanism is not tested super deeply, which is probably a mistake, but I wanted to get a reviewable PR first.
The mechanism is also added to the rebar_compiler_dag module to cover use cases that were handled by spawning an unbounded number of processes before, which would cause problem with low file descriptors being allocated and lots of files being used and open in parallel. The pool mechanism puts an upper bound on processing but also on resource usage.
So this PR may also come with a …
> Add rebar_parallel pool, use in DAG scans

- .github/workflows/main.yml
- .github/workflows/nightly.yml
- .github/workflows/publish.yml
- .github/workflows/shelltests.yml
- README.md
- rebar.config
> Support OTP-26, Deprecate OTP-23 support.

- apps/rebar/src/rebar.app.src.script
- vendor/erlware_commons/rebar.config.script
In switching to vendoring, we implicitly broke the configuration-based version checks that rely on the app vsn of rebar3. this app vsn isn't configured yet during the initial app discovery phase and the "git" value is seen as invalid, causing a bootstrap crash.
We didn't see it because since Rebar3 3.18.0, we had not returned to the "git" version for things built from main, which hid the weird behavior.
It will legitimately happen absolutely nowhere but in this repo, so until it is modified elsewhere I'm hotpatching the dep to fix nightly builds.
> Hotfix erlware_commons config script

- apps/rebar/src/rebar_prv_shell.erl
As reported in a comment in https://github.com/erlang/rebar3/pull/2090 the current mechanism only breaks on a \n and does not even respect the \r\n grapheme cluster. So instead of using string functions, we go to regular expressions where we can specify both endings without a problem.
> Support CRLF in shell ENV files

- apps/rebar/src/rebar3.erl
This avoids an issue with Erlang/OTP 26
where the IO hangs when shelled out on
Windows.
See https://github.com/erlang/otp/issues/7261.
> Avoid setting encoding on Erlang/OTP 26

- apps/rebar/rebar.config
- apps/rebar/src/rebar.hrl
- apps/rebar/src/rebar_base_compiler.erl
- apps/rebar/src/rebar_compiler.erl
- apps/rebar/src/rebar_compiler_erl.erl
- apps/rebar/src/rebar_compiler_format.erl
- apps/rebar/src/rebar_compiler_xrl.erl
- apps/rebar/src/rebar_compiler_yrl.erl
- apps/rebar/test/rebar_compiler_format_SUITE.erl
- rebar.config
- rebar.config.sample
This is rather straightforward as an implementation: given any error message that contains column information, read the source file and find that line. Display it, and indent a cursor underneath it that points to the column.
Then we can just show the same error message as before.
In practice, given the module:
-module(fake_mod).
-export([diagnostic/1]).
diagnostic(A) ->
X = add(5 / 0),
{X,X}.
add(X) -> X.
add(X, Y) -> X + Y.
Calling rebar3 compile yields:
```
...
===> Compiling apps/rebar/src/fake_mod.erl failed
┌─ apps/rebar/src/fake_mod.erl:
|
5 |  diagnostic(A) ->
|             ^-- variable 'A' is unused
┌─ apps/rebar/src/fake_mod.erl:
|
6 |      X = add(5 / 0),
|                ^-- evaluation of operator '/'/2 will fail with a 'badarith' exception
┌─ apps/rebar/src/fake_mod.erl:
|
11 …
```
> Support rich compiler error messages

- apps/rebar/src/rebar_base_compiler.erl
- apps/rebar/src/rebar_compiler.erl
- apps/rebar/src/rebar_compiler_erl.erl
- apps/rebar/src/rebar_compiler_xrl.erl
- apps/rebar/src/rebar_compiler_yrl.erl
I hadn't seen this because all my projects use warnings_as_errors, but the warnings were never properly wired up.
This patch fixes that by adding the proper callbacks and invoking them from the 3 erlang-related compilers we support.
Sample run:
```
→ rebar3 as test compile
===> Analyzing applications...
===> Compiling revault
===> Compiling maestro
┌─ apps/revault/test/id_shim.erl:
│
23 │  id_ask(From, To) ->
│               ╰── Warning: variable 'To' is unused
===> Analyzing applications...
===> Compiling extra_test
```
This might look a bit like an error but yeah, not a good way to bypass that for now without further re-structuring of the code.
> Fixup: rich compiler output in warnings

- apps/rebar/src/rebar_git_resource.erl
The function `collect_default_refcount/1` of `rebar_git_resource` did not log the error message when it failed to get the vsn number with its `git log` command.
- A diagnostic error message is now printed with the status code and output message of the failing command.
I encountered this error with GitHub Actions CI (https://github.com/actions/checkout/issues/1169)
and failed to find the appropriate error cause because there was no diagnostic logging from rebar.
According to the CONTRIBUTING documentation, a test should be attached with this PR but I'm not sure how to add a test for this.
Any guidance would be appreciated.
> Print diagnostic when failing to get VSN with Git

- apps/rebar/src/rebar_prv_shell.erl
> Erlang 26 custom shell fix

- apps/rebar/src/rebar_prv_shell.erl
Heh folks!
It seems that https://github.com/erlang/rebar3/pull/2818 introduced a bug when there are no shell args defined (with Erlang 26), since the default value of `ShellArgs` in `rebar_prv_shell` is `undefined`.
This small fix just handles that situation, since `undefined` is not a valid value for the 3rd argument of `erlang:apply/3`.
Thanks!
> Fix for `rebar3 shell` in Erlang 26 when ShellArgs==undefined

- apps/rebar/src/rebar_utils.erl
- apps/rebar/test/rebar_utils_SUITE.erl
The current mechanism had a few oddities, as reported in https://github.com/erlang/rebar3/issues/2811:
- `rebar3 do a,b` runs `a` then `b`
- `rebar3 as profile task --a=b,c` runs the task with the flag `a` set to `b,c`
- `rebar3 as profile task -a b,c` runs the task with the flag `a` set to `b`, and then tries to run `c` as a task
- `rebar3 as profile task -a b, c` runs the task with the flag `a` set to `b`, and then tries to run `c` as a task
So the issue is that to pass a comma to an argument, we can only do so when it exists as a long form argument (`--flag`) and that it does not contain spaces.
This patch attempts to correct things by making the white-space following the comma significant. If it's missing, it gets grouped as a single entity. If it's there, the task is considered to be …
> Rework argument parsing in do/as providers

- apps/rebar/src/rebar_prv_alias.erl
- apps/rebar/test/rebar_alias_SUITE.erl
Closes #2824 (pushed mostly to start the discussion around it).
You can see I work a lot with substrings 😄 Basically, this is because I don't see a way to save what I want in the state, and `providers` doesn't provide 😄 for a way to save state in the provider either (if, e.g., it had a "meta" or "extra" element we could pass info. around that'd remain internal). I initially was going to use the `short_desc` field, but there's no accessor there either. Maybe I'll even have to update `providers` first (depending on guidance) before I move forward.
As is, though, this is functional, albeit "quick and dirty".
> Add command rebar3 alias

- apps/rebar/src/rebar_dialyzer_format.erl
... as per Dialyzer's [current implementation](https://github.com/erlang/otp/blob/master/lib/dialyzer/src/dialyzer.erl#L458).
I handle both `invalid_contract` clauses the same way, since I don't know if the `InvalidContractDetails` are interesting for the consumer, but lemme know and I'll update the code.
> Add (newer) Dialyzer info. about `invalid_contract`

- .github/workflows/main.yml
Found while working on #2825.
I was going to do this on that one's scope, but maybe separating it is more proper, especially for review purposes.
In my `rebar3` fork this is failing for OTP 25...
> Fix CI OTP versions

- apps/rebar/src/rebar_env.erl
- apps/rebar/test/rebar_hooks_SUITE.erl
The option requires a list of Name-Value pairs that are set as env variables when calling the hooks.
```erlang
{env, [{"MY_VAR", "my-value"}]}.
```
I tried to add a test in the hooks suite, I do not know if there is a better place.
> Add new 'shell_hooks_env' config to extend shell hooks' OS env vars

- apps/rebar/src/rebar_prv_xref.erl
It is not guaranteed that a generated module contains a `file` attribute. I've seen `erlydtl`-generated modules that don't have it.
It's potentially possible to not see the error by making use of `xref_queries` (?) though I didn't test that thoroughly (I will have to eventually use it though, since some generated modules do appear to have the file attribute, but I'm still to understand where it's coming from).
On the other hand, instead of simply removing the analysis (as per the code comment) we could also output a special 
```
module <module>: ...
```
with the error.
Probably best seen with "Hide whitespace" enabled.
> Prevent XRef issue when analysis runs on generated code

- apps/rebar/src/rebar_compiler_dag.erl
Issue described at https://erlangforums.com/t/rebar3-is-taking-longer-to-compile-projects/3061/13
It appears that edge insertion with a label involved messes with the bag table and continuously inflates the size of a DAG after many runs. Since changes are propagated through a graph, frequent changes to often-included header files or parse transforms risk multiplying edge counts.
This little patch ensures that before inserting an artifact edge, we first look whether it already exists; if so we don't add it any further, but keep all other semantics the same.
> Dedupe compiler DAG edge insertion for artifacts

- apps/rebar/src/rebar_utils.erl
Elixir projects (and probably other non-rebar3 projects as well) don't have an
`.app.src` file and only get their `.app` file after succesful compilation. This
seems to trip up the upgrade logic and makes `rebar3 tree` fail.
With this PR, if the version can not be determined in another way, it is taken
from the `hex_metadata.config` file if it exists.
> Fall back to reading versions from hex metadata

- apps/rebar/src/rebar_packages.erl
- apps/rebar/test/rebar_deps_SUITE.erl
- apps/rebar/test/rebar_pkg_repos_SUITE.erl
The first constraint in a chain of "or"'d constraints is taken into
account, all others are ignored. That way, there is at least *some*
resolution happening, which can always be overridden via `rebar.config`.
> Handle 'or' in versions in a primitive manner

- .github/workflows/main.yml
This mostly allows the "maybe this helps" brew-related commands to silently fail. If something later also breaks, we'll still have the logs to debug them.
> Fix MacOS CI workflows

- apps/rebar/src/rebar_prv_shell.erl
This is a small modification to the `--eval` arg to the `shell` command.
If the expression provided to `--eval` is missing a trailing `.`, this just adds one before evaluating the expression.
Thanks!
> Append . to --eval arg if missing in shell

- apps/rebar/src/rebar.app.src.script
- apps/rebar/src/rebar3.erl
- apps/rebar/src/rebar_log.erl
The log_level app setting had become ignored during refactorings of old. This makes it take effect again and syncs its standard setting with that of with rebar_log:default_level(). We add rebar_log:atom_to_level/1 to avoid exposing the level numbers used internally.
> Make log_level entry in rebar.app work again

- apps/rebar/src/rebar.app.src.script
- apps/rebar/src/rebar_prv_manifest.erl
- apps/rebar/test/rebar_manifest_SUITE.erl
The `manifest` provider allows users to extract information about a `rebar3` project, so that the information can be used by external tools such as language servers to learn about the structure of a project. The format and content of the produced manifest is totally up for debate. This is just to start the discussion. Ideally, the manifest should not be tight to `rebar3` as a build tool. This would enable other build tools to produce an equivalent file.
The provider is inspired by the [build_info](https://github.com/WhatsApp/eqwalizer/blob/main/eqwalizer_rebar3/src/eqwalizer_build_info_prv.erl) one which is part of the `eqWalizer` type checker for Erlang, but uses built-in functionality to fetch dependencies.
Having a built-in provider would remove friction for language server users and …
> Initial version of the Manifest plugin (experimental)

- apps/rebar/src/rebar_prv_clean.erl
- apps/rebar/test/rebar_as_SUITE.erl
- apps/rebar/test/rebar_hooks_SUITE.erl
The issue appears to be that because the 'clean' operation might be run while dependencies have not yet been compiled, we applied a partial app detection mechanism with `rebar_app_disover:find_apps(..., ..., all, ...)`, which worked to parse "invalid" (unbuilt) apps, but also did not apply overrides.
Instead, we trust the `install_deps` provider dependency by reusing the apps as they were fully parsed _if_ they were valid, and falling back to the `rebar_app_discover:find_apps/4` call only to cover the unreadable ones.
This, it turns out, has the side effect of properly applying hooks when apps are fully parsed, and fixes https://github.com/erlang/rebar3/issues/2862
In turn, this change let me fix things up such that we no longer call `install_deps` when just calling `rebar3 clean` -- we …
> Fix "clean" hooks in non-umbrella apps and when override are presents

- apps/rebar/src/rebar_compiler_erl.erl
- apps/rebar/src/rebar_erlc_compiler.erl
- apps/rebar/src/rebar_prv_dialyzer.erl
- apps/rebar/src/rebar_prv_escriptize.erl
- vendor/relx/src/rlx_assemble.erl
The `code:lib_dir/2` function was introduced to support looking into archives. Both archives and the `code:lib_dir/2` are marked as experimental.
In the upcoming Erlang/OTP 27 release, `code:lib_dir/2` will be deprecated. In some future release, the archive functionality will be changed (`escript:extract/2` will continue to work, reading archive members using `erl_prim_loader` will not).
> Eliminate use of experimental function code:lib_dir/2

- apps/rebar/src/rebar_completion_zsh.erl
- apps/rebar/src/rebar_prv_completion.erl
- apps/rebar/test/rebar_completion_SUITE.erl
I was writing docs for `completion` provider and tried to simplify loading `zsh` completion. I copied the loading process from `1pw` which stated that `zsh` completion must be done in multiple files. However, I found that's not true - you bind multiple commands to a completion function in a singe file. 
That enables automatic usage of aliases in zsh and unifies the whole process (usage becomes simpler)!
Also, I fixed a bug where aliases weren't split into multiple ones, I dunno how I missed that before.dsa
> `zsh` support for aliases in `completion`

- apps/rebar/src/rebar.hrl
- apps/rebar/src/rebar_app_discover.erl
- apps/rebar/src/rebar_compiler.erl
- apps/rebar/src/rebar_compiler_erl.erl
- apps/rebar/src/rebar_dir.erl
- apps/rebar/src/rebar_env.erl
- apps/rebar/src/rebar_erlc_compiler.erl
- apps/rebar/src/rebar_otp_app.erl
- apps/rebar/src/rebar_plugins.erl
- apps/rebar/src/rebar_prv_compile.erl
- apps/rebar/src/rebar_prv_eunit.erl
- apps/rebar/src/rebar_prv_plugins.erl
- apps/rebar/test/rebar_dir_SUITE.erl
- apps/rebar/test/rebar_hooks_SUITE.erl
`["src"]` becomes the default for `src_dirs`.  It was de facto standard because all calls to `rebar_dir:src_dirs/2` were using it as a default.
Both `REBAR_APP_DIRS` and `REBAR_SRC_DIRS` are relative now. Note that those were undocumented for now so I think it's appropriate to change their values. `REBAR_APP_DIRS` previously pointed to non-existing directories anyways, same as `REBAR_SRC_DIRS`.
Changed the testcase to test whether all env variables are exported.
Closes #2869
> REBAR_SRC_DIRS and REBAR_APP_DIRS fix by making `rebar_dir:src_dirs/1` options default to `["src"]`

- apps/rebar/rebar.config
- apps/rebar/test/rebar_dialyzer_SUITE.erl
- vendor/erlware_commons/README.md
- vendor/erlware_commons/hex_metadata.config
- vendor/erlware_commons/rebar.config
- vendor/erlware_commons/rebar.config.script
- vendor/erlware_commons/src/ec_cmd_log.erl
- vendor/erlware_commons/src/ec_date.erl
- vendor/erlware_commons/src/ec_dict.erl
- vendor/erlware_commons/src/ec_dictionary.erl
- vendor/erlware_commons/src/ec_file.erl
- vendor/erlware_commons/src/ec_git_vsn.erl
- vendor/erlware_commons/src/ec_lists.erl
- vendor/erlware_commons/src/ec_plists.erl
- vendor/erlware_commons/src/ec_rbdict.erl
- vendor/erlware_commons/src/ec_semver.erl
- vendor/erlware_commons/src/ec_talk.erl
- vendor/erlware_commons/src/ec_vsn.erl
- vendor/erlware_commons/src/erlware_commons.app.src
- vendor/relx/hex_metadata.config
- vendor/relx/priv/templates/vm_args
- vendor/relx/src/relx.app.src
- vendor/relx/src/rlx_assemble.erl
- vendor/relx/src/rlx_overlay.erl
- vendor/relx/src/rlx_util.erl
Not ready to merge as there is a need for a manual patch (see https://github.com/erlware/relx/pull/937) but I wanted to know what CI says on all the versions.
> Bump relx and erlware commons

- .github/workflows/publish.yml
I believe that the OTP org, which has the parent org for this repo, has narrowed permissions for github action tokens since the last release.
We can ask for more permissions for this with the [proper permissions declaration](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions).
This PR is an attempt at turning this on so we can publish Rebar3 3.23.0 by unlocking the `contents` permission in write mode on tagged pushes, which should unblock us. If it doesn't work I'll need to go back to manually tagging and maybe figuring out local containers for build artifact uploads.
> Fix release workflow permissions

- apps/rebar/src/rebar.hrl
- apps/rebar/src/rebar_compiler_format.erl
- apps/rebar/test/rebar_compiler_format_SUITE.erl
They've been enabled almost a year ago since [3.22.0](https://github.com/erlang/rebar3/releases/tag/3.22.0).
I've [started gathering feedback on the Erlang Forums about it](https://erlangforums.com/t/rebar3-upgrades/1558/6), and have been using it the whole time. 
Once a long enough period has gone without any significant opposition, I'll merge this, with instructions on how to turn this off on the docs site.
> Turn rich compiler errors on by default

- apps/rebar/rebar.config
- rebar.config
Since erlware_commons bumped to 1.7.0, these options are of no use.
```shell
1
```
> Removed unsused platform_define options

- apps/rebar/rebar.config
- apps/rebar/src/rebar.hrl
* introduced by 5f9b4293bc029e2132d7c442cb5b4480915ea0e4
* CI/CD uses R24 and onwards
* [`erlang:get_stacktrace/0` removed in R23](https://erlang.org/documentation/doc-12.0-rc2/doc/general_info/removed.html#functions-removed-in-otp-23).
> Removed fun_stacktrace

- apps/rebar/src/rebar_uri.erl
- apps/rebar/src/rebar_utils.erl
*  [`OTP_RELEASE` introduced in R21](https://www.erlang.org/doc/system/macros.html#predefined-macros)
* CI/CD uses R24 and onwards.
> Removed OTP_RELEASE macro statements

- apps/rebar/src/rebar_compiler_dag.erl
In some circumstances where files repeatedly get updated, such as when a .xrl file re-generates a .erl file on each compile run, the DAG analysis would repeatedly re-add edges for this file's dependencies (such as include files) to the DAG. Since the digraph module de-dupes vertices but not edges (duplicate edges is a valid use case), we add an explicit check for edge presence before re-adding them.
This should properly prevent unexpected growth of DAG files.
From manual testing, we get stability when going from a fresh DAG, but if it already had many dupes, the file size may jump around a bit regardless.
> Prevent infinite DAG growth

- .github/workflows/main.yml
- .github/workflows/nightly.yml
- .github/workflows/publish.yml
- .github/workflows/shelltests.yml
- README.md
This is keeping in line with our support policy for versions.
Opened as a Draft PR until we can show Dialyzer is happy (✅) and all of CI works (❌).
- Elixir version support needed to be bumped to shelltests, but Elixir does not yet recognize 27.0 in its own versions
- the MacOS tests are failing because brew failed to update to 27.0 (https://github.com/Homebrew/homebrew-core/pull/172171) (also see: https://elixirforum.com/t/erlang-27-not-available-in-homebrew/63897/5)
- we could possibly move to asdf/kerl there, but this will make CI run incredibly longer.
> Bump supported version to OTP-27, deprecate OTP-24

- apps/rebar/src/rebar_prv_completion.erl
* Since the bump to R25, `group_by_namespace/1` follows only branch of the macro
* `group_by_namespace/1` occurs once in `apps/rebar/src/rebar_prv_completion.erl`
> Replaced group_by_namespace/1 by a call to maps:groups_from_list/2

- apps/rebar/rebar.config
- apps/rebar/src/rebar_utils.erl
* introduced by 4bf81cb44e665983089f759047dffade166c3810
* used for a compatibility with R21 and onwards
* CI/CD now uses R25 up to R27.
> Remove hostname checks

- apps/rebar/src/rebar_templater.erl
Handle all file read failures in the same way.
> Log path when plugin template file read fails

- apps/rebar/src/rebar_prv_escriptize.erl
Hi Ferd,
here is a small patch which makes escriptize to be reproducible by setting timestamps for files in zip. It may be usable for reproducible systems such as Guix System and NixOS.
> make escriptize reproducible by setting timestamps for files in zip to unix epoch

- apps/rebar/src/rebar_completion.erl
- apps/rebar/src/rebar_prv_compile.erl
- apps/rebar/src/vendored/r3_hex_erl_tar.hrl
- apps/rebar/test/rebar_compile_SUITE.erl
- apps/rebar/test/rebar_completion_SUITE.erl
- apps/rebar/test/rebar_deps_SUITE.erl
- apps/rebar/test/rebar_upgrade_SUITE.erl
Found via `codespell -S vendor -L cant,manuel,nd` and `typos --hidden --format brief`
> Fix typos again

- apps/rebar/rebar.config
- apps/rebar/src/rebar_utils.erl
* reverted bf27f7ad6cce57d6e4248d8825ab2105443fad98 (@ferd)
* removed `filelib_find_source macro`
* `filelib_find_source` introduced for compatibility with releases prior R20.
> Replaced rebar_utils:find_source/3 by a call to filelib:find_source/3

- bootstrap
* sequel of 58be63e57e5ba245579dd94827edc48892ae9fff
* and also of a4cac026f55cc5c095a6db28ef372e8b4033b790
* definitions are unused since the removal of these macros.
> Cleaned up additional definitions in `bootstrap`

- apps/rebar/src/rebar_prv_manifest.erl
- apps/rebar/test/rebar_manifest_SUITE.erl
Starting the discussion around the actual format to use in the `manifest` plugin.
For the time being, instead of returning the raw context, I'm basically adopting the same format previously adopted by the [`build_info`](https://github.com/WhatsApp/eqwalizer/blob/main/eqwalizer_rebar3/src/eqwalizer_build_info_prv.erl) plugin, used by the ELP language server. Using the same format avoids changes to ELP itself.
I am also adding a `json` format to make it easier for tools to consume the information.
Generate build information for the Erlang LS repo via ELP (internally using the `build_info` plugin):
```
elp build-info --project ~/git/github/erlang-ls/erlang_ls --to /tmp/erlang-ls-build
```
Locally modify ELP to use the `experimental manifest` plugin instead, then:
```
elp build-info --project …
```
> Tweak manifest plugin to return ELP compatible information.

- apps/rebar/rebar.config
- vendor/relx/hex_metadata.config
- vendor/relx/src/relx.app.src
Since I had already manually ported the changeset between 3.9.0 and 3.10.0, only metadata changed on the update.
> Bump relx vendored copy

- apps/rebar/src/rebar_prv_escriptize.erl
Hi, Fred.
I've already submitted fix related to reproducible escripts generation. Here is minor additional change to make it work with newer Erlang 27.1.
Before patch:
```
% for a in $(seq 1 3); do ./bootstrap 2>&1 >/dev/null; md5sum rebar3; done
4af061db0dffb624cbcc4f791bec4811  rebar3
934a4bb8fc774c651fc88ecd2c906f9d  rebar3
da14315045711bda5bc9f7c99175e715  rebar3
```
After patch:
```
% for a in $(seq 1 3); do ./bootstrap 2>&1 >/dev/null; md5sum rebar3; done
98ec28baced972e9f59b1ff4e84cbc07  rebar3
98ec28baced972e9f59b1ff4e84cbc07  rebar3
98ec28baced972e9f59b1ff4e84cbc07  rebar3
```
Thank you!
> make escriptize reproducible with erlang 27.1

- .github/workflows/main.yml
- README.md
Resolves https://github.com/erlang/rebar3/issues/2903
> Add Rebar3 and Erlang/OTP compatibility list

- rebar.config.sample
I started with adding the `git_subdir` portions, then saw this was missing the `{pkg, _` portions, then finally moved `app_name` to `rebar`, as per rebar3.org.
> Approach the sample config. file to rebar3.org's documentation

- apps/rebar/src/rebar_compiler_format.erl
- apps/rebar/test/rebar_compiler_format_SUITE.erl
This change resolves a bad match error that occurs when a .erl file is empty by falling back to the default error format.
```console
===> Task failed: {{badmatch,[]},
[{rebar_compiler_format,colorize,2,
[{file,
"/home/runner/work/rebar3/rebar3/apps/rebar/src/rebar_compiler_format.erl"},
{line,74}]},
{rebar_compiler_format,format,5,
[{file,
"/home/runner/work/rebar3/rebar3/apps/rebar/src/rebar_compiler_format.erl"},
{line,25}]},
{rebar_base_compiler,
'-format_errors/4-lc$^1/1-1-',4,
[{file,
"/home/runner/work/rebar3/rebar3/apps/rebar/src/rebar_base_compiler.erl"},
{line,278}]},
{rebar_base_compiler,
'-format_errors/4-lc$^0/1-0-',3,
[{file,
"/home/runner/work/rebar3/rebar3/apps/rebar/src/rebar_base_compiler.erl"},
{line,278}]},
{rebar_base_compiler,error_tuple,5,
[{file, …
```
> Fallback to the default error format when a file is empty

- apps/rebar/src/rebar3.erl
tools like mix and gleam only use rebar3 to compile deps and thus don't wnat project_plugins. They can now set this to skip installing those.
I originally was going to check if `bare` was the task but there are too many ways that might be run without being the first command (like rebar3 as prod bare compile) that I figured this was better.
> add env var for skipping project plugins

- apps/rebar/rebar.config
- apps/rebar/src/rebar.app.src.script
- apps/rebar/src/rebar_prv_common_test.erl
- apps/rebar/src/rebar_prv_eunit.erl
- rebar.config
Covers portions of https://github.com/erlang/rebar3/issues/2936, namely the bits about Dialyzer checks for xrl and yrl compilers, and for Common Test and EUnit. 
Dependencies will need to be done in a different pull request.
> OTP-28 readiness (part 1)

- apps/rebar/rebar.config
- vendor/eunit_formatters/hex_metadata.config
- vendor/eunit_formatters/rebar.config
- vendor/eunit_formatters/src/binomial_heap.erl
- vendor/eunit_formatters/src/eunit_formatters.app.src
- vendor/eunit_formatters/src/eunit_progress.erl
Does some fixing for Otp-28.
Bumped the version then re-ran `rebar3 experimental vendor` to refresh the list, and kept the manual edits we had made in other apps.
> Bump eunit_formatters to 0.6.0

- .github/workflows/main.yml
- .github/workflows/nightly.yml
- .github/workflows/publish.yml
- README.md
This increases the CI ranges and the documented values. The 3.25.0 version is not yet released but if this branch merges, I'll be bumping it right after.
> Prepare OTP-28 bump

- .github/workflows/nightly.yml
- .github/workflows/publish.yml
Nightly and Publish tasks have been deprecated for a while. The PR jobs use ubuntu-latest fine, so let's bump everything to use these.
> Bump Runner images for Nightly and release builds

- apps/rebar/src/rebar_resource_v2.erl
Removes arbitrary restriction to 2, 3, 4, or 6-element tuples for (possibly custom) resource specifications.
> Support resources of arbitrary size in rebar3

- apps/rebar/src/rebar_completion_bash.erl
- apps/rebar/test/rebar_completion_SUITE.erl
This PR enhances bash completion for rebar3 by adding file completion support for commands that accept file arguments and fixing completion behavior issues.
- **File completion for test commands**: `ct` and `eunit` now complete `.erl` files and directories
- **File completion for utility commands**: `completion`, `shell`, and `tar` now complete files and directories
- **Fixed escaping issues**: Removed problematic space-appending logic that caused unwanted backslashes
- **Improved completion options**: Changed from `-o nospace` to `-o filenames` for better file handling
- **Added test coverage**: New check_bash_file_completion test validates file completion functionality in CI
**Before (no file completion):**
```bash
$ rebar3 ct --suite test/<Tab>
$ rebar3 eunit --dir <Tab>
```
**After …
> Add file completion support for bash completion

- apps/rebar/rebar.config
The arch line changed from containing `win32` to containing `windows` in `rebar_utils:get_arch()` so to keep things working (and fix CI/CD) by providing the Rebar3 executables in the root project path, we have to update the regex.
> Update escriptize hook to work with newer Windows versions

- apps/rebar/src/rebar_prv_xref.erl
- apps/rebar/test/rebar_xref_SUITE.erl
Rebar offers the possibilty to add xref queries to the rebar.config file.
These queries can take atoms representing names of applications. However, such names were no longer recognized. No longer, because https://github.com/srijan/library_sample shows that it seems to have been possible to use application names.
This is a fix to make rebar3 add applications correctly to the xref machinery.
Test is provided that fails on old code, showing the problem that names are not recognized (and applications are unknown).
> Make xref recognize apps again
